import {
  CarFront,
  ShieldUser,
  Smartphone,
  Link2,
  MessageCircle,
  Brain,
  Waves,
  ShieldCheck,
  Wand2,
  QrCode,
  CalendarClock,
  PackageSearch,
  FileCheck2,
  Stethoscope,
  FileSpreadsheet,
  FileUser,
  PiggyBank,
  Flower2,
  Stamp,
  HeartHandshake,
  UtensilsCrossed,
  PanelsTopLeft,
  VenetianMask,
  Tag,
  Star,
  HandPlatter,
  Plane,
  PartyPopper,
  ScanEye,
  MailSearch,
  BookOpenCheck,
  FileLock2,
  Landmark,
  Signature,
  Calculator,
  Timer,
  Wind,
  Hourglass,
  Warehouse,
  Grid3x3,
  Dices,
  BriefcaseBusiness,
  Gauge,
  type LucideIcon,
} from 'lucide-react'

// Shared by MarketplaceCard and any other UI that renders a tool by its
// marketplaceTools.ts `iconName` string — single source of truth so a new
// tool's icon never silently falls back to the default in one place but
// not another.
export const marketplaceIconMap: Record<string, LucideIcon> = {
  CarFront,
  ShieldUser,
  Gauge,
  Smartphone,
  Link2,
  MessageCircle,
  Brain,
  Waves,
  ShieldCheck,
  Wand2,
  QrCode,
  CalendarClock,
  PackageSearch,
  FileCheck2,
  Stethoscope,
  FileSpreadsheet,
  FileUser,
  PiggyBank,
  Flower2,
  Stamp,
  HeartHandshake,
  UtensilsCrossed,
  PanelsTopLeft,
  VenetianMask,
  Tag,
  Star,
  HandPlatter,
  Plane,
  PartyPopper,
  ScanEye,
  MailSearch,
  BookOpenCheck,
  FileLock2,
  Landmark,
  Signature,
  Calculator,
  Timer,
  Wind,
  Hourglass,
  Warehouse,
  Grid3x3,
  Dices,
  BriefcaseBusiness,
}
