export const MARKETPLACE_CATEGORIES = ['marketing', 'security', 'personal', 'wellness', 'lavoro', 'svago', 'community'] as const
export type MarketplaceCategory = (typeof MARKETPLACE_CATEGORIES)[number]

export interface MarketplaceTool {
  toolName: string
  href: string
  gradient: string
  iconName: string
  title: string
  description: string
  color: string
  category: Exclude<MarketplaceCategory, 'community'>
  requiresSubscription?: boolean
}

/**
 * Shared by the marketplace landing page (category tiles + counts) and each
 * category detail page (the actual tool grid). `t` only needs to resolve
 * plain string keys with no interpolation — every title/description here
 * is a bare message.
 */
export function getMarketplaceTools(t: (key: string) => string): MarketplaceTool[] {
  return [
    {
      toolName: 'qr-generator',
      href: '/marketplace/qr-generator',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Smartphone',
      title: t('qrGenerator'),
      description: t('qrDescription'),
      color: 'gold',
      category: 'marketing',
    },
    {
      toolName: 'fidelity',
      href: '/marketplace/fidelity',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Stamp',
      title: t('fidelity'),
      description: t('fidelityDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'whatsapp-messages',
      href: '/marketplace/whatsapp-messages',
      gradient: 'bg-[var(--ink)]',
      iconName: 'MessageCircle',
      title: t('whatsappMessages'),
      description: t('whatsappDescription'),
      color: 'gold',
      category: 'marketing',
    },
    {
      toolName: 'firma-email',
      href: '/marketplace/firma-email',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Signature',
      title: t('firmaEmail'),
      description: t('firmaEmailDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'link-in-bio',
      href: '/marketplace/link-in-bio',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Link2',
      title: t('linkInBio'),
      description: t('linkInBioDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'offermaker',
      href: '/marketplace/offermaker',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Wand2',
      title: t('offermaker'),
      description: t('offermakerDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'qr-code-pro',
      href: '/marketplace/qr-code-pro',
      gradient: 'bg-[var(--ink)]',
      iconName: 'QrCode',
      title: t('qrCodePro'),
      description: t('qrCodeProDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'svat',
      href: '/marketplace/svat',
      gradient: 'bg-[var(--ink)]',
      iconName: 'ShieldCheck',
      title: t('svat'),
      description: t('svatDescription'),
      color: 'gold',
      category: 'security',
      requiresSubscription: true,
    },
    {
      toolName: 'verifoto',
      href: '/marketplace/verifoto',
      gradient: 'bg-[var(--ink)]',
      iconName: 'ScanEye',
      title: t('verifoto'),
      description: t('verifotoDescription'),
      color: 'gold',
      category: 'security',
      requiresSubscription: true,
    },
    {
      toolName: 'checkmail',
      href: '/marketplace/checkmail',
      gradient: 'bg-[var(--ink)]',
      iconName: 'MailSearch',
      title: t('checkmail'),
      description: t('checkmailDescription'),
      color: 'gold',
      category: 'security',
      requiresSubscription: true,
    },
    {
      toolName: 'antitruffa',
      href: '/marketplace/antitruffa',
      gradient: 'bg-[var(--ink)]',
      iconName: 'BookOpenCheck',
      title: t('antitruffa'),
      description: t('antitruffaDescription'),
      color: 'gold',
      category: 'security',
    },
    {
      toolName: 'verifica-iban',
      href: '/marketplace/verifica-iban',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Landmark',
      title: t('verificaIban'),
      description: t('verificaIbanDescription'),
      color: 'gold',
      category: 'security',
    },
    {
      toolName: 'documento-sicuro',
      href: '/marketplace/documento-sicuro',
      gradient: 'bg-[var(--ink)]',
      iconName: 'FileLock2',
      title: t('documentoSicuro'),
      description: t('documentoSicuroDescription'),
      color: 'gold',
      category: 'security',
      requiresSubscription: true,
    },
    {
      toolName: 'memolife',
      href: '/marketplace/memolife',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Brain',
      title: t('memolife'),
      description: t('memolifeDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      toolName: 'life-calendar',
      href: '/marketplace/life-calendar',
      gradient: 'bg-[var(--ink)]',
      iconName: 'CalendarClock',
      title: t('lifeCalendar'),
      description: t('lifeCalendarDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      toolName: 'garage',
      href: '/marketplace/garage',
      gradient: 'bg-[var(--ink)]',
      iconName: 'CarFront',
      title: t('garage'),
      description: t('garageDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      toolName: 'findo',
      href: '/marketplace/findo',
      gradient: 'bg-[var(--ink)]',
      iconName: 'PackageSearch',
      title: t('findo'),
      description: t('findoDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      toolName: 'digital-receipt',
      href: '/marketplace/digital-receipt',
      gradient: 'bg-[var(--ink)]',
      iconName: 'FileCheck2',
      title: t('digitalReceipt'),
      description: t('digitalReceiptDescription'),
      color: 'gold',
      category: 'lavoro',
      requiresSubscription: true,
    },
    {
      toolName: 'spendly',
      href: '/marketplace/spendly',
      gradient: 'bg-[var(--ink)]',
      iconName: 'PiggyBank',
      title: t('spendly'),
      description: t('spendlyDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      // Test gratuito; il check-up del bilancio usa i dati di Spendly (Base)
      toolName: 'fincheck',
      href: '/marketplace/fincheck',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Gauge',
      title: t('fincheck'),
      description: t('fincheckDescription'),
      color: 'gold',
      category: 'personal',
    },
    {
      // Pagine sotto /viaggi (non /marketplace): gli invitati entrano anche
      // senza abbonamento, il piano serve solo per creare un viaggio.
      toolName: 'travel',
      href: '/viaggi',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Plane',
      title: t('travel'),
      description: t('travelDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      toolName: 'mandala',
      href: '/marketplace/mandala',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Flower2',
      title: t('mandala'),
      description: t('mandalaDescription'),
      color: 'gold',
      category: 'wellness',
    },
    {
      toolName: 'oxygen',
      href: '/marketplace/oxygen',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Wind',
      title: t('oxygen'),
      description: t('oxygenDescription'),
      color: 'gold',
      category: 'wellness',
    },
    {
      toolName: 'focus',
      href: '/marketplace/focus',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Timer',
      title: t('focus'),
      description: t('focusDescription'),
      color: 'gold',
      category: 'wellness',
    },
    {
      toolName: 'neurobalance',
      href: '/marketplace/neurobalance',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Waves',
      title: t('neurobalance'),
      description: t('neurobalanceDescription'),
      color: 'gold',
      category: 'wellness',
      requiresSubscription: true,
    },
    {
      toolName: 'aureya',
      href: '/marketplace/aureya',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Stethoscope',
      title: t('aureya'),
      description: t('aureyaDescription'),
      color: 'gold',
      category: 'wellness',
      requiresSubscription: true,
    },
    {
      toolName: 'preventivi',
      href: '/marketplace/preventivi',
      gradient: 'bg-[var(--ink)]',
      iconName: 'FileSpreadsheet',
      title: t('preventivi'),
      description: t('preventiviDescription'),
      color: 'gold',
      category: 'lavoro',
      requiresSubscription: true,
    },
    {
      toolName: 'magazzino',
      href: '/marketplace/magazzino',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Warehouse',
      title: t('magazzino'),
      description: t('magazzinoDescription'),
      color: 'gold',
      category: 'lavoro',
      requiresSubscription: true,
    },
    {
      toolName: 'calcolatrici',
      href: '/marketplace/calcolatrici',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Calculator',
      title: t('calcolatrici'),
      description: t('calcolatriciDescription'),
      color: 'gold',
      category: 'lavoro',
      requiresSubscription: true,
    },
    {
      toolName: 'trova-lavoro',
      href: '/marketplace/trova-lavoro',
      gradient: 'bg-[var(--ink)]',
      iconName: 'BriefcaseBusiness',
      title: t('trovaLavoro'),
      description: t('trovaLavoroDescription'),
      color: 'gold',
      category: 'lavoro',
      requiresSubscription: true,
    },
    {
      toolName: 'kumani-cv',
      href: '/marketplace/kumani-cv',
      gradient: 'bg-[var(--ink)]',
      iconName: 'FileUser',
      title: t('kumaniCv'),
      description: t('kumaniCvDescription'),
      color: 'gold',
      category: 'personal',
      requiresSubscription: true,
    },
    {
      toolName: 'landing-page',
      href: '/marketplace/landing-page',
      gradient: 'bg-[var(--ink)]',
      iconName: 'PanelsTopLeft',
      title: t('landingPage'),
      description: t('landingPageDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'menu',
      href: '/marketplace/menu',
      gradient: 'bg-[var(--ink)]',
      iconName: 'UtensilsCrossed',
      title: t('menu'),
      description: t('menuDescription'),
      color: 'gold',
      category: 'marketing',
      requiresSubscription: true,
    },
    {
      toolName: 'affinity',
      href: '/marketplace/affinity',
      gradient: 'bg-[var(--ink)]',
      iconName: 'HeartHandshake',
      title: t('affinity'),
      description: t('affinityDescription'),
      color: 'gold',
      category: 'svago',
    },
    {
      toolName: 'veritas',
      href: '/marketplace/veritas',
      gradient: 'bg-[var(--ink)]',
      iconName: 'VenetianMask',
      title: t('veritas'),
      description: t('veritasDescription'),
      color: 'gold',
      category: 'svago',
    },
    {
      toolName: 'mosaic',
      href: '/marketplace/mosaic',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Grid3x3',
      title: t('mosaic'),
      description: t('mosaicDescription'),
      color: 'gold',
      category: 'svago',
    },
    {
      toolName: 'fabula',
      href: '/marketplace/fabula',
      gradient: 'bg-[var(--ink)]',
      iconName: 'Dices',
      title: t('fabula'),
      description: t('fabulaDescription'),
      color: 'gold',
      category: 'svago',
    },
  ]
}
