import type { GuideContent } from '@/lib/antitruffa/types'

// KUMANI Anti-Betrugs-Handbuch, Deutsch (Deutschland, Österreich, Schweiz).
// Angepasst an die italienische Referenzversion (it.ts). Stand: September 2026.
const de: GuideContent = {
  eyebrow: `KUMANI Handbuch · Sicherheit und Prüfung`,
  title: `So schützt du dich vor Online-Betrug`,
  motto: `Nicht alles, was kostenlos ist, ist wenig wert. Dieses Handbuch kann deine Ersparnisse wert sein.`,
  lead: `Betrugsnachrichten von heute haben keine Rechtschreibfehler mehr: Die Täter nutzen künstliche Intelligenz, gefälschte Telefonnummern und Webseiten, die genauso aussehen wie die echten. Dieses Handbuch zeigt dir mit echten Beispielen, wie du Betrug in wenigen Sekunden erkennst und was du tun kannst, wenn schon etwas schiefgelaufen ist.`,
  giftNote: `Ein Geschenk nur für Kumani. Lies es, speichere es und teile es mit den Menschen, die dir wichtig sind: Eltern und Großeltern sind die Lieblingsziele der Betrüger.`,
  stats: [
    { value: `20,9 Mrd. $`, label: `Schäden, die 2025 dem FBI (IC3) in den USA gemeldet wurden` },
    { value: `~16 Mrd. $`, label: `Betrugsschäden, die 2025 der US-Behörde FTC gemeldet wurden` },
    { value: `269 Mio. €`, label: `2025 in Italien durch Online-Betrug erbeutet (Polizia Postale)` },
    { value: `1.829`, label: `Webseiten mit falschen Geldanlagen, die die italienische Aufsicht Consob gesperrt hat` },
  ],
  statsSource: `Quellen: FBI IC3 2025; FTC Consumer Sentinel 2025; Polizia Postale, Jahresbericht 2025; Consob, 24.09.2026.`,
  tenSeconds: {
    title: `Der 10-Sekunden-Test`,
    intro: `Bevor du klickst, antwortest oder bezahlst: Halte kurz an und stell dir diese Fragen. Wenn auch nur eine Antwort "ja" ist, ist es mit großer Wahrscheinlichkeit Betrug.`,
    items: [
      `Werde ich unter Zeitdruck gesetzt oder bedroht (Kontosperrung, Bußgeld, Anzeige)?`,
      `Will jemand Passwörter, Codes, PIN, TAN, Kartendaten oder Fotos meines Ausweises?`,
      `Soll ich per Echtzeitüberweisung, Guthabenkarte, Gutscheinkarte oder Kryptowährung zahlen?`,
      `Werden mir leichtes Geld, Gewinne oder Preise versprochen, die zu schön sind, um wahr zu sein?`,
      `Soll ich mit niemandem darüber sprechen oder am Telefon bleiben?`,
      `Kommt die Nachricht von einer Nummer oder Adresse, die ich nicht kenne, auch wenn sich jemand als Bekannter ausgibt?`,
    ],
  },
  rules: {
    title: `Die 6 goldenen Regeln`,
    items: [
      { title: `Auflegen und selbst zurückrufen`, text: `Bank, Polizei, Krankenkasse, Finanzamt: Wenn sie sich bei dir melden, leg auf und ruf selbst die offizielle Nummer an, die du selbst heraussuchst. Die Nummer auf dem Display kann gefälscht sein.` },
      { title: `Niemals Codes weitergeben`, text: `Kein echter Mitarbeiter fragt dich jemals nach TAN, PIN, Passwort oder dem 6-stelligen WhatsApp-Code. Wer danach fragt, ist ein Betrüger. Immer.` },
      { title: `Öffne die Seite selbst`, text: `Nutze keine Links aus Nachrichten: Öffne die offizielle App oder tipp die Adresse der Webseite selbst in den Browser ein.` },
      { title: `Doppelter Schutz überall`, text: `Schalte die Zwei-Faktor-Authentisierung für E-Mail, Bank, soziale Netzwerke und WhatsApp (Verifizierung in zwei Schritten) ein. Nutze für jeden Dienst ein eigenes Passwort.` },
      { title: `Alles aktuell halten`, text: `Aktuelle Updates für Handy, Computer und Apps schließen die Türen, durch die Betrüger hereinkommen. Installiere Apps nur aus Google Play oder dem App Store.` },
      { title: `Ein Familien-Codewort`, text: `Vereinbart ein geheimes Wort, das ihr nutzt, wenn ein Familienmitglied in einem Notfall um Geld bittet: Stimmen lassen sich heute klonen.` },
    ],
  },
  chapters: [
    {
      id: `messaggi`,
      title: `E-Mail und SMS`,
      intro: `Der meistgenutzte Weg: Beliebte Themen sind Pakete, Banken, Bußgelder und Steuererstattungen.`,
      scams: [
        {
          id: `phishing`,
          title: `Phishing: Die E-Mail, die eine Behörde oder Firma nachahmt`,
          how: `Eine E-Mail mit offiziellem Logo und Ton (Finanzamt, Sparkasse, Krankenkasse, Paketdienst) fordert dich auf, auf einen Link zu klicken. Die Webseite ist eine perfekte Kopie des Originals, oft mit künstlicher Intelligenz erstellt, und soll deine Zugangsdaten oder Kartendaten stehlen. Manchmal hängt auch eine Datei an, die einen Virus installiert.`,
          example: { kind: `email`, from: `Finanzamt <erstattung@elster-rueckzahlung.info>`, text: `Sehr geehrte Steuerzahlerin, sehr geehrter Steuerzahler, Ihnen steht eine Rückerstattung von 312,40 € zu. Bestätigen Sie Ihre Daten innerhalb von 48 Stunden: [Link]` },
          flags: [`Zeitdruck und kurze Fristen`, `Die Absender- oder Webadresse ist nicht die offizielle`, `Es werden Kartendaten, Passwörter oder Online-Banking-Zugänge verlangt`, `Anhänge mit .zip, .html oder .js`],
          todo: [`Nicht klicken: Öffne die offizielle Webseite oder App selbst`, `Melde die E-Mail beim Phishing-Radar der Verbraucherzentrale`, `Wenn du Daten eingegeben hast: Passwörter ändern und die Bank anrufen`],
          ai: `Die Texte haben keine Fehler mehr und die nachgebauten Seiten sehen identisch aus: Verlass dich nicht auf das Aussehen, prüf die Adresse.`,
          vignette: `email`,
        },
        {
          id: `clickfix`,
          title: `Das falsche "Ich bin kein Roboter"`,
          how: `Eine Webseite zeigt dir eine falsche Roboter-Prüfung und bittet dich, bestimmte Tasten zu drücken (zum Beispiel Windows+R, dann Strg+V und Enter). In Wahrheit fügst du einen Befehl ein und führst ihn aus, der einen Virus installiert. Diese Masche heißt ClickFix und hat sich zuletzt stark verbreitet.`,
          flags: [`Eine Prüfung, bei der du Tastenkombinationen drücken sollst`, `Anleitungen, um "Ausführen" oder die Eingabeaufforderung zu öffnen`],
          todo: [`Schließ die Seite: Keine echte Prüfung verlangt, dass du Tasten drückst`, `Wenn du es schon gemacht hast: Internet trennen und den Computer überprüfen lassen`],
        },
        {
          id: `smishing-inps`,
          title: `SMS von "Rentenversicherung" oder "Krankenkasse": Jagd auf deine Dokumente`,
          how: `Eine SMS oder E-Mail im Namen der Deutschen Rentenversicherung, deiner Krankenkasse oder des Finanzamts sagt, du musst deine Daten aktualisieren, sonst verlierst du eine Leistung oder eine Erstattung. Die falsche Seite verlangt IBAN, Fotos von Personalausweis, Gesundheitskarte und Führerschein und sogar ein Selfie mit dem Ausweis. Damit stehlen die Täter deine Identität, eröffnen Konten auf deinen Namen und verkaufen die Dokumente weiter.`,
          example: { kind: `sms`, from: `Krankenkasse`, text: `Ihre Krankenkasse: Ihnen steht eine Beitragserstattung zu. Bitte aktualisieren Sie Ihre Daten noch heute: [Link]` },
          flags: [`Rentenversicherung, Krankenkassen und Finanzamt fordern dich nie per SMS-Link auf, Daten zu aktualisieren`, `Du sollst Fotos deiner Dokumente und ein Selfie schicken`],
          todo: [`Prüfe nur auf der offiziellen Webseite oder in der offiziellen App, oder ruf die bekannte Nummer an`, `Schick niemals Fotos von Dokumenten oder Selfies über einen Link`, `Wenn du es schon getan hast: Anzeige erstatten und Konten sowie Online-Zugänge prüfen`],
          vignette: `sms`,
        },
        {
          id: `smishing-multe`,
          title: `SMS zu unbezahlten Bußgeldern, Maut und Kfz-Steuer`,
          how: `Du bekommst eine SMS über einen kleinen Betrag, der "sofort" bezahlt werden muss: ein Bußgeld, eine offene Maut, die Kfz-Steuer. Die falsche Seite verlangt deine Kartendaten. Diese Nachrichten werden massenhaft verschickt, oft auch mit ausländischer Maut als Thema.`,
          example: { kind: `sms`, from: `Maut-Service`, text: `Für Ihr Fahrzeug ist eine Mautgebühr von 6,50 € offen. Vermeiden Sie eine Strafgebühr und zahlen Sie hier: [Link]` },
          flags: [`Kleiner Betrag und Druck, um "Zusatzgebühren zu vermeiden"`, `Ein Link in der Nachricht`, `Seite nur für das Smartphone gemacht`],
          todo: [`Echte Bußgelder kommen in Deutschland per Brief, nicht per SMS mit Link`, `Kfz-Steuer wird in der Regel per Lastschrift eingezogen: Prüf im Zweifel beim Zoll oder deiner Bank`, `Gib niemals Kartendaten über einen Link aus einer Nachricht ein`],
          vignette: `sms`,
        },
        {
          id: `pacchi`,
          title: `Paket hängt fest und falsche Zollgebühren`,
          how: `Eine Nachricht im Namen von DHL, Hermes, DPD oder der Post sagt, dein Paket ist blockiert und es fehlen ein paar Euro "Gebühren" oder "Zoll". Das ist eines der häufigsten Themen überhaupt, weil fast jeder gerade auf ein Paket wartet.`,
          example: { kind: `sms`, from: `DHL`, text: `Ihr Paket wird beim Zoll zurückgehalten. Zahlen Sie 1,99 € Gebühren für die Zustellung: [Link]` },
          flags: [`Du weißt nicht, um welches Paket es geht`, `Es werden ein paar Euro per Karte verlangt`],
          todo: [`Verfolge die Sendung über die Seite des Händlers oder des Paketdienstes`, `Echte Zollgebühren zahlst du beim Zusteller oder über offizielle Wege`],
        },
        {
          id: `account-sospeso`,
          title: `"Dein Konto wurde gesperrt" (Netflix, Amazon, PayPal)`,
          how: `E-Mail oder SMS behaupten, die Zahlung für dein Abo sei fehlgeschlagen oder dein Konto werde geschlossen. Es gibt auch eine Telefon-Version: Eine Bandansage kündigt eine teure Bestellung an und bittet dich, die 1 zu drücken, um sie zu stornieren.`,
          example: { kind: `email`, from: `Netflix <hinweis@netflix-kundendienst.com>`, text: `Die Zahlung für dein Abo ist fehlgeschlagen. Aktualisiere deine Daten innerhalb von 24 Stunden, um den Zugang nicht zu verlieren: [Link]` },
          flags: [`Drohung mit Sperrung oder Kündigung`, `Absender mit einer "fast" richtigen Adresse`],
          todo: [`Öffne direkt die App oder die Webseite und prüf dein Konto`, `Drück bei Bandansagen keine Tasten: leg auf`],
        },
        {
          id: `app-malevole`,
          title: `Falsche Banking-Apps und "Updates" per SMS`,
          how: `Eine SMS fordert dich auf, ein "Sicherheitsupdate" deiner Bank oder eine Gesundheits-App über einen Link herunterzuladen. Es ist eine Schad-App (bei Android oft eine .apk-Datei), die "Bedienungshilfen"-Rechte verlangt: So kann sie Bank-Codes mitlesen, dein Konto leerräumen und das Handy löschen.`,
          example: { kind: `sms`, from: `Bank`, text: `Sehr geehrter Kunde, Ihre App ist veraltet. Laden Sie das verpflichtende Sicherheitsupdate herunter: [Link]` },
          flags: [`Ein Link, um eine App außerhalb der Stores zu laden`, `Eine App, die Rechte für Bedienungshilfen verlangt`],
          todo: [`Installiere Apps nur aus Google Play oder dem App Store`, `Wenn du etwas installiert hast: Flugmodus, die Bank von einem anderen Telefon anrufen, das Gerät zurücksetzen`],
        },
      ],
    },
    {
      id: `telefono`,
      title: `Anrufe und Stimmen`,
      intro: `Der teuerste Betrug für Familien: eine freundliche Stimme, eine Nummer, die echt aussieht, und die Angst, die Ersparnisse zu verlieren.`,
      scams: [
        {
          id: `finto-operatore`,
          title: `Der falsche Bankmitarbeiter und der falsche Polizeibeamte`,
          how: `Zuerst kommt eine "Sicherheits-SMS" über eine verdächtige Überweisung, dann der Anruf. Auf dem Display steht die echte Nummer der Bank oder sogar die 110 (sie ist gefälscht, das nennt man Spoofing). Die Person am Telefon wirkt sehr professionell und überredet dich, dein Geld auf ein "sicheres Konto" zu überweisen, ihr Codes zu nennen oder eine Freigabe in der Banking-App zu bestätigen. Falsche Polizeibeamte erzählen oft von Einbrechern in der Nachbarschaft und wollen Bargeld und Schmuck "in Sicherheit bringen".`,
          example: { kind: `call`, from: `Betrugsabteilung (Nummer deiner Bank)`, text: `Guten Tag, wir haben eine verdächtige Überweisung über 2.450 € gestoppt. Um Ihr Geld zu schützen, müssen wir es sofort auf ein Sicherheitskonto übertragen. Bitte legen Sie nicht auf.` },
          flags: [`Geld soll auf ein anderes Konto "in Sicherheit gebracht" werden`, `Zeitdruck und die Bitte, mit niemandem darüber zu sprechen`, `Frage nach TAN, PIN oder einer Freigabe in der App`, `Die Polizei ruft nie mit der 110 an und holt nie Geld oder Wertsachen ab`],
          todo: [`Leg auf und ruf die Bank selbst unter der Nummer auf deiner Karte an, nach ein paar Minuten oder von einem anderen Telefon`, `Keine Bank und keine Polizei verlangt Überweisungen auf ein "sicheres Konto"`, `Wenn du gezahlt hast: sofort die Bank anrufen, um die Überweisung zu stoppen, dann 110 und Anzeige`],
          ai: `Die richtige Nummer auf dem Display beweist gar nichts: Sie lässt sich leicht fälschen.`,
          vignette: `call`,
        },
        {
          id: `voce-clonata`,
          title: `Enkeltrick und Schockanruf mit geklonter Stimme`,
          how: `Beim klassischen Enkeltrick gibt sich jemand am Telefon als Enkel oder Verwandter aus, der dringend Geld braucht. Heute reichen ein paar Sekunden aus einem Video in den sozialen Netzwerken, um die Stimme eines Kindes oder Enkels zu klonen. Es kommt ein verzweifelter Anruf oder eine Sprachnachricht: ein Unfall, eine Festnahme, eine Kaution. Oft kommt danach ein "Anwalt" oder "Bote" an die Tür, um Bargeld und Schmuck abzuholen.`,
          example: { kind: `call`, from: `Unbekannte Nummer`, text: `Oma, ich bin's... ich hatte einen Unfall, ich brauche sofort Geld für den Anwalt, sag Mama nichts!` },
          flags: [`Notfall, Weinen, extreme Eile`, `Du sollst niemandem Bescheid sagen`, `Eine andere Nummer als sonst`],
          todo: [`Leg auf und ruf die Nummer an, die du von deinem Familienmitglied kennst`, `Nutzt euer Familien-Codewort`, `Übergib niemals Geld oder Schmuck an Personen, die an der Tür klingeln`],
          ai: `Mit künstlicher Intelligenz klingt die geklonte Stimme wie die echte: Vertrau nicht der Stimme, sondern dem Rückruf.`,
        },
        {
          id: `supporto-tecnico`,
          title: `Der falsche technische Support`,
          how: `Beim Surfen erscheint ein Fenster im Vollbild mit Alarmton: "Dein Computer ist infiziert, ruf sofort Microsoft an". Der falsche Techniker lässt dich ein Fernwartungsprogramm installieren und kassiert dann ab oder geht in dein Online-Banking.`,
          example: { kind: `popup`, from: `Sicherheitswarnung`, text: `ACHTUNG! Ihr PC ist infiziert. Schalten Sie den Computer nicht aus. Rufen Sie sofort den Support an: +49 ...` },
          flags: [`Alarmtöne und Telefonnummern zum Anrufen`, `Du sollst AnyDesk, TeamViewer oder Ähnliches installieren`],
          todo: [`Microsoft und Apple zeigen niemals Nummern zum Anrufen an`, `Schließ den Browser, notfalls mit Gewalt`, `Installiere nichts auf Bitte von Fremden`],
        },
        {
          id: `luce-gas`,
          title: `Falsche Strom- und Gasanbieter`,
          how: `Ein angeblicher Mitarbeiter deines Energieversorgers, der Stadtwerke oder einer "Energie-Behörde" kündigt einen günstigeren Tarif oder eine Rückzahlung an und fragt nach der Zählernummer auf deiner Rechnung und deiner Bankverbindung. Mit diesen Daten schließen die Täter Verträge ab, die du nie wolltest, oder stehlen deine Daten.`,
          example: { kind: `call`, from: `Energieberatung`, text: `Guten Tag, ab Montag bekommen Sie einen günstigeren Tarif. Können Sie mir kurz die Zählernummer von Ihrer Rechnung bestätigen?` },
          flags: [`Frage nach Zählernummer, IBAN oder einem Foto der Rechnung`, `"Behörden" oder "Ämter", die wegen Angeboten anrufen`],
          todo: [`Gib Zählernummer oder IBAN nie am Telefon heraus`, `Bei Verträgen, die du nicht wolltest, wende dich an deinen Anbieter und die Verbraucherzentrale`],
        },
        {
          id: `sim-swap`,
          title: `Der SIM-Diebstahl (SIM-Swapping)`,
          how: `Mit gefälschten Dokumenten oder einem Komplizen lässt sich der Betrüger eine Ersatz-SIM für deine Nummer ausstellen. Dein Handy hat plötzlich kein Netz mehr und er bekommt die SMS mit den Bank-Codes.`,
          flags: [`Das Handy zeigt plötzlich "Kein Netz" oder "Nur Notrufe"`],
          todo: [`Ruf sofort deinen Mobilfunkanbieter und die Bank von einem anderen Telefon an`, `Schalte die SIM-PIN ein`, `Nutze lieber die Freigabe in der Banking-App als SMS-Codes`],
        },
      ],
    },
    {
      id: `chat`,
      title: `WhatsApp, soziale Netzwerke und Chats`,
      intro: `Hier läuft der Betrug über Vertrauen: ein Familienmitglied, ein Freund, jemand, der sich für dich zu interessieren scheint.`,
      scams: [
        {
          id: `finto-figlio`,
          title: `"Hallo Mama, das ist meine neue Nummer"`,
          how: `Eine unbekannte Nummer schreibt und gibt sich als dein Sohn oder deine Tochter aus: Das Handy ist kaputt, das ist die neue Nummer. Nach ein paar Nachrichten kommt die Bitte: eine dringende Überweisung für eine Rechnung, "ich geb's dir morgen zurück". Dieselbe Masche gibt es als "Hallo Papa".`,
          example: { kind: `chat`, from: `+49 15x xxxxxxx`, text: `Hallo Mama, mein Handy ist ins Wasser gefallen, das ist meine neue Nummer, speicher sie ab. Ich muss dringend eine Rechnung bezahlen, kannst du das überweisen? Morgen bekommst du alles zurück ❤️` },
          flags: [`Unbekannte Nummer, die sich als Familienmitglied ausgibt`, `Nennt weder deinen Namen noch Spitznamen`, `Weicht einem Anruf aus`],
          todo: [`Ruf die alte Nummer deines Familienmitglieds an`, `Stell eine Frage, die nur die echte Person beantworten kann`, `Nutzt euer Familien-Codewort`],
          vignette: `whatsapp`,
        },
        {
          id: `codice-6-cifre`,
          title: `"Ich hab dir aus Versehen einen Code geschickt": der Konto-Diebstahl`,
          how: `Ein Freund (dessen Konto in Wahrheit schon gestohlen ist) bittet dich, ihm einen 6-stelligen Code weiterzuleiten, der "aus Versehen" bei dir gelandet ist, oder für seine Nichte bei einem Wettbewerb abzustimmen. Es ist der Bestätigungscode deines WhatsApp-Kontos: Wenn du ihn weitergibst, verlierst du das Konto und der Betrüger bittet alle deine Kontakte um Geld.`,
          example: { kind: `chat`, from: `Markus`, text: `Hi! Hast du einen 6-stelligen Code bekommen? Den hab ich aus Versehen an deine Nummer geschickt, kannst du ihn mir bitte weiterleiten?` },
          flags: [`Bitte um einen Code, der per SMS kam`, `Links zum "Abstimmen" oder "Bestätigen"`],
          todo: [`Gib Bestätigungscodes niemals weiter, an niemanden`, `Schalte die Verifizierung in zwei Schritten bei WhatsApp ein (PIN und E-Mail)`, `Wenn du das Konto verloren hast: WhatsApp neu installieren, die Nummer bestätigen und die Kontakte warnen`],
        },
        {
          id: `romance`,
          title: `Der Liebesbetrug (Love Scam)`,
          how: `Ein attraktives Profil (Soldat im Auslandseinsatz, Arzt im Ausland, Unternehmer) umwirbt dich wochenlang mit Aufmerksamkeit und Versprechen. Dann kommen die Bitten: Geld für den Zoll, einen Notfall, ein Flugticket. Oft wird daraus auch ein Anlagebetrug mit Kryptowährungen.`,
          flags: [`Die Person trifft dich nie persönlich`, `Herzzerreißende Geschichten und Bitten um Geld`, `Einladung, gemeinsam zu investieren`],
          todo: [`Such die Fotos mit der umgekehrten Bildersuche`, `Schick kein Geld an Menschen, die du nie getroffen hast`, `Sprich mit einer Vertrauensperson darüber`],
          ai: `Fotos, Nachrichten und sogar Videoanrufe können mit künstlicher Intelligenz erzeugt werden.`,
          vignette: `romance`,
        },
        {
          id: `sextortion`,
          title: `Erpressung mit intimen Bildern und der falsche Hacker`,
          how: `Es gibt die Massenversion: Eine E-Mail behauptet, man habe dich über die Webcam gefilmt, und verlangt Geld in Bitcoin, manchmal mit einem alten, gestohlenen Passwort von dir, damit es glaubwürdig wirkt. Meist gibt es gar kein Video. Und es gibt die echte Version: Nach dem Austausch intimer Bilder mit einem falschen Profil folgt die Erpressung.`,
          example: { kind: `email`, from: `Unbekannt`, text: `Ich habe dein Gerät übernommen und dich mit der Webcam aufgenommen. Zahl 530 € in Bitcoin innerhalb von 48 Stunden, sonst schicke ich das Video an alle deine Kontakte.` },
          flags: [`Drohungen, Fristen und Zahlung in Kryptowährung`, `Ein altes Passwort von dir im Text`],
          todo: [`Nicht zahlen und nicht antworten`, `Beweise sichern und Anzeige bei der Polizei erstatten`, `Das genannte Passwort ändern`],
          ai: `Heute lassen sich aus ganz normalen Fotos falsche intime Bilder erstellen: Es ist nicht deine Schuld, erstatte Anzeige.`,
          vignette: `blackmail`,
        },
        {
          id: `lavoro`,
          title: `Leichte Jobs von zu Hause und bezahlte "Likes"`,
          how: `Eine Nachricht auf WhatsApp oder Telegram bietet 50 bis 300 € am Tag für "Likes" oder Bewertungen. Die ersten Zahlungen kommen wirklich, um dein Vertrauen zu gewinnen. Dann landest du in einer Gruppe, in der du Geld einzahlen musst, um "Premium-Aufgaben freizuschalten".`,
          example: { kind: `chat`, from: `HR Recruiterin`, text: `Hallo! Wir suchen Teilzeitkräfte: 50 bis 300 € am Tag von zu Hause, einfach Videos auf YouTube liken. Interesse?` },
          flags: [`Jobangebote, um die du nie gebeten hast`, `Um zu verdienen, musst du erst zahlen`, `Du sollst fremdes Geld empfangen und weiterleiten`],
          todo: [`Ein echter Job verlangt nie Geld von dir`, `Stell dein Konto niemandem zur Verfügung: Als "Finanzagent" machst du dich wegen Geldwäsche strafbar`],
          vignette: `job`,
        },
      ],
    },
    {
      id: `acquisti`,
      title: `Einkäufe, Kleinanzeigen und Urlaub`,
      intro: `Unwiderstehliche Preise, übertrieben nette Verkäufer und Eile beim Abschluss: Das Drehbuch ist immer dasselbe.`,
      scams: [
        {
          id: `negozi-falsi`,
          title: `Falsche Online-Shops mit Werbung in sozialen Netzwerken`,
          how: `Eine gesponserte Anzeige verspricht "Lagerräumung, minus 80 %" auf Markenschuhe, Taschen oder Elektronik. Die Seite, oft mit künstlicher Intelligenz erstellt, wirkt echt, aber die Ware kommt nie an oder ist gefälscht. Es kursieren auch viele falsche Konzerttickets.`,
          example: { kind: `ad`, from: `Gesponsert`, text: `GESCHÄFTSAUFGABE! Alles minus 80 %, nur heute. Letzte Stücke verfügbar 🔥` },
          flags: [`Unrealistische Rabatte und ein Countdown`, `Kein Impressum, keine Adresse, kein Kontakt`, `Zahlung nur per Vorkasse-Überweisung oder Kryptowährung`],
          todo: [`Nutze Zahlungen mit Käuferschutz (Kreditkarte, PayPal "Waren und Dienstleistungen")`, `Such nach Bewertungen auf anderen Seiten`, `Sei vorsichtig bei Seiten, die erst seit ein paar Tagen existieren`],
          vignette: `shop`,
        },
        {
          id: `marketplace`,
          title: `Der falsche Käufer auf Kleinanzeigen, Vinted und Marketplace`,
          how: `Du verkaufst etwas und ein "Käufer" schreibt, er habe schon über einen Versandservice bezahlt: Du musst nur auf einen Link klicken, um "das Geld zu erhalten". Die Seite verlangt deine Kartendaten. Oder der Verkäufer will eine Anzahlung per Überweisung und verschwindet dann.`,
          example: { kind: `chat`, from: `Käufer`, text: `Ich habe schon über den Versandservice bezahlt, klick hier, um zu bestätigen und das Geld auf deine Karte zu bekommen: [Link]` },
          flags: [`Aufforderung, den Chat der Plattform zu verlassen`, `Um Geld zu "empfangen", sollst du deine Kartendaten eingeben`, `Zahlungsanforderungen von Fremden in Bezahl-Apps`],
          todo: [`Bleib immer im Chat und im Bezahlsystem der Plattform`, `Um Geld zu empfangen, brauchst du nie deine Kartendaten`, `Melde den Nutzer in der App`],
        },
        {
          id: `case-vacanza`,
          title: `Ferienwohnungen und Mietwohnungen, die es nicht gibt`,
          how: `Anzeigen mit wunderschönen Fotos (gestohlen oder erzeugt) und niedrigen Preisen. Der "Vermieter" lebt im Ausland und will eine hohe Anzahlung per Überweisung. Bei der Ankunft gibt es die Wohnung nicht oder sie gehört jemand anderem. Dasselbe Schema gibt es bei Wohnungen für Studierende.`,
          flags: [`Hohe Anzahlung, bevor du die Wohnung gesehen hast`, `Zahlung außerhalb der Plattform`, `Der Vermieter ist persönlich nie erreichbar`],
          todo: [`Zahl nur innerhalb der Buchungsplattform`, `Prüf die Adresse auf einer Karte und die Fotos mit der umgekehrten Bildersuche`, `Überweise nie eine Kaution für eine Wohnung, die du nicht besichtigt hast`],
        },
        {
          id: `qr`,
          title: `Manipulierte QR-Codes (Quishing)`,
          how: `Auf Parkscheinautomaten und Ladesäulen werden Aufkleber mit einem QR-Code "Parken bezahlen" geklebt, der zu einer falschen Seite führt. Derselbe Trick steckt in falschen Strafzetteln unter dem Scheibenwischer, Paket-Benachrichtigungen und E-Mails, in denen du "zur Kontoprüfung scannen" sollst.`,
          flags: [`Aufkleber über dem Original-QR-Code`, `Nach dem Scannen öffnet sich eine seltsame Adresse`],
          todo: [`Bezahl das Parken über die offizielle App der Stadt oder des Betreibers`, `Prüf immer die Adresse, die sich nach dem Scannen öffnet`],
          vignette: `qr`,
        },
        {
          id: `premi`,
          title: `Gewinne, Lotterien und Erbschaften`,
          how: `"Glückwunsch, du hast ein iPhone gewonnen!": Du musst nur 2 € Versand zahlen. In Wahrheit schließt du ein verstecktes Abo über deine Karte ab. Varianten: Millionen-Erbschaften von Notaren im Ausland, Gewinne im Namen von Supermärkten.`,
          example: { kind: `sms`, from: `Gewinn`, text: `Glückwunsch! Du wurdest ausgewählt und kannst ein iPhone 17 gewinnen. Zahl nur 2 € Versand: [Link]` },
          flags: [`Gewinne bei Wettbewerben, an denen du nie teilgenommen hast`, `Kleine Gebühren, um den Gewinn zu erhalten`],
          todo: [`Wenn du nicht mitgemacht hast, hast du nicht gewonnen`, `Zahl nie Gebühren, um einen Gewinn zu erhalten`],
        },
      ],
    },
    {
      id: `soldi`,
      title: `Geldanlage und Finanzen`,
      intro: `Die höchsten Verluste: oft die Ersparnisse eines ganzen Lebens, verloren in wenigen Monaten.`,
      scams: [
        {
          id: `investimenti`,
          title: `Geldanlage mit falschen Promis (Deepfake) und falschen Brokern`,
          how: `Eine Anzeige oder ein falscher Zeitungsartikel zeigt eine Politikerin, einen TV-Star oder einen bekannten Unternehmer, die "das Geheimnis zum schnellen Geld" verraten. Du hinterlässt deine Nummer, ein "Berater" ruft an, lässt dich ein Fernwartungsprogramm installieren und zeigt dir falsche Gewinne. Wenn du dein Geld abheben willst, verlangt er "Steuern" und "Freischaltgebühren". Variante: eine wochenlange Chat-Bekanntschaft, dann die Einladung, in Kryptowährungen zu investieren.`,
          example: { kind: `ad`, from: `Aktuelle Nachrichten`, text: `Das Geheimnis, das die Banken dir verschweigen: Mit nur 250 € verdienst du 1.500 € pro Woche. Sieh dir das Interview an.` },
          flags: [`Garantierte oder extrem hohe Renditen`, `Promis, die Geldanlagen "empfehlen"`, `Du sollst AnyDesk oder ähnliche Apps installieren`, `Um Geld abzuheben, musst du zahlen`],
          todo: [`Prüf den Anbieter in der Unternehmensdatenbank der BaFin`, `Such im Internet nach dem Namen der Plattform und dem Wort "Betrug"`, `Installiere niemals Fernwartungs-Apps`],
          ai: `Betrüger nutzen immer öfter Deepfake-Videos bekannter Politiker und Prominenter: Ein bekanntes Gesicht ist keine Garantie.`,
          vignette: `invest`,
        },
        {
          id: `recupero-fondi`,
          title: `Wer verspricht, verlorenes Geld zurückzuholen`,
          how: `Nach einem Betrug meldet sich ein falscher Anwalt, eine "Rückholfirma" oder sogar eine falsche "Polizei" oder "Europol": Dein Geld sei gefunden, aber um es freizugeben, brauche es Anwaltskosten. Das ist ein zweiter Betrug am selben Opfer.`,
          flags: [`Sie melden sich bei dir und wissen vom Betrug`, `Sie verlangen eine Vorauszahlung`],
          todo: [`Keine Behörde verlangt Geld, um dir gestohlenes Geld zurückzugeben`, `Sprich nur mit der Polizei und mit Anwälten, die du selbst auswählst`],
        },
        {
          id: `beneficenza`,
          title: `Falsche Spendenaufrufe`,
          how: `Nach Hochwasser, Erdbeben oder Kriegen tauchen Seiten auf, die echte Hilfsorganisationen nachahmen, private IBANs und Spendenaktionen mit rührenden Fotos, manchmal mit künstlicher Intelligenz erzeugt.`,
          flags: [`IBAN auf den Namen einer Privatperson`, `Neu erstellte, sehr emotionale Seiten`],
          todo: [`Spende nur über die offizielle Webseite der Organisation`, `Nie an eine IBAN, die du im Chat bekommen hast`],
        },
      ],
    },
    {
      id: `identita`,
      title: `Digitale Identität und persönliche Daten`,
      intro: `Deine Daten sind Geld wert: Damit werden Konten eröffnet, Kredite beantragt und andere Betrügereien glaubwürdiger gemacht.`,
      scams: [
        {
          id: `spid`,
          title: `Identitätsdiebstahl mit Online-Ausweis und BundID`,
          how: `Mit gestohlenen Dokumenten und Selfies (zum Beispiel aus einer falschen Krankenkassen-SMS) oder mit erbeuteten Zugangsdaten eröffnen Betrüger Konten und Kredite auf deinen Namen, schließen Verträge ab oder versuchen, über Online-Dienste an deine Daten zu kommen. Manche falschen Seiten fragen gezielt nach der PIN deines Online-Ausweises oder nach deinen BundID-Zugangsdaten.`,
          flags: [`Post zu Konten, Krediten oder Verträgen, die du nie beantragt hast`, `Erstattungen oder Zahlungen, die nicht ankommen`, `Jemand fragt nach deiner Ausweis-PIN`],
          todo: [`Schick nie Fotos von Dokumenten oder Selfies über einen Link`, `Gib die PIN deines Online-Ausweises nur in der offiziellen AusweisApp ein, nie auf einer Webseite oder am Telefon`, `Bei Diebstahl: Anzeige erstatten, die Online-Ausweisfunktion über den Sperr-Notruf 116 116 sperren lassen und deine Konten prüfen`],
          vignette: `identity`,
        },
        {
          id: `data-breach`,
          title: `Wenn der Betrüger deine Daten schon kennt`,
          how: `Nach einem Datendiebstahl bei einem Unternehmen kennen Betrüger Name, Adresse, Kundennummer und letzte Einkäufe. Damit machen sie Nachrichten und Anrufe glaubwürdig, manchmal geben sie sich sogar als die betroffene Firma oder als "Polizei" aus.`,
          flags: [`Sie wissen viel über dich und verlangen trotzdem Daten oder Geld`],
          todo: [`Dass jemand deine Daten kennt, macht ihn nicht vertrauenswürdig`, `Ändere deine Passwörter und nutze einen Passwort-Manager`, `Prüf deine E-Mail-Adresse mit dem HPI Identity Leak Checker (sec.hpi.de/ilc) oder auf haveibeenpwned.com`],
        },
      ],
    },
    {
      id: `aziende`,
      title: `Für Selbstständige und Unternehmen`,
      intro: `Handwerker, Händler und Freiberufler sind perfekte Ziele: Sie bezahlen jeden Tag Rechnungen.`,
      scams: [
        {
          id: `iban-fattura`,
          title: `Die geänderte IBAN auf der Rechnung und der falsche Chef`,
          how: `Das E-Mail-Postfach eines Lieferanten wird gehackt, oder die Betrüger nutzen eine fast identische Adresse. Es kommt eine Mitteilung mit der "neuen IBAN" für Zahlungen. Variante (CEO-Fraud): Der falsche Inhaber verlangt eine dringende und vertrauliche Überweisung. Solche Fälle können Unternehmen sehr viel Geld kosten.`,
          example: { kind: `email`, from: `Buchhaltung <buchhaltung@lieferant-gmbh.co>`, text: `Wir informieren Sie, dass sich unsere Bankverbindung aus Prüfungsgründen geändert hat. Bitte überweisen Sie ab sofort nur noch auf die neue IBAN.` },
          flags: [`Änderung der IBAN per E-Mail`, `Eile und Geheimhaltung bei einer Überweisung`],
          todo: [`Prüf jede IBAN-Änderung telefonisch, mit der Nummer, die du schon gespeichert hast`, `Schalte die Zwei-Faktor-Authentisierung für das E-Mail-Postfach ein`, `Große Überweisungen prüfen immer zwei Personen`],
          vignette: `invoice`,
        },
      ],
    },
  ],
  victim: {
    title: `Betrogen worden? Was du sofort tun kannst`,
    intro: `Schäm dich nicht: Du bist das Opfer, nicht der Täter. Schnelles Handeln in den ersten Stunden kann viel ausmachen.`,
    steps: [
      { title: `Alles sperren`, text: `Sperr Karten und Zugänge in der Banking-App oder über die Nummer deiner Bank. Rund um die Uhr hilft der Sperr-Notruf 116 116 (aus dem Ausland +49 116 116): Damit sperrst du Bankkarten, Kreditkarten, Online-Banking und die Online-Ausweisfunktion.` },
      { title: `Überweisung zurückholen lassen`, text: `Ruf sofort deine Bank an und bitte darum, die Überweisung zu stoppen oder zurückzurufen: Bei Echtzeitüberweisungen zählt jede Minute.` },
      { title: `Konten absichern`, text: `Ändere deine Passwörter (zuerst E-Mail und Bank), schalte die Zwei-Faktor-Authentisierung ein und melde Geräte ab, die du nicht kennst.` },
      { title: `Beweise sammeln`, text: `Screenshots von Nachrichten und Chats, E-Mails, Telefonnummern, die IBAN des Empfängers, Kontoauszüge, Links. Lösch nichts.` },
      { title: `Anzeige erstatten`, text: `Erstatte Anzeige bei jeder Polizeidienststelle oder online über die Onlinewache deines Bundeslandes. Die Anzeige brauchst du auch, um von der Bank eine Erstattung zu verlangen.` },
      { title: `Andere warnen`, text: `Wenn eines deiner Konten gestohlen wurde, warn deine Kontakte: Sie könnten in deinem Namen um Geld gebeten werden.` },
    ],
  },
  contacts: {
    title: `Hier bekommst du Hilfe in Deutschland`,
    intro: `Die offiziellen Nummern und Webseiten. Speicher sie jetzt, bevor du sie brauchst.`,
    items: [
      { name: `Polizei`, detail: `Wenn du in Gefahr bist, gerade betrogen wirst oder jemand an deiner Tür Geld abholen will.`, phone: `110` },
      { name: `Notruf`, detail: `Europaweiter Notruf für Feuerwehr und Rettungsdienst.`, phone: `112` },
      { name: `Sperr-Notruf 116 116`, detail: `Rund um die Uhr: Bankkarten, Kreditkarten, Online-Banking und Online-Ausweis sperren. Aus dem Ausland: +49 116 116.`, phone: `116 116`, url: `https://www.sperr-notruf.de` },
      { name: `Onlinewache der Polizei`, detail: `Anzeige online erstatten, organisiert nach Bundesland: Wähl hier dein Bundesland aus.`, url: `https://portal.onlinewache.polizei.de` },
      { name: `BSI (Bundesamt für Sicherheit in der Informationstechnik)`, detail: `Verständliche Tipps zu Phishing, Passwörtern und sicheren Geräten.`, url: `https://www.bsi.bund.de` },
      { name: `Verbraucherzentrale: Phishing-Radar`, detail: `Aktuelle Warnungen vor Phishing-Mails und die Möglichkeit, verdächtige Nachrichten zu melden.`, url: `https://www.verbraucherzentrale.de/wissen/digitale-welt/phishingradar/phishingradar-aktuelle-warnungen-6059` },
    ],
    note: `Österreich: Polizei 133, Schweiz: Polizei 117 (Notruf überall 112). In sozialen Netzwerken und Apps nutzt du immer die Funktion "Melden" der Plattform (WhatsApp, Facebook, Instagram, Kleinanzeigen, Vinted, Airbnb).`,
  },
  whyReport: {
    title: `Warum eine Anzeige wichtig ist`,
    items: [
      `Damit können Ermittlungen beginnen und die Täter gestoppt werden, bevor sie andere treffen.`,
      `Sie hilft, neue Betrugswellen zu erkennen und zu blockieren.`,
      `Du brauchst sie, um von der Bank eine Erstattung zu verlangen und den Schaden zu begrenzen.`,
      `Sie macht die digitale Welt für alle sicherer.`,
      `Schäm dich nicht: Schämen muss sich der Betrüger, nicht du.`,
    ],
  },
  ui: {
    toc: `Inhalt`,
    print: `Handbuch herunterladen oder drucken`,
    howItWorks: `So funktioniert es`,
    example: `Echtes Beispiel`,
    flags: `Warnsignale`,
    todo: `Was du tun kannst`,
    ai: `Mit künstlicher Intelligenz`,
    checkmailTitle: `Eine verdächtige E-Mail bekommen?`,
    checkmailText: `Mit KUMANI CheckMail prüfst du sie in wenigen Sekunden: Absender, Links, Anhänge und Text unter der Lupe.`,
    checkmailCta: `CheckMail öffnen`,
    updated: `Stand September 2026, mit Daten von FBI, FTC, Polizia Postale, CERT-AgID und Consob.`,
    disclaimer: `Dieses Handbuch dient nur der Information und ersetzt nicht den Rat der Polizei, deiner Bank oder eines Anwalts. Betrugsmaschen ändern sich ständig: Im Zweifel halt an und frag nach.`,
    copyright: `© KUMANI. Du darfst es frei teilen, um anderen zu helfen, sich zu schützen.`,
  },
}

export default de
