import type { GuideContent } from '@/lib/antitruffa/types'

// KUMANI anti-scam manual: English (UK first, with US references).
// Adapted from the Italian reference version (it.ts), not a literal translation.
// Main sources: FBI IC3, FTC, Polizia Postale, CERT-AgID, Consob, Report Fraud,
// Stop Scams UK. Updated September 2026.
const en: GuideContent = {
  eyebrow: `KUMANI Manual · Safety and Verification`,
  title: `How to protect yourself from online and doorstep scams`,
  motto: `Not everything free is worth little. This one could be worth your savings.`,
  lead: `Today's scams no longer have spelling mistakes: they use artificial intelligence, faked phone numbers and websites that look exactly like the real ones. This manual shows you, with real examples, how to spot them in a few seconds and what to do if something has already gone wrong.`,
  giftNote: `A gift for Kumani members only. Read it, save it and share it with the people you love: parents and grandparents are the scammers' favourite targets.`,
  stats: [
    { value: `$20.9bn`, label: `in losses reported to the FBI's Internet Crime Complaint Center in 2025 (USA)` },
    { value: `~$16bn`, label: `in fraud losses reported to the US Federal Trade Commission in 2025` },
    { value: `€269m`, label: `stolen through online fraud in Italy in 2025 (Polizia Postale)` },
    { value: `1,829`, label: `fake investment websites blocked by Italy's market regulator Consob` },
  ],
  statsSource: `Sources: FBI IC3 Internet Crime Report 2025; FTC Consumer Sentinel 2025; Polizia Postale annual report 2025; Consob, 24/09/2026.`,
  tenSeconds: {
    title: `The 10-second test`,
    intro: `Before you click, reply or pay, stop and ask yourself these questions. If even one answer is "yes", it is almost certainly a scam.`,
    items: [
      `Is it rushing me or threatening me (account blocked, a fine, legal action)?`,
      `Is it asking for passwords, codes, PINs, card details or photos of my ID?`,
      `Is it asking me to pay by instant bank transfer, top-up, gift card or cryptocurrency?`,
      `Is it offering easy money, prizes or prices that are too good to be true?`,
      `Is it asking me to keep it secret or to stay on the phone?`,
      `Does it come from a number or address I don't know, even if it claims to be someone I know?`,
    ],
  },
  rules: {
    title: `The 6 golden rules`,
    items: [
      { title: `Hang up and call back yourself`, text: `Your bank, the police, the tax office, a benefits agency: if they contact you, hang up and call the official number you look up yourself. The number shown on your screen can be faked.` },
      { title: `Never share codes with anyone`, text: `No genuine company will ever ask for a one-time passcode, PIN, password or your 6-digit WhatsApp code. Anyone who asks is a scammer, every time.` },
      { title: `Open the website yourself`, text: `Don't use links you receive: open the official app, or type the website address into your browser yourself.` },
      { title: `Two-step protection everywhere`, text: `Turn on two-factor authentication for your email, bank, social media and WhatsApp (two-step verification). Use a different password for every service.` },
      { title: `Keep everything updated`, text: `An up-to-date phone, computer and apps close the doors scammers use to get in. Only install apps from Google Play or the App Store.` },
      { title: `A family password`, text: `Agree on a secret word to use if a family member asks for money in an emergency: voices can now be cloned.` },
    ],
  },
  chapters: [
    {
      id: `messaggi`,
      title: `Emails and text messages`,
      intro: `The most used channel of all: the favourite themes are deliveries, banks, fines and tax refunds.`,
      scams: [
        {
          id: `phishing`,
          title: `Phishing: the email that pretends to be an organisation or a company`,
          how: `An email with an official logo and tone (HMRC, your bank, a well-known company) asks you to click a link. The website is a perfect copy of the real one, often built with artificial intelligence, and it exists to steal your passwords, online account logins or card details. Sometimes there is an attachment that installs a virus.`,
          example: { kind: `email`, from: `HMRC <refunds@hmrc-tax-refund.info>`, text: `Dear taxpayer, you are due a tax refund of £312.40. To receive it, please confirm your details within 48 hours: [link]` },
          flags: [`Rush and very short deadlines`, `The sender's address or the website is not the official one`, `It asks for card details, passwords or your online account login`, `Attachments ending in .zip, .html or .js`],
          todo: [`Don't click: open the official website or app yourself`, `In the UK, forward suspicious emails to report@phishing.gov.uk`, `If you entered any details: change your passwords and call your bank`],
          ai: `The text no longer has mistakes and cloned websites look identical: don't trust how it looks, check the address.`,
          vignette: `email`,
        },
        {
          id: `clickfix`,
          title: `The fake "I'm not a robot" check`,
          how: `A website shows you a fake anti-robot check and asks you to press some keys (for example Windows+R, then Ctrl+V and Enter). In reality you are pasting and running a command that installs a virus. This trick, called ClickFix, has spread a lot recently.`,
          flags: [`A "check" that asks you to press key combinations`, `Instructions to open "Run" or the command window`],
          todo: [`Close the page: no genuine check asks you to press keys`, `If you've already done it, disconnect from the internet and have your computer checked`],
        },
        {
          id: `smishing-inps`,
          title: `The fake government or benefits text: after your documents`,
          how: `A text that seems to come from a government department (HMRC, the DWP or "GOV.UK") says you must update your details so you don't lose a payment, a tax refund or a benefit. The fake website asks for your bank details, photos of your passport or driving licence, payslips and even a selfie holding your ID. With all this, scammers steal your identity, take over your online government accounts and sell your documents.`,
          example: { kind: `sms`, from: `GOV.UK`, text: `GOV.UK: your benefit payment has been put on hold. Update your details today to avoid losing it: [link]` },
          flags: [`Government departments don't ask you to update your details through a link in a text`, `Requests for photos of your documents and a selfie`],
          todo: [`Only check on gov.uk or in the official app, typing the address yourself`, `Never send photos of your documents or a selfie through a link`, `If you already have: report it and check your online accounts and the bank details where your payments go`],
          vignette: `sms`,
        },
        {
          id: `smishing-multe`,
          title: `Texts about unpaid fines, road tolls and vehicle tax`,
          how: `A text arrives about a small amount "to be paid now": a parking fine, an unpaid road toll or bridge charge, or DVLA vehicle tax. The fake website asks for your card details. These campaigns go out in huge waves, to millions of phones at once.`,
          example: { kind: `sms`, from: `Road Tolls`, text: `You have an unpaid toll charge of £6.50. Avoid a penalty by paying here today: [link]` },
          flags: [`A small amount and pressure to "avoid a penalty"`, `A link in the message`, `A page designed only for smartphones`],
          todo: [`Check real fines and charges on gov.uk or on the official council or operator website`, `The DVLA says it never asks for bank or card details by text or email`, `Never enter card details on a page you reached from a link in a text`],
          vignette: `sms`,
        },
        {
          id: `pacchi`,
          title: `Parcels on hold and fake customs fees`,
          how: `A message from "Royal Mail", "Evri", "DHL" or another courier says your parcel is stuck and you need to pay a small "redelivery fee" or "customs charge". It is one of the most common scams of all, because almost everyone is waiting for a parcel.`,
          example: { kind: `sms`, from: `Royal Mail`, text: `Your parcel is being held at customs. Pay £1.99 in charges to arrange delivery: [link]` },
          flags: [`You don't know which parcel it is about`, `It asks for a few pounds by card`],
          todo: [`Track your delivery from the seller's or courier's official website`, `Genuine customs charges are paid to the courier through its official channels`],
        },
        {
          id: `account-sospeso`,
          title: `"Your account has been suspended" (Netflix, Amazon, PayPal)`,
          how: `An email or text says your subscription payment failed or that your account will be closed. There's a phone version too: a recorded voice announces an expensive order and asks you to press 1 to cancel it.`,
          example: { kind: `email`, from: `Netflix <alerts@netflix-support-help.com>`, text: `Your subscription payment could not be processed. Update your details within 24 hours to keep your access: [link]` },
          flags: [`Threats to block or close your account`, `A sender with an "almost" correct address`],
          todo: [`Open the app or website directly and check your account`, `Don't press any keys during recorded calls: hang up`],
        },
        {
          id: `app-malevole`,
          title: `Fake banking apps and "updates" by text`,
          how: `A text asks you to download a "security update" for your banking app, or a health app, from a link. It's a fake app (on Android often an .apk file) that asks for "Accessibility" permissions: this lets it read your bank codes, empty your account and wipe your phone.`,
          example: { kind: `sms`, from: `Bank`, text: `Dear customer, your app is out of date. Download the mandatory security update: [link]` },
          flags: [`A link to download an app outside the official stores`, `An app that asks for Accessibility permissions`],
          todo: [`Only install apps from Google Play or the App Store`, `If you installed something: switch on airplane mode, call your bank from another phone and reset the device`],
        },
      ],
    },
    {
      id: `telefono`,
      title: `Phone calls and voices`,
      intro: `The most expensive scam for families: a kind voice, a number that looks genuine and the fear of losing your savings.`,
      scams: [
        {
          id: `finto-operatore`,
          title: `The fake bank fraud team and the fake police officer`,
          how: `First a "security" text arrives about a suspicious payment, then the phone call. Your screen shows the real number of your bank or the police (it's faked: this is called spoofing). The caller, very professional, persuades you to move your money to a "safe account", to read out your codes or to approve a notification in your banking app. Some victims lose a few hundred pounds, others their life savings.`,
          example: { kind: `call`, from: `Fraud team (your bank's number)`, text: `Good morning, we've stopped a suspicious payment of £2,450. To protect your savings we need to move them to a safe account right away. Please don't hang up.` },
          flags: [`"Protecting your money" by moving it to another account`, `Rush, and being told not to tell anyone`, `Requests for a passcode, PIN or to approve a notification`],
          todo: [`Hang up and call your bank yourself on the number on the back of your card, after a few minutes or from another phone (in the UK you can dial 159)`, `No bank and no police force will ever ask you to transfer money to a safe account`, `If you've paid: call your bank straight away to stop the payment, then the police`],
          ai: `Scammers can fake the number that appears on your screen: seeing the right number proves nothing.`,
          vignette: `call`,
        },
        {
          id: `voce-clonata`,
          title: `The cloned voice of a family member`,
          how: `A few seconds of a video on social media are enough to clone the voice of a son, daughter or grandchild. A desperate call or voice message arrives: an accident, an arrest, a lawyer needed right now. Often a "lawyer" or a courier then turns up at the door to collect cash or jewellery.`,
          example: { kind: `call`, from: `Unknown number`, text: `Grandad, it's me... I've had an accident, I need money for a lawyer right now, please don't tell Mum!` },
          flags: [`An emergency, crying, extreme urgency`, `Being asked not to tell anyone`, `A different number from usual`],
          todo: [`Hang up and call your family member on the number you know`, `Use your family password`, `Never hand over money or jewellery to someone who comes to your door`],
        },
        {
          id: `supporto-tecnico`,
          title: `Fake tech support`,
          how: `While you're browsing, a full-screen window appears with a siren: "Your computer is infected, call Microsoft now". The fake technician gets you to install a remote-control program, then charges you or gets into your online banking.`,
          example: { kind: `popup`, from: `Security warning`, text: `WARNING! Your PC is infected. Do not turn off your computer. Call support immediately: 0800 ...` },
          flags: [`Alarm sounds and phone numbers to call`, `Requests to install AnyDesk, TeamViewer or similar`],
          todo: [`Microsoft and Apple never show phone numbers to call in warnings like these`, `Close the browser, forcing it closed if you have to`, `Never install anything because a stranger asks you to`],
        },
        {
          id: `luce-gas`,
          title: `Fake energy supplier calls`,
          how: `A caller claiming to be from your energy supplier, "the energy regulator" or a government scheme offers a cheaper tariff, a discount or a refund. They ask for your account number, your meter details (such as the MPAN or MPRN on your bill) and your bank details. With these they can switch you to contracts you never asked for or steal your money and identity.`,
          example: { kind: `call`, from: `Energy team`, text: `Good morning, you qualify for our discounted tariff from Monday. Could you just confirm your account number and the meter number on your bill?` },
          flags: [`Requests for account numbers, meter details, bank details or a photo of your bill`, `"Regulators" or "government schemes" calling you with offers`],
          todo: [`Never give account, meter or bank details over the phone to someone who called you`, `If in doubt, hang up and call your supplier on the number on your bill`],
        },
        {
          id: `sim-swap`,
          title: `SIM theft (SIM swap)`,
          how: `Using fake documents or an insider, the scammer gets a copy of your SIM card. Your phone loses its signal and they receive the texts with your bank codes.`,
          flags: [`Your phone suddenly shows "No service" or "Emergency calls only"`],
          todo: [`Call your mobile network and your bank straight away from another phone`, `Set a SIM PIN`, `Choose notifications in your banking app rather than text messages`],
        },
      ],
    },
    {
      id: `domicilio`,
      title: `At your front door`,
      intro: `Not every scam arrives by phone or online. In the UK alone, Trading Standards recorded 5,228 reported cases of doorstep selling and rogue traders in 2021, with £25.8 million lost (National Trading Standards, Friends Against Scams). Many scams start with a knock at the door.`,
      pattern: {
        title: `The trick is always the same`,
        text: `Water, gas, electricity, the council, the police: the uniform changes, the trick does not. Someone you were not expecting, an ID card flashed in a hurry, an urgent reason (a leak, a fault, an inspection, a refund) and one request: to come inside, or to be handed money and jewellery. Often an accomplice slips in while you are distracted.`,
      },
      scams: [
        {
          id: `finto-letturista`,
          title: `The fake meter reader`,
          how: `They knock saying they need to read your water, gas or electricity meter, or check your taps because of a problem in the area. Once inside they ask you to run the water in the bathroom or kitchen and, while you are busy, they or an accomplice look for cash and jewellery. Sometimes they simply ask for cash for an “adjustment” or a “refund”.`,
          example: {
            kind: `notice`,
            from: `Council notice, following a police warning`,
            text: `Residents are asked to be extremely careful with people calling at homes claiming to read water meters. Do not let anyone in unless you have confirmed who they are and, if in doubt, contact the police.`,
          },
          flags: [`The visit was not announced by letter or on your bill`, `They insist on coming in or on you running the taps`, `They ask for cash for adjustments, refunds or deposits`, `They flash their ID quickly or have nothing to identify them`],
          todo: [`Do not open the door to anyone you are not expecting: talk through the closed door or the intercom`, `Call the number on your bill, not one they give you, and ask whether a visit is really planned`, `Many energy and water companies let you set a password their staff will say at the door: ask yours`, `If in doubt call 999 (UK), 911 (US) or 112 (EU) and warn older neighbours and relatives`],
          vignette: `door`,
        },
        {
          id: `finta-fuga-gas`,
          title: `The fake gas leak and the bogus boiler check`,
          how: `They claim to be from the gas board, the water company or the council: “There is a leak in the area, we must check now.” They frighten you and ask you to gather cash and jewellery “to keep them safe”, or they get you out of the house. Other times they demand payment for a “compulsory inspection” that does not exist.`,
          example: {
            kind: `door`,
            from: `At the door`,
            text: `Hello, we are from the gas company. There is a leak in the building, it is dangerous, we need to come in now. Put your cash and jewellery in a bag so they do not get damaged.`,
          },
          flags: [`Sudden alarm and fear: “it is dangerous, quick”`, `They ask you to move or gather money and jewellery`, `They talk about compulsory checks to be paid now, in cash`],
          todo: [`No real engineer asks you to touch your money or jewellery`, `If you really smell gas, get out, do not use switches and call the emergency number on your bill`, `Close the door and call the police`],
        },
        {
          id: `finto-carabiniere-ritiro`,
          title: `Courier fraud: the fake officer who comes to collect`,
          how: `First comes a call from a “police officer” or “bank investigator”, or about a relative in trouble who needs bail. Shortly afterwards a “courier” knocks at the door to collect cash, cards or jewellery. They keep you on the phone so you cannot call anyone.`,
          example: {
            kind: `call`,
            from: `Unknown number`,
            text: `This is the police. Your grandson has caused an accident and needs bail today. We will send a courier to collect it from you in half an hour.`,
          },
          flags: [`Police and banks never send anyone to collect money, cards or jewellery`, `They ask you to stay on the line and tell no one`, `Rush and fear for a relative`],
          todo: [`Hang up, call your relative yourself, then the police from a different phone`, `Never hand anything over, not even to someone with an ID card`, `Use your family password`],
          vignette: `call`,
        },
        {
          id: `finto-funzionario`,
          title: `The fake council, pension or bank official`,
          how: `They claim to be from the council, the pension service, the post office or the bank: they need to check your pension, replace “counterfeit” banknotes, verify documents or hand you a refund. The goal is to get in, see where you keep your money or get cash, cards and PIN numbers.`,
          flags: [`Councils and banks do not send staff to your home without an appointment`, `They ask to see cash, cards, PIN numbers or bank books`, `They talk about counterfeit notes or refunds to collect today`],
          todo: [`Ask for their name and department and call the official number yourself`, `Never show where you keep money or jewellery`, `If needed, book an appointment at the office yourself, with a relative`],
        },
      ],
      poster: {
        title: `Print it and stick it next to your door`,
        lines: [`I do not open the door to people I am not expecting.`, `I ask for ID and call the number on my bill or the official number myself.`, `Nobody collects money or jewellery at home: not the police, not the bank, not engineers.`, `If in doubt, I call the police.`],
        note: `Print it and stick it inside the front door of your parents and grandparents. And talk about it together: people who know are harder to fool.`,
      },
    },
    {
      id: `chat`,
      title: `WhatsApp, social media and chats`,
      intro: `Here the scam works through trust: a family member, a friend, someone who seems interested in you.`,
      scams: [
        {
          id: `finto-figlio`,
          title: `"Hi Mum, I've got a new number"`,
          how: `An unknown number messages you pretending to be your son or daughter: their phone broke, this is the new number. After a few messages comes the request: an urgent bank transfer to pay a bill, "I'll pay you back tomorrow".`,
          example: { kind: `chat`, from: `+44 7xxx xxxxxx`, text: `Hi Mum, I dropped my phone in water, this is my new number, save it. I need to pay an urgent bill, can you do a transfer for me? I'll pay you back tomorrow ❤️` },
          flags: [`An unknown number claiming to be a family member`, `They don't use your name or nicknames`, `They avoid a voice call`],
          todo: [`Call your family member on their old number`, `Ask a question only they would know`, `Use your family password`],
          vignette: `whatsapp`,
        },
        {
          id: `codice-6-cifre`,
          title: `"I sent you a code by mistake": account theft`,
          how: `A friend (whose account has in fact already been stolen) asks you to send them a 6-digit code "that arrived by mistake", or to vote for their niece in a competition. It is the verification code for your own WhatsApp: if you give it away, you lose your account and the scammer asks all your contacts for money.`,
          example: { kind: `chat`, from: `Sarah`, text: `Hi! Did you get a 6-digit code? I sent it to your number by mistake, could you forward it to me please?` },
          flags: [`A request for a code you received by text`, `A link to "vote" or "verify"`],
          todo: [`Never pass on verification codes, to anyone`, `Turn on WhatsApp two-step verification (PIN + email)`, `If you've lost your account: reinstall WhatsApp, verify your number and warn your contacts`],
        },
        {
          id: `romance`,
          title: `Romance scams`,
          how: `An attractive profile (a soldier on a mission, a doctor working abroad, a businessman) courts you for weeks with attention and promises. Then the requests begin: money for customs, an emergency, a plane ticket. It often turns into a cryptocurrency investment scam too.`,
          flags: [`They never meet you in person`, `Heartbreaking stories and requests for money`, `An invitation to invest together`],
          todo: [`Check their photos with a reverse image search`, `Never send money to someone you have never met`, `Talk about it with someone you trust`],
          ai: `Photos, messages and even video calls can be generated with artificial intelligence.`,
          vignette: `romance`,
        },
        {
          id: `sextortion`,
          title: `Sexual blackmail and the fake hacker`,
          how: `There's the mass version: an email claims they filmed you through your webcam and demands money in Bitcoin, sometimes quoting an old stolen password of yours to seem believable. Usually there is no video at all. And there's the real version: after exchanging intimate images with a fake profile, the blackmail begins.`,
          example: { kind: `email`, from: `Unknown`, text: `I have taken control of your device and recorded you through your webcam. Pay £500 in Bitcoin within 48 hours or I will send the video to all your contacts.` },
          flags: [`Threats, deadlines and payment in cryptocurrency`, `An old password of yours in the text`],
          todo: [`Don't pay and don't reply`, `Keep the evidence and report it to the police`, `Change the password they mention`],
          ai: `Fake intimate images can now be created from ordinary photos: it's not your fault, report it.`,
          vignette: `blackmail`,
        },
        {
          id: `lavoro`,
          title: `Easy jobs from home and paid "likes"`,
          how: `A message on WhatsApp or Telegram offers £50 to £300 a day for "liking" videos or writing reviews. The first payments really do arrive, to win your trust. Then you're added to a group where you must pay money to "unlock premium tasks", and you never see it again.`,
          example: { kind: `chat`, from: `HR Recruiter`, text: `Hi! We're looking for part-time helpers: £50-£300 a day from home just liking YouTube videos. Interested?` },
          flags: [`Job offers you never asked for`, `You have to pay before you can earn`, `You're asked to receive other people's money and pass it on`],
          todo: [`A real job never asks you for money`, `Never let anyone use your bank account: you could be treated as a "money mule" and face money laundering charges`],
          vignette: `job`,
        },
      ],
    },
    {
      id: `acquisti`,
      title: `Shopping, listings and holidays`,
      intro: `Irresistible prices, very friendly sellers and a rush to close the deal: the script is always the same.`,
      scams: [
        {
          id: `negozi-falsi`,
          title: `Fake online shops advertised on social media`,
          how: `A sponsored ad announces "warehouse clearance, 80% off" on branded shoes, bags or electronics. The website, often built with artificial intelligence, looks real, but the goods never arrive or are fakes. Fake concert and event tickets are very common too.`,
          example: { kind: `ad`, from: `Sponsored`, text: `SHOP CLOSING DOWN! Everything 80% off, today only. Last items left 🔥` },
          flags: [`Unrealistic discounts and a countdown clock`, `No company details, address or contact information`, `Payment only by bank transfer or cryptocurrency`],
          todo: [`Pay with methods that protect you (credit card, PayPal "Goods and Services")`, `Look for reviews on independent websites`, `Be wary of websites created only a few days ago`],
          vignette: `shop`,
        },
        {
          id: `marketplace`,
          title: `The fake buyer on Gumtree, Vinted and Facebook Marketplace`,
          how: `You're selling something and a "buyer" tells you they've already paid through a delivery service: you just need to click a link to "receive the money". The page asks for your card details. Or it's the seller who asks for a deposit by bank transfer and then disappears.`,
          example: { kind: `chat`, from: `Buyer`, text: `I've already paid through the courier service, click here to confirm and receive the payment on your card: [link]` },
          flags: [`Being asked to leave the platform's chat`, `Being asked for your card details in order to "receive" money`, `Payment requests from strangers on payment apps`],
          todo: [`Always stay in the platform's own chat and payment system`, `You never need to give your card details to receive money`, `Report the user through the app`],
        },
        {
          id: `case-vacanza`,
          title: `Holiday lets and rentals that don't exist`,
          how: `Listings with beautiful photos (stolen or AI-generated) and low prices. The "owner" lives abroad and asks for a large deposit, half the price or more, by bank transfer or top-up. When you arrive, the property doesn't exist or belongs to someone else. Student rentals follow the same pattern.`,
          flags: [`A large deposit before you've seen the property`, `Payment outside the booking platform`, `An owner you can never meet in person`],
          todo: [`Only pay inside the booking platform`, `Check the address on a map and the photos with a reverse image search`, `Be very wary of large deposits requested by bank transfer`],
        },
        {
          id: `qr`,
          title: `Tampered QR codes (quishing)`,
          how: `Stickers with a "pay for parking" QR code are stuck onto parking machines and lead to a fake website. The same trick appears on fake fines tucked under your windscreen wiper, parcel notices and emails asking you to "scan to verify your account".`,
          flags: [`Stickers placed over the original QR code`, `A strange web address after scanning`],
          todo: [`Pay for parking through the council's or the operator's official app`, `Always check the address that opens after you scan`],
          vignette: `qr`,
        },
        {
          id: `premi`,
          title: `Prizes, lotteries and inheritances`,
          how: `"Congratulations, you've won an iPhone!": you just need to pay £2 for delivery. In reality you sign up to a hidden subscription on your card. Variations: million-pound inheritances from foreign lawyers, prizes in the name of supermarkets.`,
          example: { kind: `sms`, from: `Prize`, text: `Congratulations! You've been selected to win an iPhone 17. Just pay £2 for delivery: [link]` },
          flags: [`Winning competitions you never entered`, `Small fees to pay before you get the prize`],
          todo: [`If you didn't enter, you didn't win`, `Never pay fees to receive a prize`],
        },
      ],
    },
    {
      id: `soldi`,
      title: `Investments and money`,
      intro: `The biggest losses: often a lifetime of savings, gone in a few months.`,
      scams: [
        {
          id: `investimenti`,
          title: `Investments with fake celebrities (deepfakes) and fake brokers`,
          how: `An ad or a fake news article shows a politician, a TV personality or a famous business figure revealing "the secret to making money". You leave your number and a "financial adviser" calls, gets you to install a remote-control app and shows you fake profits. When you try to withdraw, you're asked for "taxes" and "release fees". A variation: a chat relationship built up over weeks, then an invitation to invest in cryptocurrency.`,
          example: { kind: `ad`, from: `Today's News`, text: `The secret the banks don't want you to know: with just £250 you can earn £1,500 a week. Watch the interview.` },
          flags: [`Guaranteed or very high returns`, `Celebrities "recommending" investments`, `Requests to install AnyDesk or similar apps`, `You have to pay to withdraw your money`],
          todo: [`In the UK, check the firm on the FCA Register and the FCA Warning List; elsewhere, check with your country's financial regulator`, `Never install remote-access apps`, `Talk to someone you trust before investing`],
          ai: `Videos of famous people "recommending" investments can be deepfakes: no real celebrity is selling you a shortcut to wealth.`,
          vignette: `invest`,
        },
        {
          id: `recupero-fondi`,
          title: `People who promise to recover the money you lost`,
          how: `After a scam, you're contacted by a fake lawyer, a recovery company or even a fake "police" or "Europol": they've found your money, but legal fees are needed to release it. It's a second scam on the same victim.`,
          flags: [`They contact you, already knowing about the scam`, `They ask for payment up front`],
          todo: [`No public body asks for money to give you back what was stolen`, `Only deal with the police and with lawyers you choose yourself`],
        },
        {
          id: `beneficenza`,
          title: `Fake fundraisers`,
          how: `After floods, earthquakes or wars, pages appear that imitate real charities, with private bank accounts and moving photos, sometimes generated with artificial intelligence.`,
          flags: [`Bank accounts in a private person's name`, `Brand-new, very emotional pages`],
          todo: [`Only donate through the charity's official website`, `Never to bank details you received in a chat`],
        },
      ],
    },
    {
      id: `identita`,
      title: `Digital identity and personal data`,
      intro: `Your data is worth money: it is used to open accounts, take out loans and make other scams more believable.`,
      scams: [
        {
          id: `spid`,
          title: `Digital identity theft and account takeover`,
          how: `With stolen documents and selfies (for example from the fake government text), or with stolen passwords, scammers take over your online accounts: your Government Gateway or GOV.UK login, your email, your bank. Then they change the bank details where your pension, benefits or tax refunds are paid, and open accounts or take out loans in your name.`,
          flags: [`Emails about logins or changes you didn't make`, `A pension, benefit or refund that doesn't arrive`],
          todo: [`Never send photos of your documents or selfies`, `Turn on two-step verification and use the official app to confirm logins`, `If your identity is stolen: report it, contact the organisations involved (HMRC, DWP, your pension provider, your bank) through their official channels and check the bank details they hold for you`],
          vignette: `identity`,
        },
        {
          id: `data-breach`,
          title: `When the scammer already knows your details`,
          how: `After a company suffers a data breach, scammers know your name, address, customer number and recent purchases. They use them to make messages and calls believable, sometimes pretending to be the very company that was hacked, or the police.`,
          flags: [`They know a lot about you and still ask for data or money`],
          todo: [`Knowing your details doesn't make someone trustworthy`, `Change your passwords and use a password manager`, `You can check your email address on haveibeenpwned.com`],
        },
      ],
    },
    {
      id: `aziende`,
      title: `For small businesses and the self-employed`,
      intro: `Tradespeople, shopkeepers and freelancers are perfect targets: they pay invoices every day.`,
      scams: [
        {
          id: `iban-fattura`,
          title: `Changed bank details on an invoice and the fake boss`,
          how: `A supplier's email account is hacked, or scammers use an address that looks almost identical. A message arrives with "new bank details" for payments. A variation: the fake owner or director asks for an urgent, confidential transfer. A single case can cost a business a fortune.`,
          example: { kind: `email`, from: `Accounts <accounts@supplier-ltd.co>`, text: `Please note that, following an audit, our bank account has changed. From today, please make all payments to the new account details below.` },
          flags: [`A change of bank details sent by email`, `Urgency and secrecy around a transfer`],
          todo: [`Check every change of bank details by phone, using a number you already have`, `Turn on two-factor authentication for your email`, `Have two people check large payments`],
          vignette: `invoice`,
        },
      ],
    },
  ],
  victim: {
    title: `Been scammed? What to do right now`,
    intro: `Don't be ashamed: you are the victim, not the one to blame. Acting in the first few hours can make all the difference.`,
    steps: [
      { title: `Block everything`, text: `Freeze your cards and access: call the number on the back of your card or use your banking app (in the UK you can also dial 159).` },
      { title: `Ask for the payment to be recalled`, text: `Call your bank straight away and ask them to stop or recall the transfer: with instant payments, every minute counts.` },
      { title: `Secure your accounts`, text: `Change your passwords (email and bank first), turn on two-factor authentication and log out any devices you don't recognise.` },
      { title: `Collect the evidence`, text: `Screenshots of messages and chats, emails, phone numbers, the recipient's bank details, bank statements, links. Don't delete anything.` },
      { title: `Report it`, text: `Report it to the police: in the UK through Report Fraud, in the US to the FTC and the FBI's IC3, elsewhere to your local police. Keep your reference number: your bank may need it when you ask for a refund.` },
      { title: `Warn others`, text: `If one of your accounts was stolen, warn your contacts: they may receive requests for money in your name.` },
    ],
  },
  contacts: {
    title: `Where to get help`,
    intro: `Official numbers and websites for the UK, the US and the EU. Save them now, before you need them.`,
    items: [
      { name: `Emergency (UK)`, detail: `If you are in danger or someone is at your door to collect money.`, phone: `999` },
      { name: `Emergency (EU)`, detail: `The European emergency number, which also works in the UK.`, phone: `112` },
      { name: `Report Fraud (formerly Action Fraud)`, detail: `The UK police service for reporting fraud and cyber crime (England, Wales and Northern Ireland; in Scotland, report to Police Scotland).`, url: `https://www.reportfraud.police.uk`, phone: `0300 123 2040` },
      { name: `Scam texts: forward to 7726`, detail: `In the UK, forward suspicious texts to 7726 for free: your mobile network can block the sender.` },
      { name: `159: call your bank safely`, detail: `If you get a suspicious call about your money, hang up and dial 159 to reach your bank directly (UK, most major banks).`, url: `https://stopscamsuk.org.uk/campaign/get-help-now/`, phone: `159` },
      { name: `FTC: ReportFraud (USA)`, detail: `Report scams and fraud to the US Federal Trade Commission.`, url: `https://reportfraud.ftc.gov` },
      { name: `FBI IC3 (USA)`, detail: `The FBI's Internet Crime Complaint Center, for online fraud and cyber crime.`, url: `https://www.ic3.gov` },
    ],
    note: `Outside these countries, call your local police and your bank. On social media and apps, always use the platform's "Report" feature too (WhatsApp, Facebook, Instagram, Gumtree, Vinted, Airbnb).`,
  },
  whyReport: {
    title: `Why reporting matters`,
    items: [
      `It allows investigations to start and scammers to be stopped before they strike again.`,
      `It helps spot and block new campaigns.`,
      `It helps when you ask your bank for a refund and limits the damage.`,
      `It makes the digital world safer for everyone.`,
      `Don't be ashamed: the scammer is the one who should be, not you.`,
    ],
  },
  ui: {
    toc: `Contents`,
    print: `Download or print the manual`,
    howItWorks: `How it works`,
    example: `Real example`,
    flags: `Warning signs`,
    todo: `What to do`,
    ai: `With artificial intelligence`,
    checkmailTitle: `Received a suspicious email?`,
    checkmailText: `With KUMANI CheckMail you can check it in seconds: sender, links, attachments and text under the magnifying glass.`,
    checkmailCta: `Open CheckMail`,
    updated: `Updated September 2026 with data from the FBI, FTC, Polizia Postale, CERT-AgID and Consob.`,
    disclaimer: `This manual is for information only and does not replace advice from the police, your bank or a lawyer. Scams change all the time: if in doubt, stop and ask.`,
    copyright: `© KUMANI. You're free to share it to help other people protect themselves.`,
  },
}

export default en
