import type { GuideContent } from '@/lib/antitruffa/types'

// Manual antiestafas KUMANI, español (España).
// Adaptado de la versión italiana: timos locales sustituidos por los
// equivalentes españoles. Cifras: FBI IC3, FTC, Polizia Postale, Consob.
// Contactos verificados en septiembre de 2026.
const es: GuideContent = {
  eyebrow: `Manual KUMANI · Seguridad y Verificación`,
  title: `Cómo protegerte de las estafas online y a domicilio`,
  motto: `No todo lo gratis vale poco. Esto puede valer tus ahorros.`,
  lead: `Las estafas de hoy ya no tienen faltas de ortografía: usan inteligencia artificial, números de teléfono falsificados y webs idénticas a las de verdad. Este manual te enseña, con ejemplos reales, a reconocerlas en pocos segundos y qué hacer si algo ya ha salido mal.`,
  giftNote: `Un regalo solo para los Kumani. Léelo, guárdalo y compártelo con quien quieres: padres y abuelos son el blanco favorito.`,
  stats: [
    { value: `20.900 M$`, label: `en pérdidas denunciadas al FBI (IC3) en 2025, en EE. UU.` },
    { value: `~16.000 M$`, label: `en fraudes denunciados a la FTC de EE. UU. en 2025` },
    { value: `269 M€`, label: `robados con fraudes online en Italia en 2025` },
    { value: `1.829`, label: `webs de falsas inversiones bloqueadas por la Consob italiana` },
  ],
  statsSource: `Fuentes: FBI IC3 2025; FTC Consumer Sentinel 2025; Polizia Postale, informe 2025; Consob, 24/09/2026.`,
  tenSeconds: {
    title: `La prueba de los 10 segundos`,
    intro: `Antes de hacer clic, responder o pagar, para y hazte estas preguntas. Si una sola respuesta es "sí", casi seguro que es una estafa.`,
    items: [
      `¿Me mete prisa o me amenaza (bloqueo de la cuenta, multa, denuncia)?`,
      `¿Me pide contraseñas, códigos, PIN, datos de la tarjeta o fotos de mis documentos?`,
      `¿Me pide pagar con transferencia inmediata, Bizum, recarga, tarjeta regalo o criptomonedas?`,
      `¿Me ofrece dinero fácil, premios o precios demasiado buenos para ser verdad?`,
      `¿Me pide que no se lo cuente a nadie o que no cuelgue el teléfono?`,
      `¿Viene de un número o una dirección que no conozco, aunque diga ser alguien que sí conozco?`,
    ],
  },
  rules: {
    title: `Las 6 reglas de oro`,
    items: [
      { title: `Cuelga y llama tú`, text: `Banco, Policía, Guardia Civil, Seguridad Social: si te contactan, cuelga y llama tú al número oficial que busques por tu cuenta. El número que aparece en pantalla se puede falsificar.` },
      { title: `Nunca des códigos a nadie`, text: `Ningún empleado de verdad te pedirá jamás un código OTP, un PIN, una contraseña o el código de 6 cifras de WhatsApp. Quien lo pide es un estafador, siempre.` },
      { title: `Abre tú la web`, text: `No uses los enlaces que te llegan: abre la app oficial o escribe tú la dirección de la web en el navegador.` },
      { title: `Doble protección en todo`, text: `Activa la verificación en dos pasos en el correo, el banco, las redes sociales y WhatsApp. Usa una contraseña distinta para cada servicio.` },
      { title: `Actualízalo todo`, text: `Un móvil, un ordenador y unas apps actualizados cierran las puertas por las que entran los estafadores. Instala apps solo desde Google Play o App Store.` },
      { title: `Una palabra clave en familia`, text: `Elegid una palabra secreta para usarla si un familiar pide dinero por una urgencia: hoy en día las voces se pueden clonar.` },
    ],
  },
  chapters: [
    {
      id: `messaggi`,
      title: `Correos y SMS`,
      intro: `El canal más usado. Los temas favoritos: envíos, bancos, multas y devoluciones de impuestos.`,
      scams: [
        {
          id: `phishing`,
          title: `Phishing: el correo que imita a un organismo o una empresa`,
          how: `Un correo con logotipo y tono oficiales (Agencia Tributaria, DGT, tu banco, una compañía eléctrica) te invita a pulsar un enlace. La web es una copia perfecta de la original, a menudo hecha con inteligencia artificial, y sirve para robarte contraseñas, tu Cl@ve o los datos de la tarjeta. A veces trae un adjunto que instala un virus.`,
          example: { kind: `email`, from: `Agencia Tributaria <devoluciones@agencia-devolucion.info>`, text: `Estimado contribuyente, tiene pendiente una devolución de 312,40 € a su favor. Para recibirla confirme sus datos en un plazo de 48 horas: [enlace]` },
          flags: [`Prisa y plazos muy cortos`, `La dirección del remitente o de la web no es la oficial`, `Pide datos de la tarjeta, contraseñas o tu acceso Cl@ve`, `Adjuntos .zip, .html o .js`],
          todo: [`No pulses: abre tú la web oficial o la app`, `Márcalo como phishing en tu correo y, si tienes dudas, llama gratis al 017 de INCIBE`, `Si has metido datos: cambia las contraseñas y llama a tu banco`],
          ai: `Los textos ya no tienen faltas y las webs clonadas son idénticas: no te fíes del aspecto, mira la dirección.`,
          vignette: `email`,
        },
        {
          id: `clickfix`,
          title: `El falso "No soy un robot"`,
          how: `Una web te muestra una falsa verificación antirrobots y te pide que pulses unas teclas (por ejemplo Windows+R, luego Ctrl+V e Intro). En realidad estás pegando y ejecutando una orden que instala un virus. Esta técnica se llama ClickFix y se ha extendido muchísimo.`,
          flags: [`Una verificación que te pide pulsar combinaciones de teclas`, `Instrucciones para abrir "Ejecutar" o la terminal`],
          todo: [`Cierra la página: ninguna verificación real te pide pulsar teclas`, `Si ya lo has hecho, desconecta internet y haz revisar el ordenador`],
        },
        {
          id: `smishing-inps`,
          title: `SMS de la "Seguridad Social", el SEPE o Hacienda: la caza de tus documentos`,
          how: `Un SMS en nombre de la Seguridad Social, el SEPE o la Agencia Tributaria te avisa de que debes actualizar tus datos para no perder una prestación o una ayuda. La web falsa pide IBAN, fotos del DNI, de la tarjeta sanitaria y del carné de conducir, nóminas y hasta un selfi con el documento. Con todo eso roban tu identidad, piden un certificado digital o una Cl@ve a tu nombre y revenden tus documentos.`,
          example: { kind: `sms`, from: `SEG-SOCIAL`, text: `Seguridad Social: estimado usuario, para no perder su prestación actualice sus datos hoy mismo: [enlace]` },
          flags: [`Ningún organismo público te pide actualizar datos con un enlace en un SMS`, `Te piden fotos de documentos y un selfi`],
          todo: [`Comprueba solo en las webs oficiales (seg-social.es, sepe.es, agenciatributaria.gob.es) o en sus apps`, `No mandes nunca fotos de documentos ni selfis desde un enlace`, `Si ya lo has hecho: denuncia y revisa tu Cl@ve, tu IBAN y tus cuentas`],
          vignette: `sms`,
        },
        {
          id: `smishing-multe`,
          title: `SMS de multas de tráfico y peajes sin pagar`,
          how: `Te llega un SMS con un importe pequeño "a pagar ya": una multa de la DGT o un peaje de autopista pendiente. La web falsa te pide los datos de la tarjeta. Es una de las campañas más repetidas y llega a miles de personas a la vez.`,
          example: { kind: `sms`, from: `DGT`, text: `DGT: tiene una sanción pendiente de 6,50 € por un peaje no abonado. Evite el recargo pagando aquí: [enlace]` },
          flags: [`Importe pequeño y prisa para "evitar el recargo"`, `Enlace en el mensaje`, `Página pensada solo para el móvil`],
          todo: [`Las multas de verdad se consultan en la sede electrónica de la DGT o en la app miDGT`, `La DGT no pide pagos por SMS`, `Nunca metas los datos de la tarjeta desde un enlace recibido`],
          vignette: `sms`,
        },
        {
          id: `pacchi`,
          title: `Paquetes retenidos y falsos gastos de aduana`,
          how: `Un mensaje en nombre de Correos, SEUR o DHL dice que tu paquete está parado y que hacen falta unos pocos euros de "gastos de envío" o "aranceles". Es uno de los temas más usados, porque casi todo el mundo espera algún paquete.`,
          example: { kind: `sms`, from: `Correos`, text: `Su paquete está retenido en aduana. Abone 1,99 € de tasas para recibirlo: [enlace]` },
          flags: [`No sabes de qué paquete se trata`, `Te piden unos pocos euros con tarjeta`],
          todo: [`Sigue el envío desde la web de la tienda o de la empresa de mensajería`, `Los aranceles de verdad se pagan a la mensajería o por canales oficiales`],
        },
        {
          id: `account-sospeso`,
          title: `"Tu cuenta está suspendida" (Netflix, Amazon, PayPal)`,
          how: `Un correo o un SMS dice que el pago de tu suscripción ha fallado o que van a cerrar tu cuenta. También existe la versión por teléfono: una voz grabada anuncia un pedido caro y te pide que pulses 1 para cancelarlo.`,
          example: { kind: `email`, from: `Netflix <avisos@netflix-soporte.com>`, text: `No hemos podido cobrar tu suscripción. Actualiza tus datos en 24 horas para no perder el acceso: [enlace]` },
          flags: [`Amenaza de bloqueo o cierre`, `Remitente con un dominio "casi" correcto`],
          todo: [`Abre directamente la app o la web y revisa tu cuenta`, `No pulses teclas en llamadas grabadas: cuelga`],
        },
        {
          id: `app-malevole`,
          title: `Apps falsas del banco y "actualizaciones" por SMS`,
          how: `Un SMS te invita a descargar desde un enlace una "actualización de seguridad" del banco o una app de salud. Es una app pirata (en Android suele ser un archivo .apk) que pide permisos de "Accesibilidad": así lee los códigos del banco, puede vaciarte la cuenta y borrar el móvil.`,
          example: { kind: `sms`, from: `Banco`, text: `Estimado cliente, su app está obsoleta. Descargue la actualización de seguridad obligatoria: [enlace]` },
          flags: [`Enlace para descargar una app fuera de las tiendas oficiales`, `Una app que pide permisos de Accesibilidad`],
          todo: [`Instala apps solo desde Google Play o App Store`, `Si has instalado algo: modo avión, llama al banco desde otro teléfono y restablece el dispositivo`],
        },
      ],
    },
    {
      id: `telefono`,
      title: `Llamadas y voces`,
      intro: `La estafa que más dinero cuesta a las familias: una voz amable, un número que parece real y el miedo a perder los ahorros.`,
      scams: [
        {
          id: `finto-operatore`,
          title: `El falso empleado del banco y el falso guardia civil`,
          how: `Primero llega un SMS "de seguridad" sobre una transferencia sospechosa y luego la llamada. En la pantalla aparece el número real de tu banco, de la Policía o de la Guardia Civil (está falsificado: se llama spoofing). El "empleado", muy profesional, te convence para mover el dinero a una "cuenta segura", dictarle los códigos o aprobar una notificación en la app. Hay víctimas que pierden desde unos cientos de euros hasta los ahorros de toda una vida.`,
          example: { kind: `call`, from: `Departamento de fraude (número de tu banco)`, text: `Buenos días, hemos bloqueado una transferencia sospechosa de 2.450 €. Para proteger sus ahorros tenemos que moverlos ahora mismo a una cuenta segura. No cuelgue.` },
          flags: [`"Poner a salvo el dinero" en otra cuenta`, `Prisa y petición de no contárselo a nadie`, `Te piden un código OTP, un PIN o aprobar una notificación`],
          todo: [`Cuelga y llama tú al banco al número que aparece en el reverso de tu tarjeta, pasados unos minutos o desde otro teléfono`, `Ningún banco ni ningún cuerpo policial pide transferencias a cuentas seguras`, `Si ya has pagado: llama enseguida al banco para parar la transferencia, luego al 112 y denuncia`],
          ai: `Aunque se intenta frenar las llamadas falsificadas, los estafadores cambian de número una y otra vez: ver el número correcto en pantalla no garantiza nada.`,
          vignette: `call`,
        },
        {
          id: `voce-clonata`,
          title: `La voz clonada de un familiar`,
          how: `Bastan unos segundos de un vídeo en redes sociales para clonar la voz de un hijo o un nieto. Llega una llamada o un audio desesperado: un accidente, una detención, hace falta un abogado ya. Muchas veces después aparece un "abogado" o un mensajero en tu puerta para recoger dinero en efectivo y joyas.`,
          example: { kind: `call`, from: `Número desconocido`, text: `Abuelo, soy yo... he tenido un accidente, necesito dinero ya para el abogado, ¡no se lo digas a mamá!` },
          flags: [`Emergencia, llanto, urgencia extrema`, `Te pide que no avises a nadie`, `Un número distinto del de siempre`],
          todo: [`Cuelga y llama al número de tu familiar que ya conoces`, `Usa la palabra clave de la familia`, `No entregues nunca dinero ni joyas a quien se presente en tu puerta`],
        },
        {
          id: `supporto-tecnico`,
          title: `El falso servicio técnico`,
          how: `Mientras navegas aparece una ventana a pantalla completa con una sirena: "Tu ordenador está infectado, llama ya a Microsoft". El falso técnico te hace instalar un programa de control remoto y después te cobra o entra en tu banca online.`,
          example: { kind: `popup`, from: `Aviso de seguridad`, text: `¡ATENCIÓN! Su PC está infectado. No apague el ordenador. Llame ahora al soporte técnico: +34 91 ...` },
          flags: [`Alarmas sonoras y números a los que llamar`, `Te piden instalar AnyDesk, TeamViewer o similares`],
          todo: [`Microsoft y Apple nunca muestran números a los que llamar`, `Cierra el navegador, aunque tengas que forzarlo`, `No instales nada porque te lo pida un desconocido`],
        },
        {
          id: `luce-gas`,
          title: `Los falsos comerciales de luz y gas`,
          how: `Alguien que dice llamar "de tu compañía eléctrica", "del regulador" o "de un organismo oficial" te anuncia una tarifa más barata o una devolución y te pide el código CUPS de la factura y tu cuenta bancaria. Con esos datos te cambian de compañía sin que lo hayas pedido o roban tus datos.`,
          example: { kind: `call`, from: `Departamento de energía`, text: `Buenos días, a partir del lunes pasa a la tarifa reducida. ¿Me confirma el código CUPS que aparece en su factura?` },
          flags: [`Te piden el CUPS, el IBAN o una foto de la factura`, `"Organismos oficiales" que llaman para ofrecer tarifas`],
          todo: [`No des nunca códigos de la factura ni tu IBAN por teléfono`, `Si te han cambiado de contrato sin pedirlo, llama a tu compañía de siempre`],
        },
        {
          id: `sim-swap`,
          title: `El robo de la SIM (SIM swapping)`,
          how: `Con documentos falsos o un cómplice, el estafador consigue un duplicado de tu tarjeta SIM. Tu móvil se queda sin línea y él recibe los SMS con los códigos del banco.`,
          flags: [`El móvil pasa de repente a "Sin servicio" o "Solo emergencias"`],
          todo: [`Llama enseguida a tu operadora y a tu banco desde otro teléfono`, `Activa el PIN de la SIM`, `Mejor las notificaciones en la app del banco que los SMS`],
        },
      ],
    },
    {
      id: `domicilio`,
      title: `En la puerta de casa`,
      intro: `No todas las estafas llegan por teléfono o por internet. El Ministerio del Interior y la Policía Nacional alertan con la campaña «Detente antes de abrir»: falsos revisores del gas y del agua se presentan sin aviso, sobre todo en casas de personas mayores, para cobrar revisiones que no existen o para robar.`,
      pattern: {
        title: `El esquema siempre es el mismo`,
        text: `Agua, gas, luz, ayuntamiento, policía: cambia el uniforme, no el truco. Alguien a quien no esperabas, una acreditación enseñada deprisa, un motivo urgente (una fuga, una avería, una revisión, un reembolso) y una petición: entrar en casa o que le des dinero y joyas. A menudo un cómplice entra o rebusca mientras estás distraído.`,
      },
      scams: [
        {
          id: `finto-letturista`,
          title: `El falso lector de contadores`,
          how: `Llama a la puerta diciendo que tiene que leer el contador del agua, del gas o de la luz, o revisar los grifos por un problema en la zona. Una vez dentro te hace abrir el agua en el baño o la cocina y, mientras estás ocupado, él o un cómplice busca dinero y joyas. Otras veces pide directamente dinero en efectivo por una «regularización» o un «reembolso».`,
          example: {
            kind: `notice`,
            from: `Aviso del ayuntamiento, a petición de la Guardia Civil`,
            text: `Se ruega a los vecinos la máxima atención ante personas que se presenten en los domicilios haciéndose pasar por encargados de la lectura de los contadores del agua. No dejen entrar a nadie sin identificarlo y, ante cualquier duda, llamen al 112.`,
          },
          flags: [`La visita no se ha avisado con antelación en el portal o en la factura`, `Insiste en entrar o en que abras los grifos`, `Pide efectivo por regularizaciones, reembolsos o fianzas`, `Enseña la acreditación deprisa o no lleva nada que lo identifique`],
          todo: [`No abras a quien no esperas: habla desde la puerta cerrada o el telefonillo`, `Llama al número de tu factura, no al que te da la persona, y pregunta si de verdad hay una visita`, `Las revisiones reales se avisan con antelación y nunca se pagan en efectivo en la puerta`, `Ante la duda llama al 112, al 091 (Policía Nacional) o al 062 (Guardia Civil) y avisa a vecinos y familiares mayores`],
          vignette: `door`,
        },
        {
          id: `finta-fuga-gas`,
          title: `La falsa fuga de gas y el falso revisor de la caldera`,
          how: `Se presentan como técnicos del gas, del agua o del ayuntamiento: «Hay una fuga en la zona, tenemos que revisar ahora mismo». Te asustan y te piden que juntes dinero y joyas «para protegerlos», o te hacen salir de casa. Otras veces exigen pagar una «revisión obligatoria» que no existe o te hacen firmar un contrato.`,
          example: {
            kind: `door`,
            from: `En la puerta`,
            text: `Buenos días, venimos del gas. Hay una fuga en el edificio, es peligroso, tenemos que entrar ya. Guarde el dinero y las joyas en una bolsa para que no se estropeen.`,
          },
          flags: [`Alarma repentina y miedo: «es peligroso, deprisa»`, `Te piden mover o juntar dinero y joyas`, `Hablan de revisiones obligatorias que hay que pagar ya, en efectivo`],
          todo: [`Ningún técnico de verdad te pide tocar tu dinero o tus joyas`, `Si de verdad huele a gas, sal, no toques interruptores y llama al teléfono de urgencias de tu distribuidora`, `Cierra la puerta y llama al 112`],
        },
        {
          id: `finto-carabiniere-ritiro`,
          title: `El falso policía o abogado que pasa a recoger dinero y joyas`,
          how: `Primero llega una llamada: un hijo o un nieto ha tenido un accidente o está en apuros y hace falta una fianza ya. Poco después, un «enviado» que se presenta como policía, abogado o mensajero llama a la puerta para recoger dinero o joyas. Te mantienen al teléfono para que no puedas llamar a nadie.`,
          example: {
            kind: `call`,
            from: `Número desconocido`,
            text: `Señora, le llamo de la Policía. Su nieto ha provocado un accidente y necesita una fianza hoy mismo para no ir a prisión. Un compañero pasará a recogerla por su casa en media hora.`,
          },
          flags: [`La policía y los abogados nunca recogen dinero ni joyas en casa`, `Te piden que no cuelgues y que no se lo cuentes a nadie`, `Prisa y miedo por un familiar`],
          todo: [`Cuelga, llama tú a tu familiar y después al 091 o al 062`, `No entregues nada a nadie, aunque enseñe una placa`, `Usa la palabra clave de la familia`],
          vignette: `call`,
        },
        {
          id: `finto-funzionario`,
          title: `El falso empleado del ayuntamiento, de la Seguridad Social, de Correos o del banco`,
          how: `Se presenta como empleado del ayuntamiento, de la Seguridad Social, de Correos o del banco: tiene que revisar tu pensión, cambiar billetes «falsos», comprobar documentos o entregarte un reembolso. El objetivo es entrar, ver dónde guardas el dinero o que le des efectivo, tarjetas y PIN.`,
          flags: [`Ayuntamientos y bancos no envían empleados a casa sin cita`, `Pide ver efectivo, tarjetas, PIN o libretas`, `Habla de billetes falsos o de reembolsos que cobrar ya`],
          todo: [`Pide nombre y departamento y llama tú al número oficial`, `No enseñes nunca dónde guardas dinero y joyas`, `Si hace falta, pide tú cita en la oficina, con un familiar`],
        },
      ],
      poster: {
        title: `Para imprimir y pegar junto a la puerta`,
        lines: [`No abro a quien no espero.`, `Pido la acreditación y llamo yo al número de la factura o del organismo.`, `Nadie recoge dinero ni joyas en casa: ni policías, ni abogados, ni técnicos.`, `Ante la duda, llamo al 112.`],
        note: `Imprímela y pégala por dentro de la puerta de tus padres y abuelos. Y habladlo juntos: quien está avisado se defiende mejor.`,
      },
    },
    {
      id: `chat`,
      title: `WhatsApp, redes sociales y chats`,
      intro: `Aquí la estafa entra por la confianza: un familiar, un amigo, alguien que parece interesarse por ti.`,
      scams: [
        {
          id: `finto-figlio`,
          title: `"Hola mamá, he cambiado de número"`,
          how: `Un número desconocido te escribe haciéndose pasar por tu hijo o tu hija: se le ha roto el móvil y este es su número nuevo. Tras unos pocos mensajes llega la petición: una transferencia urgente para pagar una factura, "mañana te lo devuelvo". En España es una de las estafas más comunes.`,
          example: { kind: `chat`, from: `+34 6xx xxx xxx`, text: `Hola mamá, se me ha caído el móvil al agua, este es mi número nuevo, guárdalo. Tengo que pagar una factura urgente, ¿me haces una transferencia? Mañana te lo devuelvo todo ❤️` },
          flags: [`Un número desconocido que dice ser de la familia`, `No usa tu nombre ni los apodos de siempre`, `Evita hacer una llamada de voz`],
          todo: [`Llama al número antiguo de tu familiar`, `Hazle una pregunta que solo él o ella sepa`, `Usa la palabra clave de la familia`],
          vignette: `whatsapp`,
        },
        {
          id: `codice-6-cifre`,
          title: `"Te he mandado un código por error": el robo de la cuenta`,
          how: `Un amigo (en realidad su cuenta ya ha sido robada) te pide que le reenvíes un código de 6 cifras "que te ha llegado por error", o que votes a su sobrina en un concurso. Es el código de verificación de tu WhatsApp: si lo das, pierdes la cuenta y el estafador pide dinero a todos tus contactos.`,
          example: { kind: `chat`, from: `Marcos`, text: `¡Hola! ¿Te ha llegado un código de 6 cifras? Lo he mandado a tu número sin querer, ¿me lo reenvías porfa?` },
          flags: [`Te piden un código que te ha llegado por SMS`, `Enlaces para "votar" o "verificar"`],
          todo: [`No reenvíes nunca códigos de verificación, a nadie`, `Activa la verificación en dos pasos de WhatsApp (PIN y correo)`, `Si la has perdido: reinstala WhatsApp, verifica tu número y avisa a tus contactos`],
        },
        {
          id: `romance`,
          title: `La estafa del amor`,
          how: `Un perfil encantador (militar en misión, médico en el extranjero, empresario) te corteja durante semanas con atenciones y promesas. Luego llegan las peticiones: dinero para la aduana, una emergencia, un billete de avión. A menudo acaba también en una estafa de inversión en criptomonedas.`,
          flags: [`Nunca se deja ver en persona`, `Historias lacrimógenas y peticiones de dinero`, `Te invita a invertir juntos`],
          todo: [`Busca sus fotos con la búsqueda inversa de imágenes`, `No mandes dinero a quien nunca has visto en persona`, `Háblalo con alguien de confianza`],
          ai: `Las fotos, los mensajes y hasta las videollamadas se pueden generar con inteligencia artificial.`,
          vignette: `romance`,
        },
        {
          id: `sextortion`,
          title: `El chantaje sexual y el falso hacker`,
          how: `Existe la versión masiva: un correo dice que te han grabado con la webcam y pide dinero en bitcoins, a veces citando una contraseña antigua tuya robada para parecer creíble. Normalmente no existe ningún vídeo. Y existe la versión real: tras intercambiar imágenes íntimas con un perfil falso llega el chantaje.`,
          example: { kind: `email`, from: `Desconocido`, text: `He tomado el control de tu dispositivo y te he grabado con la webcam. Paga 530 € en bitcoins en 48 horas o envío el vídeo a todos tus contactos.` },
          flags: [`Amenazas, plazos y pago en criptomonedas`, `Una contraseña antigua tuya en el texto`],
          todo: [`No pagues y no respondas`, `Guarda las pruebas y denuncia ante la Policía Nacional o la Guardia Civil`, `Cambia la contraseña que mencionan`],
          ai: `Hoy se pueden crear imágenes íntimas falsas a partir de fotos normales: no es culpa tuya, denuncia.`,
          vignette: `blackmail`,
        },
        {
          id: `lavoro`,
          title: `Trabajos fáciles desde casa y "me gusta" pagados`,
          how: `Un mensaje por WhatsApp o Telegram ofrece entre 50 y 300 € al día por dar "me gusta" o escribir reseñas. Los primeros pagos llegan de verdad, para ganarse tu confianza. Después entras en un grupo donde tienes que poner dinero para "desbloquear tareas premium", y ese dinero ya no vuelve.`,
          example: { kind: `chat`, from: `Recruiter RR. HH.`, text: `¡Hola! Buscamos colaboradores a tiempo parcial: de 50 a 300 € al día desde casa dando likes en YouTube. ¿Te interesa?` },
          flags: [`Ofertas de trabajo que no has pedido`, `Para ganar primero tienes que pagar`, `Te piden recibir dinero de otros y reenviarlo`],
          todo: [`Un trabajo de verdad nunca te pide dinero`, `No prestes tu cuenta: te pueden acusar de blanqueo de capitales (serías una "mula")`],
          vignette: `job`,
        },
      ],
    },
    {
      id: `acquisti`,
      title: `Compras, anuncios y vacaciones`,
      intro: `Precios irresistibles, vendedores amabilísimos y prisa por cerrar el trato: el guion siempre es el mismo.`,
      scams: [
        {
          id: `negozi-falsi`,
          title: `Tiendas online falsas anunciadas en redes sociales`,
          how: `Un anuncio patrocinado dice "liquidamos el almacén, -80%" en zapatillas, bolsos o electrónica de marca. La web, muchas veces creada con inteligencia artificial, parece real, pero el pedido no llega o es una falsificación. También circulan muchas entradas falsas para conciertos.`,
          example: { kind: `ad`, from: `Patrocinado`, text: `¡CIERRE DE TIENDA! Todo al -80% solo hoy. Últimas unidades disponibles 🔥` },
          flags: [`Descuentos irreales y cuenta atrás`, `Sin NIF, dirección ni datos de contacto`, `Solo se paga por transferencia, Bizum o criptomonedas`],
          todo: [`Paga con métodos que te protegen (tarjeta de crédito, PayPal "bienes y servicios")`, `Busca opiniones en webs externas`, `Desconfía de las webs creadas hace pocos días`],
          vignette: `shop`,
        },
        {
          id: `marketplace`,
          title: `El falso comprador en Wallapop, Vinted y Marketplace`,
          how: `Vendes algo y un "comprador" te escribe que ya ha pagado con el servicio de envío: solo tienes que pulsar un enlace para "recibir el dinero". La página te pide los datos de tu tarjeta. O es el vendedor quien pide un adelanto por transferencia o Bizum y luego desaparece.`,
          example: { kind: `chat`, from: `Comprador`, text: `Ya he pagado con el servicio de mensajería, pulsa aquí para confirmar y recibir el pago en tu tarjeta: [enlace]` },
          flags: [`Te invitan a salir del chat de la plataforma`, `Para "recibir" dinero te piden los datos de la tarjeta`, `Solicitudes de dinero por Bizum de desconocidos que dicen que es un pago`],
          todo: [`Quédate siempre en el chat y en el sistema de pago de la plataforma`, `Para recibir dinero nunca hacen falta los datos de tu tarjeta`, `Denuncia al usuario desde la app`],
        },
        {
          id: `case-vacanza`,
          title: `Pisos de vacaciones y alquileres que no existen`,
          how: `Anuncios con fotos preciosas (robadas o generadas) y precios bajos. El "propietario" vive en el extranjero y pide una señal del 50% o más por transferencia. Al llegar, el piso no existe o es de otra persona. El mismo esquema se usa con los alquileres para estudiantes.`,
          flags: [`Señal alta antes de ver el piso`, `Pago fuera de la plataforma`, `Un propietario al que nunca puedes ver en persona`],
          todo: [`Paga solo dentro de la plataforma de reservas`, `Comprueba la dirección en un mapa y las fotos con la búsqueda inversa`, `Una señal razonable ronda el 20%`],
        },
        {
          id: `qr`,
          title: `Los códigos QR trucados (quishing)`,
          how: `En los parquímetros pegan pegatinas con un QR de "paga el aparcamiento" que lleva a una web falsa. El mismo truco aparece en falsas multas bajo el limpiaparabrisas, avisos de paquetes y correos que te piden "escanear para verificar la cuenta".`,
          flags: [`Pegatinas encima del QR original`, `Tras escanear, una dirección rara`],
          todo: [`Paga el aparcamiento desde la app oficial de tu ayuntamiento o del operador`, `Mira siempre la dirección que se abre tras escanear`],
          vignette: `qr`,
        },
        {
          id: `premi`,
          title: `Premios, sorteos y herencias`,
          how: `"¡Enhorabuena, has ganado un iPhone!": solo tienes que pagar 2 € de envío. En realidad activas una suscripción oculta en tu tarjeta. Variantes: herencias millonarias de notarios extranjeros, premios en nombre de supermercados.`,
          example: { kind: `sms`, from: `Premio`, text: `¡Enhorabuena! Has sido seleccionado para ganar un iPhone 17. Paga solo 2 € de envío: [enlace]` },
          flags: [`Premios de sorteos en los que no has participado`, `Pequeños gastos a pagar para recibir el premio`],
          todo: [`Si no has participado, no has ganado`, `No pagues nunca gastos para recibir un premio`],
        },
      ],
    },
    {
      id: `soldi`,
      title: `Inversiones y dinero`,
      intro: `Las pérdidas más altas: a menudo los ahorros de toda una vida, perdidos en pocos meses.`,
      scams: [
        {
          id: `investimenti`,
          title: `Inversiones con famosos falsos (deepfake) y falsos brókers`,
          how: `Un anuncio o una falsa noticia de periódico muestra a un político, a un famoso de la tele o a un empresario conocido revelando "el secreto para ganar dinero". Dejas tu número, te llama un "asesor" que te hace instalar una app de control remoto y te enseña ganancias falsas. Cuando intentas sacar el dinero, piden "impuestos" y "comisiones de desbloqueo". Variante: una relación por chat construida durante semanas y luego la invitación a invertir en criptomonedas.`,
          example: { kind: `ad`, from: `Noticias de hoy`, text: `El secreto que los bancos no quieren que sepas: con solo 250 € ganas 1.500 € a la semana. Mira la entrevista.` },
          flags: [`Rentabilidades garantizadas o altísimas`, `Famosos que "recomiendan" inversiones`, `Te piden instalar AnyDesk o apps parecidas`, `Para sacar tu dinero tienes que pagar`],
          todo: [`Comprueba la entidad en los registros de la CNMV y del Banco de España`, `Consulta las advertencias de la CNMV sobre entidades no autorizadas ("chiringuitos financieros")`, `No instales nunca apps de acceso remoto`],
          ai: `Los estafadores usan vídeos deepfake de políticos y famosos muy conocidos: si un vídeo promete dinero fácil, es falso.`,
          vignette: `invest`,
        },
        {
          id: `recupero-fondi`,
          title: `Quien promete recuperar el dinero perdido`,
          how: `Después de una estafa te contacta un falso abogado, una empresa de recuperación o incluso una falsa "Policía" o "Europol": han encontrado tu dinero, pero para liberarlo hay que pagar gastos legales. Es una segunda estafa a la misma víctima.`,
          flags: [`Te contactan ellos, sabiendo que te han estafado`, `Piden un pago por adelantado`],
          todo: [`Ningún organismo público te pide dinero para devolverte lo robado`, `Habla solo con la Policía, la Guardia Civil y con abogados que elijas tú`],
        },
        {
          id: `beneficenza`,
          title: `Falsas recogidas de fondos`,
          how: `Tras inundaciones, terremotos o guerras aparecen páginas que imitan a ONG reales, cuentas bancarias de particulares y campañas con fotos conmovedoras, a veces generadas con inteligencia artificial.`,
          flags: [`Cuentas bancarias a nombre de particulares`, `Páginas recién creadas y muy emotivas`],
          todo: [`Dona solo desde la web oficial de la organización`, `Nunca a un IBAN que te llega por chat`],
        },
      ],
    },
    {
      id: `identita`,
      title: `Identidad digital y datos personales`,
      intro: `Tus datos valen dinero: sirven para abrir cuentas, pedir préstamos y hacer más creíbles otras estafas.`,
      scams: [
        {
          id: `spid`,
          title: `El robo de tu Cl@ve o de tu certificado digital`,
          how: `Con documentos y selfis robados (por ejemplo con el falso SMS de la Seguridad Social), los estafadores se dan de alta en Cl@ve o piden un certificado digital a tu nombre, o te roban las credenciales que ya tienes. Después cambian el IBAN de tu pensión, tus prestaciones o tu devolución de la renta, y abren cuentas o piden préstamos.`,
          flags: [`Avisos de altas o accesos a Cl@ve que no has hecho tú`, `Una devolución, una prestación o la pensión que no llegan`],
          todo: [`No mandes nunca fotos de documentos ni selfis`, `Guarda tu certificado digital y tus claves solo en tus dispositivos`, `Si te los roban: denuncia, pide revocar el certificado o la Cl@ve y revisa tu IBAN en la Seguridad Social y en la Agencia Tributaria`],
          vignette: `identity`,
        },
        {
          id: `data-breach`,
          title: `Cuando el estafador ya conoce tus datos`,
          how: `Tras un robo de datos a una empresa, los estafadores conocen tu nombre, dirección, número de cliente y últimas compras. Los usan para que sus mensajes y llamadas resulten creíbles, a veces haciéndose pasar por la propia empresa afectada o por la "Policía".`,
          flags: [`Saben muchas cosas de ti y aun así te piden datos o dinero`],
          todo: [`Que alguien conozca tus datos no lo hace de fiar`, `Cambia las contraseñas y usa un gestor de contraseñas`, `Puedes comprobar si tu correo aparece en algún robo de datos en haveibeenpwned.com`],
        },
      ],
    },
    {
      id: `aziende`,
      title: `Para autónomos y empresas`,
      intro: `Autónomos, comercios y profesionales son el blanco perfecto: pagan facturas todos los días.`,
      scams: [
        {
          id: `iban-fattura`,
          title: `El IBAN cambiado en la factura y el falso jefe`,
          how: `Alguien entra en el correo de un proveedor, o los estafadores usan una dirección casi idéntica. Llega un aviso con la "nueva cuenta bancaria" para los pagos. Variante: el falso dueño de la empresa pide una transferencia urgente y confidencial (el "fraude del CEO"). Una sola transferencia puede costar cientos de miles de euros.`,
          example: { kind: `email`, from: `Administración <administracion@proveedor-sl.co>`, text: `Les informamos de que, por motivos de auditoría, nuestra cuenta ha cambiado. A partir de hoy les rogamos que realicen los pagos al nuevo IBAN indicado.` },
          flags: [`Cambio de IBAN comunicado por correo`, `Urgencia y secretismo en una transferencia`],
          todo: [`Confirma cualquier cambio de IBAN por teléfono, con el número que ya tenías guardado`, `Activa la verificación en dos pasos en el correo`, `Que dos personas revisen las transferencias importantes`],
          vignette: `invoice`,
        },
      ],
    },
  ],
  victim: {
    title: `¿Te han estafado? Qué hacer ya`,
    intro: `No te avergüences: eres la víctima, no el culpable. Actuar en las primeras horas puede marcar la diferencia.`,
    steps: [
      { title: `Bloquéalo todo`, text: `Bloquea tarjetas y accesos desde la app de tu banco o llamando al número que aparece en el reverso de tu tarjeta.` },
      { title: `Pide que paren la transferencia`, text: `Llama enseguida al banco y pide que bloqueen o recuperen la transferencia: con las transferencias inmediatas cada minuto cuenta.` },
      { title: `Protege tus cuentas`, text: `Cambia las contraseñas (primero el correo y el banco), activa la verificación en dos pasos y cierra la sesión en los dispositivos que no reconozcas.` },
      { title: `Reúne las pruebas`, text: `Capturas de pantalla de mensajes y chats, correos, números de teléfono, el IBAN de destino, extractos bancarios, enlaces. No borres nada.` },
      { title: `Denuncia`, text: `Pon una denuncia en una comisaría de la Policía Nacional o en un puesto de la Guardia Civil, o por internet. La denuncia también sirve para pedir al banco que te devuelva el dinero. Si necesitas orientación, llama gratis al 017.` },
      { title: `Avisa a los demás`, text: `Si te han robado una cuenta, avisa a tus contactos: podrían recibir peticiones de dinero en tu nombre.` },
    ],
  },
  contacts: {
    title: `A quién acudir en España`,
    intro: `Los números y webs oficiales. Guárdalos ahora, antes de necesitarlos.`,
    items: [
      { name: `Emergencias`, detail: `Si estás en peligro o alguien está en tu puerta para recoger dinero.`, phone: `112` },
      { name: `Policía Nacional`, detail: `Para avisar a la Policía Nacional.`, phone: `091` },
      { name: `Guardia Civil`, detail: `Para avisar a la Guardia Civil.`, phone: `062` },
      { name: `INCIBE, Tu Ayuda en Ciberseguridad`, detail: `Línea gratuita y confidencial de ayuda en ciberseguridad: técnicos, abogados y psicólogos te orientan.`, phone: `017`, url: `https://www.incibe.es/linea-de-ayuda-en-ciberseguridad` },
      { name: `Policía Nacional, denuncia por internet`, detail: `Oficina virtual de denuncias. Después tienes que firmar la denuncia en comisaría en un plazo de 72 horas.`, url: `https://denuncias.policia.es/OVD/` },
      { name: `Guardia Civil, denuncia electrónica`, detail: `Denuncia por internet, también de estafas y cargos no autorizados. Necesitas certificado digital o Cl@ve.`, url: `https://web.guardiacivil.es/es/tramites/denuncias/denuncia-electronica/` },
    ],
    note: `¿Vives en Latinoamérica? Acude a la policía de tu país y llama enseguida a tu banco. Redes sociales y apps: usa siempre la función "Denunciar" de la plataforma (WhatsApp, Facebook, Instagram, Wallapop, Vinted, Airbnb).`,
  },
  whyReport: {
    title: `Por qué es importante denunciar`,
    items: [
      `Permite abrir una investigación y parar a los estafadores antes de que ataquen a otros.`,
      `Ayuda a reconocer y bloquear las nuevas campañas.`,
      `Sirve para pedir al banco que te devuelva el dinero y limitar los daños.`,
      `Hace el mundo digital más seguro para todos.`,
      `No sientas vergüenza: quien debe avergonzarse es el estafador, no tú.`,
    ],
  },
  ui: {
    toc: `Índice`,
    print: `Descarga o imprime el manual`,
    howItWorks: `Cómo funciona`,
    example: `Ejemplo real`,
    flags: `Señales de alarma`,
    todo: `Qué hacer`,
    ai: `Con inteligencia artificial`,
    checkmailTitle: `¿Te ha llegado un correo sospechoso?`,
    checkmailText: `Con KUMANI CheckMail lo revisas en pocos segundos: remitente, enlaces, adjuntos y texto, bajo la lupa.`,
    checkmailCta: `Abrir CheckMail`,
    updated: `Actualizado en septiembre de 2026 con datos del FBI, la FTC, la Polizia Postale, CERT-AgID, la Consob e INCIBE.`,
    disclaimer: `Este manual es solo informativo y no sustituye el consejo de la policía, de tu banco o de un abogado. Las estafas cambian constantemente: ante la duda, para y pregunta.`,
    copyright: `© KUMANI. Puedes compartirlo libremente para ayudar a otras personas a protegerse.`,
  },
}

export default es
