import type { GuideContent } from '@/lib/antitruffa/types'

// Manuel anti-arnaque KUMANI, version française (France, Belgique, Suisse).
// Adaptée de la version italienne : les arnaques propres à l'Italie sont
// remplacées par leurs équivalents français. Mis à jour en septembre 2026.
const fr: GuideContent = {
  eyebrow: `Manuel KUMANI · Sécurité et Vérification`,
  title: `Comment se protéger des arnaques en ligne`,
  motto: `Tout ce qui est gratuit ne vaut pas rien. Celui-ci peut valoir vos économies.`,
  lead: `Les arnaques d'aujourd'hui n'ont plus de fautes d'orthographe : elles utilisent l'intelligence artificielle, des numéros de téléphone falsifiés et des sites identiques aux vrais. Ce manuel vous montre, avec des exemples réels, comment les reconnaître en quelques secondes et quoi faire si quelque chose a déjà mal tourné.`,
  giftNote: `Un cadeau réservé aux Kumani. Lisez-le, gardez-le et partagez-le avec ceux que vous aimez : les parents et les grands-parents sont les cibles préférées.`,
  stats: [
    { value: `20,9 Md$`, label: `de pertes signalées au FBI (IC3) en 2025, aux États-Unis` },
    { value: `~16 Md$`, label: `de fraudes signalées à la FTC américaine en 2025` },
    { value: `269 M€`, label: `volés en ligne en Italie en 2025 (Polizia Postale)` },
    { value: `1 829`, label: `faux sites d'investissement bloqués par la Consob italienne` },
  ],
  statsSource: `Sources : FBI IC3 2025 ; FTC Consumer Sentinel 2025 ; Polizia Postale, rapport 2025 ; Consob, 24/09/2026.`,
  tenSeconds: {
    title: `Le test des 10 secondes`,
    intro: `Avant de cliquer, de répondre ou de payer, arrêtez-vous et posez-vous ces questions. Si une seule réponse est « oui », c'est presque sûrement une arnaque.`,
    items: [
      `Est-ce qu'on me presse ou qu'on me menace (compte bloqué, amende, plainte) ?`,
      `Est-ce qu'on me demande un mot de passe, un code, un PIN, les données de ma carte ou la photo de mes papiers ?`,
      `Est-ce qu'on me demande de payer par virement instantané, recharge, carte cadeau ou cryptomonnaie ?`,
      `Est-ce qu'on me promet des gains faciles, un cadeau ou un prix trop beau pour être vrai ?`,
      `Est-ce qu'on me demande de n'en parler à personne ou de rester en ligne ?`,
      `Est-ce que ça vient d'un numéro ou d'une adresse que je ne connais pas, même si la personne dit être quelqu'un que je connais ?`,
    ],
  },
  rules: {
    title: `Les 6 règles d'or`,
    items: [
      { title: `Raccrochez et rappelez vous-même`, text: `Banque, police, gendarmerie, Assurance maladie : s'ils vous contactent, raccrochez et rappelez le numéro officiel que vous trouvez vous-même. Le numéro qui s'affiche sur l'écran peut être falsifié.` },
      { title: `Jamais de code à personne`, text: `Aucun vrai conseiller ne vous demandera jamais un code reçu par SMS, votre PIN, votre mot de passe ou le code à 6 chiffres de WhatsApp. Celui qui le demande est un escroc, toujours.` },
      { title: `Ouvrez le site vous-même`, text: `N'utilisez pas les liens reçus : ouvrez l'application officielle ou tapez vous-même l'adresse du site dans le navigateur.` },
      { title: `Double protection partout`, text: `Activez la double authentification sur votre messagerie, votre banque, vos réseaux sociaux et WhatsApp (vérification en deux étapes). Utilisez un mot de passe différent pour chaque service.` },
      { title: `Mettez tout à jour`, text: `Un téléphone, un ordinateur et des applications à jour ferment les portes que les escrocs utilisent pour entrer. N'installez des applications que depuis Google Play ou l'App Store.` },
      { title: `Un mot de passe en famille`, text: `Choisissez ensemble un mot secret à utiliser si un proche demande de l'argent pour une urgence : aujourd'hui, les voix peuvent être clonées.` },
    ],
  },
  chapters: [
    {
      id: `messaggi`,
      title: `E-mails et SMS`,
      intro: `Le canal le plus utilisé. Les thèmes préférés des escrocs : colis, banques, amendes et remboursements d'impôts.`,
      scams: [
        {
          id: `phishing`,
          title: `Le phishing : l'e-mail qui imite un organisme ou une entreprise`,
          how: `Un e-mail avec le logo et le ton officiels (impots.gouv, Assurance maladie, votre banque, votre fournisseur d'accès) vous invite à cliquer sur un lien. Le site est une copie parfaite de l'original, souvent créée avec l'intelligence artificielle, et sert à voler vos identifiants, votre accès FranceConnect ou les données de votre carte. Parfois, une pièce jointe installe un virus.`,
          example: { kind: `email`, from: `Finances publiques <remboursement@impots-remboursement.info>`, text: `Madame, Monsieur, après un dernier calcul de vos impôts, vous avez droit à un remboursement de 312,40 €. Pour le recevoir, confirmez vos coordonnées sous 48 heures : [lien]` },
          flags: [`Urgence et délais très courts`, `L'adresse de l'expéditeur ou du site n'est pas l'adresse officielle`, `On vous demande les données de votre carte, un mot de passe ou votre accès FranceConnect`, `Pièces jointes .zip, .html ou .js`],
          todo: [`Ne cliquez pas : ouvrez vous-même le site officiel ou l'application`, `Signalez l'e-mail avec le bouton « Signaler » de votre messagerie, puis supprimez-le`, `Si vous avez saisi des informations : changez vos mots de passe et appelez votre banque`],
          ai: `Les textes n'ont plus de fautes et les faux sites sont identiques aux vrais : ne vous fiez pas à l'apparence, vérifiez l'adresse.`,
          vignette: `email`,
        },
        {
          id: `clickfix`,
          title: `Le faux « Je ne suis pas un robot »`,
          how: `Un site affiche une fausse vérification anti-robot et vous demande d'appuyer sur certaines touches (par exemple Windows+R, puis Ctrl+V et Entrée). En réalité, vous collez et lancez une commande qui installe un virus. Cette technique, appelée ClickFix, s'est beaucoup répandue.`,
          flags: [`Une vérification qui vous demande d'appuyer sur des combinaisons de touches`, `Des instructions pour ouvrir « Exécuter » ou le terminal`],
          todo: [`Fermez la page : aucune vraie vérification ne demande d'appuyer sur des touches`, `Si c'est déjà fait, coupez Internet et faites vérifier l'ordinateur`],
        },
        {
          id: `smishing-inps`,
          title: `SMS « Assurance maladie », « CAF » ou « CPF » : la chasse à vos papiers`,
          how: `Un SMS au nom de l'Assurance maladie (ameli), de la CAF ou de votre compte formation (CPF) vous prévient que vous devez mettre à jour vos informations : carte Vitale à renouveler, aide à ne pas perdre, droits à la formation qui vont expirer. Le faux site demande votre RIB, la photo de votre carte d'identité, de votre carte Vitale, de votre permis, vos fiches de paie et même un selfie avec votre pièce d'identité. Avec tout cela, les escrocs volent votre identité, ouvrent des comptes à votre nom et revendent vos documents.`,
          example: { kind: `sms`, from: `ameli`, text: `Assurance maladie : votre carte Vitale arrive à expiration. Pour éviter l'interruption de vos remboursements, faites votre demande aujourd'hui : [lien]` },
          flags: [`L'Assurance maladie, la CAF et le CPF ne demandent jamais de mettre à jour vos informations via un lien dans un SMS`, `Demande de photos de vos papiers et d'un selfie`],
          todo: [`Vérifiez uniquement dans votre espace officiel (ameli.fr, caf.fr, moncompteformation.gouv.fr) ou dans l'application officielle`, `N'envoyez jamais de photos de vos papiers ou de selfie via un lien`, `Si c'est déjà fait : portez plainte et surveillez vos comptes, votre RIB et vos accès en ligne`],
          vignette: `sms`,
        },
        {
          id: `smishing-multe`,
          title: `SMS d'amendes, de péages ou de vignette Crit'Air impayés`,
          how: `Vous recevez un SMS avec une petite somme « à régler tout de suite » : une amende au nom de l'ANTAI, un péage d'autoroute en flux libre non payé, une vignette Crit'Air à acheter. Le faux site demande les données de votre carte. Ces campagnes sont très nombreuses et reviennent sans cesse.`,
          example: { kind: `sms`, from: `ANTAI`, text: `Avis de contravention : un montant de 35 € reste impayé. Réglez avant ce soir pour éviter la majoration : [lien]` },
          flags: [`Petite somme et urgence pour « éviter la majoration »`, `Un lien dans le message`, `Une page faite uniquement pour smartphone`],
          todo: [`Les vraies amendes se vérifient sur antai.gouv.fr, en tapant vous-même l'adresse`, `La vraie vignette Crit'Air s'achète uniquement sur le site officiel du gouvernement, jamais par SMS`, `Ne saisissez jamais les données de votre carte depuis un lien reçu`, `Signalez le SMS en le transférant gratuitement au 33700`],
          vignette: `sms`,
        },
        {
          id: `pacchi`,
          title: `Colis en attente et faux frais de douane`,
          how: `Un message au nom de La Poste, Colissimo, Chronopost ou DHL vous dit que votre colis est bloqué et qu'il faut payer quelques euros de « frais » ou de « taxes ». C'est l'un des thèmes les plus utilisés, parce que presque tout le monde attend un colis.`,
          example: { kind: `sms`, from: `Colissimo`, text: `Votre colis est retenu en douane. Réglez 1,99 € de frais pour la livraison : [lien]` },
          flags: [`Vous ne savez pas de quel colis il s'agit`, `On vous demande quelques euros par carte`],
          todo: [`Suivez l'envoi depuis le site du vendeur ou du transporteur`, `Les vrais frais de douane se paient au transporteur ou par ses canaux officiels`, `Transférez le SMS au 33700`],
        },
        {
          id: `account-sospeso`,
          title: `« Votre compte est suspendu » (Netflix, Amazon, PayPal)`,
          how: `Un e-mail ou un SMS vous dit que le paiement de votre abonnement a échoué ou que votre compte va être fermé. Il existe aussi une version par téléphone : une voix enregistrée annonce une commande coûteuse et vous demande d'appuyer sur 1 pour l'annuler.`,
          example: { kind: `email`, from: `Netflix <avis@netflix-assistance.com>`, text: `Le paiement de votre abonnement a échoué. Mettez à jour vos informations sous 24 heures pour ne pas perdre l'accès : [lien]` },
          flags: [`Menace de blocage ou de fermeture`, `Un expéditeur avec un nom de domaine « presque » correct`],
          todo: [`Ouvrez directement l'application ou le site et vérifiez votre compte`, `N'appuyez sur aucune touche pendant un appel enregistré : raccrochez`],
        },
        {
          id: `app-malevole`,
          title: `Fausses applis de banque et « mises à jour » par SMS`,
          how: `Un SMS vous invite à télécharger une « mise à jour de sécurité » de votre banque ou une appli santé depuis un lien. C'est une application piégée (sur Android, souvent un fichier .apk) qui demande les autorisations « Accessibilité » : elle peut alors lire les codes de la banque, vider le compte et effacer le téléphone.`,
          example: { kind: `sms`, from: `Banque`, text: `Cher client, votre application n'est plus à jour. Téléchargez la mise à jour de sécurité obligatoire : [lien]` },
          flags: [`Un lien pour télécharger une application en dehors des stores`, `Une application qui demande les autorisations d'Accessibilité`],
          todo: [`N'installez des applications que depuis Google Play ou l'App Store`, `Si vous avez installé quelque chose : mode avion, appelez la banque depuis un autre téléphone, réinitialisez l'appareil`],
        },
      ],
    },
    {
      id: `telefono`,
      title: `Appels et voix`,
      intro: `L'arnaque qui coûte le plus cher aux familles : une voix aimable, un numéro qui semble vrai et la peur de perdre ses économies.`,
      scams: [
        {
          id: `finto-operatore`,
          title: `Le faux conseiller bancaire et le faux gendarme`,
          how: `D'abord arrive un SMS « de sécurité » sur un virement suspect, puis l'appel. Sur l'écran s'affiche le vrai numéro de votre banque ou de la gendarmerie (il est falsifié : on appelle cela le spoofing). Le conseiller, très professionnel, vous convainc de déplacer votre argent sur un « compte sécurisé », de lui dicter vos codes ou de valider une notification dans l'application. Les victimes perdent parfois quelques milliers d'euros, parfois les économies de toute une vie.`,
          example: { kind: `call`, from: `Service antifraude (le numéro de votre banque)`, text: `Bonjour, nous avons bloqué un virement suspect de 2 450 €. Pour protéger votre épargne, nous devons la transférer tout de suite sur un compte sécurisé. Ne raccrochez pas.` },
          flags: [`« Mettre votre argent à l'abri » sur un autre compte`, `Urgence et consigne de n'en parler à personne`, `Demande d'un code SMS, de votre PIN ou de valider une notification`],
          todo: [`Raccrochez et rappelez vous-même la banque au numéro au dos de votre carte, quelques minutes plus tard ou depuis un autre téléphone`, `Aucune banque et aucun policier ne demande de virement vers un compte sécurisé`, `Si vous avez payé : appelez tout de suite la banque pour bloquer le virement, puis le 17 et portez plainte`],
          ai: `Les opérateurs filtrent de plus en plus d'appels falsifiés, mais les escrocs changent sans cesse de numéro : le bon numéro sur l'écran ne garantit rien.`,
          vignette: `call`,
        },
        {
          id: `voce-clonata`,
          title: `La voix clonée d'un proche`,
          how: `Quelques secondes d'une vidéo sur les réseaux sociaux suffisent pour cloner la voix d'un fils ou d'un petit-enfant. Arrive alors un appel ou un message vocal désespéré : un accident, une arrestation, il faut tout de suite un avocat. Souvent, un « avocat » ou un coursier se présente ensuite pour récupérer de l'argent liquide et des bijoux.`,
          example: { kind: `call`, from: `Numéro inconnu`, text: `Papi, c'est moi... j'ai eu un accident, j'ai besoin d'argent tout de suite pour l'avocat, ne dis rien à maman !` },
          flags: [`Urgence, pleurs, panique`, `On vous demande de ne prévenir personne`, `Un numéro différent de d'habitude`],
          todo: [`Raccrochez et appelez le numéro que vous connaissez de votre proche`, `Utilisez le mot de passe de la famille`, `Ne remettez jamais d'argent ou de bijoux à quelqu'un qui se présente à votre porte`],
          ai: `L'intelligence artificielle imite aujourd'hui une voix de façon très réaliste : même si c'est « sa » voix, vérifiez toujours en rappelant.`,
        },
        {
          id: `supporto-tecnico`,
          title: `Le faux support technique`,
          how: `Pendant que vous naviguez, une fenêtre plein écran apparaît avec une sirène : « Votre ordinateur est infecté, appelez Microsoft immédiatement ». Le faux technicien vous fait installer un logiciel de prise en main à distance, puis se fait payer ou entre dans votre banque en ligne.`,
          example: { kind: `popup`, from: `Alerte de sécurité`, text: `ATTENTION ! Votre PC est infecté. N'éteignez pas l'ordinateur. Appelez immédiatement l'assistance : 01 ...` },
          flags: [`Alarmes sonores et numéro à appeler`, `Demande d'installer AnyDesk, TeamViewer ou un logiciel similaire`],
          todo: [`Microsoft et Apple n'affichent jamais de numéro à appeler`, `Fermez le navigateur, de force si besoin`, `N'installez rien à la demande d'un inconnu`],
        },
        {
          id: `luce-gas`,
          title: `Les faux fournisseurs d'électricité et de gaz`,
          how: `Un conseiller « du service régional » ou « de l'autorité de l'énergie » vous annonce un tarif réduit, un chèque énergie ou un remboursement, et vous demande le numéro PDL (électricité) ou PCE (gaz) de votre facture, ainsi que votre RIB. Avec ces informations, les escrocs souscrivent des contrats que vous n'avez pas demandés ou volent vos données.`,
          example: { kind: `call`, from: `Service énergie`, text: `Bonjour, à partir de lundi vous passez au tarif réduit. Pouvez-vous me confirmer le numéro PDL qui figure sur votre facture ?` },
          flags: [`Demande du numéro PDL ou PCE, de votre RIB ou d'une photo de votre facture`, `Des organismes « régionaux » ou des « autorités » qui appellent pour des offres`],
          todo: [`Ne donnez jamais les numéros de votre facture ni votre RIB par téléphone`, `Pour un contrat que vous n'avez pas demandé, contactez votre fournisseur`],
        },
        {
          id: `sim-swap`,
          title: `Le vol de la carte SIM (SIM swap)`,
          how: `Avec de faux papiers ou un complice, l'escroc obtient un duplicata de votre carte SIM. Votre téléphone n'a plus de réseau et c'est lui qui reçoit les SMS contenant les codes de la banque.`,
          flags: [`Votre téléphone affiche soudain « Aucun service » ou « Appels d'urgence uniquement »`],
          todo: [`Appelez tout de suite votre opérateur et votre banque depuis un autre téléphone`, `Activez le code PIN de la carte SIM`, `Préférez les validations dans l'application de la banque plutôt que par SMS`],
        },
      ],
    },
    {
      id: `chat`,
      title: `WhatsApp, réseaux sociaux et messageries`,
      intro: `Ici, l'arnaque passe par la confiance : un proche, un ami, quelqu'un qui semble s'intéresser à vous.`,
      scams: [
        {
          id: `finto-figlio`,
          title: `« Coucou maman, j'ai changé de numéro »`,
          how: `Un numéro inconnu vous écrit en se faisant passer pour votre fils ou votre fille : le téléphone est cassé, voici le nouveau numéro. Après quelques messages arrive la demande : un virement urgent pour une facture, « je te rembourse demain ».`,
          example: { kind: `chat`, from: `+33 6 xx xx xx xx`, text: `Coucou maman, mon téléphone est tombé dans l'eau, c'est mon nouveau numéro, enregistre-le. Je dois payer une facture urgente, tu peux me faire un virement ? Je te rembourse tout demain ❤️` },
          flags: [`Un numéro inconnu qui se présente comme un proche`, `Il n'utilise ni votre prénom ni vos petits surnoms`, `Il évite de vous appeler`],
          todo: [`Appelez l'ancien numéro de votre proche`, `Posez une question dont lui seul connaît la réponse`, `Utilisez le mot de passe de la famille`],
          vignette: `whatsapp`,
        },
        {
          id: `codice-6-cifre`,
          title: `« Je t'ai envoyé un code par erreur » : le vol du compte`,
          how: `Un ami (en réalité, son compte a déjà été piraté) vous demande de lui renvoyer un code à 6 chiffres « arrivé par erreur », ou de voter pour sa nièce à un concours. C'est le code de vérification de votre WhatsApp : en le donnant, vous perdez votre compte et l'escroc demande de l'argent à tous vos contacts.`,
          example: { kind: `chat`, from: `Marc`, text: `Salut ! Tu as reçu un code à 6 chiffres ? Je l'ai envoyé sur ton numéro par erreur, tu peux me le transférer s'il te plaît ?` },
          flags: [`Demande d'un code reçu par SMS`, `Un lien pour « voter » ou « vérifier »`],
          todo: [`Ne transmettez jamais un code de vérification, à personne`, `Activez la vérification en deux étapes de WhatsApp (code PIN + e-mail)`, `Si vous l'avez perdu : réinstallez WhatsApp, vérifiez votre numéro et prévenez vos contacts`],
        },
        {
          id: `romance`,
          title: `L'arnaque sentimentale`,
          how: `Un profil séduisant (militaire en mission, médecin à l'étranger, chef d'entreprise) vous fait la cour pendant des semaines avec attentions et promesses. Puis arrivent les demandes : de l'argent pour la douane, une urgence, un billet d'avion. Cela se transforme souvent en arnaque à l'investissement en cryptomonnaies.`,
          flags: [`La personne ne se montre jamais en vrai`, `Histoires tristes et demandes d'argent`, `Invitation à investir ensemble`],
          todo: [`Vérifiez ses photos avec une recherche d'image inversée`, `N'envoyez jamais d'argent à quelqu'un que vous n'avez jamais rencontré`, `Parlez-en à une personne de confiance`],
          ai: `Photos, messages et même appels vidéo peuvent être générés par l'intelligence artificielle.`,
          vignette: `romance`,
        },
        {
          id: `sextortion`,
          title: `Le chantage sexuel et le faux pirate`,
          how: `Il y a la version de masse : un e-mail prétend vous avoir filmé avec votre webcam et réclame de l'argent en Bitcoin, parfois en citant un de vos anciens mots de passe volés pour paraître crédible. En général, aucune vidéo n'existe. Et il y a la version réelle : après un échange d'images intimes avec un faux profil, le chantage commence. Ce type de chantage touche aussi beaucoup d'adolescents.`,
          example: { kind: `email`, from: `Inconnu`, text: `J'ai pris le contrôle de votre appareil et je vous ai filmé avec la webcam. Payez 530 € en Bitcoin sous 48 heures ou j'envoie la vidéo à tous vos contacts.` },
          flags: [`Menaces, délais et paiement en cryptomonnaie`, `Un de vos anciens mots de passe dans le texte`],
          todo: [`Ne payez pas et ne répondez pas`, `Gardez les preuves et portez plainte à la police ou à la gendarmerie`, `Changez le mot de passe cité`],
          ai: `Aujourd'hui, on peut créer de fausses images intimes à partir de photos ordinaires : ce n'est pas votre faute, portez plainte.`,
          vignette: `blackmail`,
        },
        {
          id: `lavoro`,
          title: `Travail facile à domicile et « likes » payés`,
          how: `Un message sur WhatsApp ou Telegram propose de 50 à 300 € par jour pour mettre des « j'aime » ou écrire des avis. Les premiers paiements arrivent vraiment, pour gagner votre confiance. Puis vous entrez dans un groupe où il faut verser de l'argent pour « débloquer des missions premium ». Les pertes peuvent vite devenir très importantes.`,
          example: { kind: `chat`, from: `Recruteur RH`, text: `Bonjour ! Nous recherchons des collaborateurs à temps partiel : de 50 à 300 € par jour depuis chez vous en aimant des vidéos YouTube. Cela vous intéresse ?` },
          flags: [`Des offres d'emploi que vous n'avez jamais demandées`, `Pour gagner, il faut d'abord payer`, `On vous demande de recevoir et de renvoyer l'argent d'autres personnes`],
          todo: [`Un vrai travail ne vous demande jamais d'argent`, `Ne prêtez jamais votre compte bancaire : vous risquez d'être accusé de blanchiment`],
          vignette: `job`,
        },
      ],
    },
    {
      id: `acquisti`,
      title: `Achats, petites annonces et vacances`,
      intro: `Des prix irrésistibles, des vendeurs très aimables et la hâte de conclure : le scénario est toujours le même.`,
      scams: [
        {
          id: `negozi-falsi`,
          title: `Fausses boutiques en ligne vues sur les réseaux sociaux`,
          how: `Une publicité sponsorisée annonce « on vide le stock, -80 % » sur des chaussures, des sacs ou de l'électronique de marque. Le site, souvent créé avec l'intelligence artificielle, semble vrai, mais la marchandise n'arrive jamais ou c'est de la contrefaçon. Les faux billets de concert circulent aussi beaucoup.`,
          example: { kind: `ad`, from: `Sponsorisé`, text: `FERMETURE DU MAGASIN ! Tout à -80 % aujourd'hui seulement. Derniers articles disponibles 🔥` },
          flags: [`Réductions irréalistes et compte à rebours`, `Aucun numéro SIRET, aucune adresse ni aucun contact`, `Paiement uniquement par virement ou en cryptomonnaie`],
          todo: [`Utilisez un moyen de paiement protégé (carte bancaire, PayPal « biens et services »)`, `Cherchez des avis sur d'autres sites`, `Méfiez-vous des sites créés il y a seulement quelques jours`],
          vignette: `shop`,
        },
        {
          id: `marketplace`,
          title: `Le faux acheteur sur Leboncoin, Vinted et Marketplace`,
          how: `Vous vendez un objet et un « acheteur » vous écrit qu'il a déjà payé via le service de livraison : il suffit de cliquer sur un lien pour « recevoir l'argent ». La page vous demande les données de votre carte. Ou c'est le vendeur qui réclame un acompte par virement ou recharge, puis disparaît.`,
          example: { kind: `chat`, from: `Acheteur`, text: `J'ai déjà payé avec le service de livraison, cliquez ici pour confirmer et recevoir le paiement sur votre carte : [lien]` },
          flags: [`Invitation à quitter la messagerie de la plateforme`, `Pour « recevoir » de l'argent, on vous demande les données de votre carte`, `Des demandes de paiement d'inconnus dans votre application bancaire (Wero, Paylib)`],
          todo: [`Restez toujours dans la messagerie et le paiement de la plateforme`, `Pour recevoir de l'argent, on n'a jamais besoin des données de votre carte`, `Signalez l'utilisateur depuis l'application`],
        },
        {
          id: `case-vacanza`,
          title: `Locations de vacances et logements qui n'existent pas`,
          how: `Des annonces avec de très belles photos (volées ou générées) et des prix bas. Le « propriétaire » vit à l'étranger et demande un acompte de 50 % ou plus par virement ou recharge. À l'arrivée, le logement n'existe pas ou appartient à quelqu'un d'autre. Même scénario pour les locations aux étudiants.`,
          flags: [`Un gros acompte avant d'avoir vu le logement`, `Paiement en dehors de la plateforme`, `Un propriétaire impossible à rencontrer`],
          todo: [`Payez uniquement sur la plateforme de réservation`, `Vérifiez l'adresse sur une carte et les photos avec une recherche d'image inversée`, `Un acompte raisonnable tourne autour de 20 à 30 %`],
        },
        {
          id: `qr`,
          title: `Les QR codes piégés (quishing)`,
          how: `Sur les horodateurs, des escrocs collent des autocollants avec un QR code « payez votre stationnement » qui mène à un faux site. Le même piège apparaît sur de faux avis de contravention sous l'essuie-glace, des avis de colis et des e-mails qui demandent de « scanner pour vérifier votre compte ».`,
          flags: [`Un autocollant collé par-dessus le QR code d'origine`, `Après le scan, une adresse bizarre`],
          todo: [`Payez le stationnement avec l'application officielle de la ville ou du gestionnaire`, `Vérifiez toujours l'adresse qui s'ouvre après le scan`],
          vignette: `qr`,
        },
        {
          id: `premi`,
          title: `Cadeaux, loteries et héritages`,
          how: `« Félicitations, vous avez gagné un iPhone ! » : il suffit de payer 2 € de frais de port. En réalité, vous souscrivez un abonnement caché sur votre carte. Variantes : des héritages de plusieurs millions venant de notaires étrangers, des cadeaux au nom de supermarchés.`,
          example: { kind: `sms`, from: `Cadeau`, text: `Félicitations ! Vous avez été sélectionné pour gagner un iPhone 17. Payez seulement 2 € de frais de port : [lien]` },
          flags: [`Vous gagnez un jeu auquel vous n'avez pas participé`, `De petits frais à payer pour recevoir le cadeau`],
          todo: [`Si vous n'avez pas joué, vous n'avez pas gagné`, `Ne payez jamais de frais pour recevoir un cadeau`],
        },
      ],
    },
    {
      id: `soldi`,
      title: `Investissements et argent`,
      intro: `Les pertes les plus lourdes : souvent les économies d'une vie, perdues en quelques mois.`,
      scams: [
        {
          id: `investimenti`,
          title: `Placements avec de fausses célébrités (deepfake) et faux courtiers`,
          how: `Une publicité ou un faux article de journal montre une personnalité politique, un présentateur TV ou un grand banquier qui révèle « le secret pour gagner de l'argent ». Vous laissez votre numéro, un « conseiller » vous appelle, vous fait installer une application de prise en main à distance et vous montre des gains fictifs. Quand vous voulez retirer votre argent, il faut payer des « taxes » et des « frais de déblocage ». Variante : une relation en ligne construite pendant des semaines, puis l'invitation à investir en cryptomonnaies.`,
          example: { kind: `ad`, from: `Actualités du jour`, text: `Le secret que les banques ne veulent pas que vous connaissiez : avec seulement 250 €, gagnez 1 500 € par semaine. Regardez l'interview.` },
          flags: [`Rendements garantis ou très élevés`, `Des célébrités qui « recommandent » un placement`, `Demande d'installer AnyDesk ou une application similaire`, `Pour retirer votre argent, il faut payer`],
          todo: [`Vérifiez que l'intermédiaire est autorisé sur les sites de l'AMF et de la Banque de France`, `Consultez les listes noires de l'AMF`, `N'installez jamais d'application de prise en main à distance`],
          ai: `Des vidéos truquées de personnalités politiques et de visages connus de la télévision sont régulièrement utilisées pour ces publicités.`,
          vignette: `invest`,
        },
        {
          id: `recupero-fondi`,
          title: `Ceux qui promettent de récupérer l'argent perdu`,
          how: `Après une arnaque, un faux avocat, une société de recouvrement ou même une fausse « Police » ou « Europol » vous contacte : ils ont retrouvé votre argent, mais pour le débloquer il faut payer des frais. C'est une deuxième arnaque sur la même victime.`,
          flags: [`Ce sont eux qui vous contactent, en sachant que vous avez été arnaqué`, `Ils demandent un paiement à l'avance`],
          todo: [`Aucun organisme public ne demande d'argent pour vous rendre des sommes volées`, `Ne parlez qu'à la police, à la gendarmerie et aux avocats que vous choisissez vous-même`],
        },
        {
          id: `beneficenza`,
          title: `Fausses collectes de dons`,
          how: `Après des inondations, des tremblements de terre ou des guerres apparaissent des pages qui imitent de vraies associations, des RIB de particuliers et des cagnottes avec des photos émouvantes, parfois générées par l'intelligence artificielle.`,
          flags: [`Un RIB au nom d'un particulier`, `Des pages créées récemment et très émotionnelles`],
          todo: [`Donnez uniquement depuis le site officiel de l'association`, `Jamais sur un RIB reçu par message`],
        },
      ],
    },
    {
      id: `identita`,
      title: `Identité numérique et données personnelles`,
      intro: `Vos données valent de l'argent : elles servent à ouvrir des comptes, demander des crédits et rendre d'autres arnaques plus crédibles.`,
      scams: [
        {
          id: `spid`,
          title: `Le vol de FranceConnect et l'usurpation d'identité`,
          how: `Avec des papiers et des selfies volés (par exemple avec un faux SMS de l'Assurance maladie), ou en volant vos identifiants, les escrocs accèdent à vos comptes via FranceConnect ou créent des comptes à votre nom. Ils changent ensuite le RIB de vos remboursements et de vos aides, ouvrent des comptes ou demandent des crédits.`,
          flags: [`Un e-mail de connexion à un service que vous n'avez pas utilisé`, `Des remboursements ou des aides qui n'arrivent plus`],
          todo: [`N'envoyez jamais de photos de vos papiers ou de selfie`, `Activez la double authentification sur les comptes que vous utilisez avec FranceConnect`, `En cas de vol : portez plainte, changez vos mots de passe et vérifiez le RIB enregistré sur vos espaces impots.gouv, ameli et CAF`],
          vignette: `identity`,
        },
        {
          id: `data-breach`,
          title: `Quand l'escroc connaît déjà vos informations`,
          how: `Après un vol de données dans une entreprise, les escrocs connaissent votre nom, votre adresse, votre numéro client et vos derniers achats. Ils s'en servent pour rendre leurs messages et leurs appels crédibles, parfois en se faisant passer pour l'entreprise touchée ou pour la « police ».`,
          flags: [`Ils en savent beaucoup sur vous et demandent quand même des informations ou de l'argent`],
          todo: [`Connaître vos informations ne rend personne digne de confiance`, `Changez vos mots de passe et utilisez un gestionnaire de mots de passe`, `Vous pouvez vérifier si votre e-mail a fuité sur haveibeenpwned.com`],
        },
      ],
    },
    {
      id: `aziende`,
      title: `Pour les entrepreneurs, artisans et indépendants`,
      intro: `Artisans, commerçants et professions libérales sont des cibles parfaites : ils paient des factures tous les jours.`,
      scams: [
        {
          id: `iban-fattura`,
          title: `Le RIB modifié sur la facture et le faux patron`,
          how: `La messagerie d'un fournisseur est piratée, ou les escrocs utilisent une adresse presque identique. Vous recevez un message avec le « nouveau RIB » pour les paiements. Variante : le faux dirigeant demande un virement urgent et confidentiel. Une seule facture détournée peut coûter des centaines de milliers d'euros.`,
          example: { kind: `email`, from: `Comptabilité <comptabilite@fournisseur-sarl.co>`, text: `Nous vous informons que, suite à un audit, nos coordonnées bancaires ont changé. À partir d'aujourd'hui, merci d'effectuer vos paiements sur le nouveau RIB ci-joint.` },
          flags: [`Un changement de RIB annoncé par e-mail`, `Urgence et confidentialité autour d'un virement`],
          todo: [`Vérifiez chaque changement de RIB par téléphone, avec le numéro déjà dans votre carnet`, `Activez la double authentification sur la messagerie`, `Deux personnes contrôlent les virements importants`],
          vignette: `invoice`,
        },
      ],
    },
  ],
  victim: {
    title: `Vous avez été arnaqué ? Que faire tout de suite`,
    intro: `N'ayez pas honte : vous êtes la victime, pas le coupable. Agir dans les premières heures peut faire toute la différence.`,
    steps: [
      { title: `Bloquez tout`, text: `Faites opposition sur vos cartes et bloquez vos accès depuis l'application de la banque ou au numéro d'opposition indiqué au dos de votre carte ou dans votre application bancaire.` },
      { title: `Demandez le rappel du virement`, text: `Appelez tout de suite la banque et demandez de bloquer ou de rappeler le virement : avec les virements instantanés, chaque minute compte.` },
      { title: `Sécurisez vos comptes`, text: `Changez vos mots de passe (d'abord messagerie et banque), activez la double authentification et déconnectez les appareils que vous ne reconnaissez pas.` },
      { title: `Rassemblez les preuves`, text: `Captures d'écran des messages et des conversations, e-mails, numéros de téléphone, RIB du destinataire, relevés bancaires, liens. N'effacez rien.` },
      { title: `Portez plainte`, text: `Portez plainte au commissariat ou à la gendarmerie, et faites-vous guider sur 17cyber.gouv.fr. La plainte sert aussi à demander le remboursement à votre banque.` },
      { title: `Prévenez les autres`, text: `Si un de vos comptes a été volé, prévenez vos contacts : ils pourraient recevoir des demandes d'argent en votre nom.` },
    ],
  },
  contacts: {
    title: `Qui contacter en France`,
    intro: `Les numéros et les sites officiels. Enregistrez-les maintenant, avant d'en avoir besoin.`,
    items: [
      { name: `Urgence : 17 ou 112`, detail: `Si vous êtes en danger ou si quelqu'un est à votre porte pour récupérer de l'argent. Le 112 fonctionne dans toute l'Europe.`, phone: `17` },
      { name: `17Cyber`, detail: `Assistance en ligne gratuite de la police, de la gendarmerie et de Cybermalveillance.gouv.fr : diagnostic, conseils et échange par tchat.`, url: `https://17cyber.gouv.fr` },
      { name: `Cybermalveillance.gouv.fr`, detail: `Aide aux victimes, conseils et fiches pratiques sur les arnaques.`, url: `https://www.cybermalveillance.gouv.fr` },
      { name: `PHAROS`, detail: `Le portail officiel pour signaler un contenu illicite sur Internet (site, réseau social, forum).`, url: `https://internet-signalement.gouv.fr` },
      { name: `33700`, detail: `Transférez gratuitement les SMS indésirables au 33700. Pour un appel, envoyez « spam vocal » suivi du numéro qui vous a appelé.`, url: `https://www.33700.fr`, phone: `33700` },
    ],
    note: `En Belgique et en Suisse, contactez la police locale et votre banque. Sur les réseaux sociaux et les applications, utilisez toujours la fonction « Signaler » de la plateforme (WhatsApp, Facebook, Instagram, Leboncoin, Vinted, Airbnb).`,
  },
  whyReport: {
    title: `Pourquoi porter plainte est important`,
    items: [
      `Cela permet d'ouvrir une enquête et d'arrêter les escrocs avant qu'ils ne fassent d'autres victimes.`,
      `Cela aide à repérer et à bloquer les nouvelles campagnes.`,
      `Cela sert à demander le remboursement à votre banque et à limiter les dégâts.`,
      `Cela rend le monde numérique plus sûr pour tout le monde.`,
      `N'ayez pas honte : c'est l'escroc qui devrait avoir honte, pas vous.`,
    ],
  },
  ui: {
    toc: `Sommaire`,
    print: `Télécharger ou imprimer le manuel`,
    howItWorks: `Comment ça marche`,
    example: `Exemple réel`,
    flags: `Signaux d'alerte`,
    todo: `Que faire`,
    ai: `Avec l'intelligence artificielle`,
    checkmailTitle: `Vous avez reçu un e-mail suspect ?`,
    checkmailText: `Avec KUMANI CheckMail, vous le vérifiez en quelques secondes : expéditeur, liens, pièces jointes et texte passés à la loupe.`,
    checkmailCta: `Ouvrir CheckMail`,
    updated: `Mis à jour en septembre 2026 avec les données du FBI, de la FTC, de la Polizia Postale, du CERT-AgID et de la Consob.`,
    disclaimer: `Ce manuel a un but informatif et ne remplace pas l'avis des forces de l'ordre, de votre banque ou d'un avocat. Les arnaques changent sans cesse : dans le doute, arrêtez-vous et demandez.`,
    copyright: `© KUMANI. Vous pouvez le partager librement pour aider d'autres personnes à se protéger.`,
  },
}

export default fr
