import type { GuideContent } from '@/lib/antitruffa/types'

// Manuale anti-truffa KUMANI — italiano (versione di riferimento).
// Fonti principali: Polizia Postale (report 2025 e avvisi 2026), CERT-AgID,
// Consob, AGCOM, AgID, INPS, Agenzia delle Entrate. Aggiornato a settembre 2026.
// Capitolo "Alla porta di casa": Direzione Centrale della Polizia Criminale
// (truffe agli over 65, dati 2024, nel Rapporto Eurispes 2025) e avvisi di
// Comuni e Carabinieri. Nelle altre lingue: BKA 2025 (DE), National Trading
// Standards / Friends Against Scams 2021 (UK), campagne di Ministerio del
// Interior (ES), Gendarmerie e Préfecture de police (FR), PSP e GNR (PT).
const it: GuideContent = {
  eyebrow: `Manuale KUMANI · Sicurezza e Verifica`,
  title: `Come difendersi dalle truffe online e a domicilio`,
  motto: `Non tutto ciò che è gratis vale poco. Questo può valere i tuoi risparmi.`,
  lead: `Le truffe di oggi non hanno più errori di grammatica: usano l'intelligenza artificiale, numeri di telefono falsificati e siti identici a quelli veri. Questo manuale ti mostra, con esempi reali, come riconoscerle in pochi secondi e cosa fare se qualcosa è già andato storto.`,
  giftNote: `Un regalo riservato ai Kumani. Leggilo, salvalo e condividilo con chi ami: genitori e nonni sono i bersagli preferiti.`,
  stats: [
    { value: `51.560`, label: `casi trattati dalla Polizia Postale nel 2025` },
    { value: `269 mln €`, label: `sottratti con frodi online in Italia nel 2025` },
    { value: `3.620`, label: `campagne malevole scoperte dal CERT-AgID nel 2025` },
    { value: `1.829`, label: `siti di falsi investimenti oscurati dalla Consob` },
  ],
  statsSource: `Fonti: Polizia Postale, report annuale 2025; CERT-AgID, report 2025; Consob, comunicato del 24/09/2026.`,
  tenSeconds: {
    title: `Il test dei 10 secondi`,
    intro: `Prima di cliccare, rispondere o pagare, fermati e fatti queste domande. Se anche una sola risposta è "sì", è quasi certamente una truffa.`,
    items: [
      `Mi mette fretta o mi minaccia (blocco del conto, multa, denuncia)?`,
      `Mi chiede password, codici, PIN, dati della carta o foto dei documenti?`,
      `Mi chiede di pagare con bonifico istantaneo, ricarica, carta regalo o criptovalute?`,
      `Mi propone guadagni facili, premi o prezzi troppo belli per essere veri?`,
      `Mi chiede di non parlarne con nessuno o di restare al telefono?`,
      `Arriva da un numero o da un indirizzo che non conosco, anche se dice di essere qualcuno che conosco?`,
    ],
  },
  rules: {
    title: `Le 6 regole d'oro`,
    items: [
      { title: `Riattacca e richiama tu`, text: `Banca, Polizia, Carabinieri, INPS: se ti contattano, chiudi e richiama il numero ufficiale che trovi tu. Il numero che compare sul display può essere falsificato.` },
      { title: `Mai codici a nessuno`, text: `Nessun operatore vero ti chiederà mai OTP, PIN, password o il codice a 6 cifre di WhatsApp. Chi lo chiede è un truffatore, sempre.` },
      { title: `Apri tu il sito`, text: `Non usare i link ricevuti: apri l'app ufficiale o scrivi tu l'indirizzo del sito nel browser.` },
      { title: `Doppia protezione ovunque`, text: `Attiva l'autenticazione a due fattori su email, banca, social e WhatsApp (verifica in due passaggi). Usa password diverse per ogni servizio.` },
      { title: `Aggiorna tutto`, text: `Telefono, computer e app aggiornati chiudono le porte che i truffatori usano per entrare. Installa app solo da Google Play o App Store.` },
      { title: `Una parola d'ordine in famiglia`, text: `Scegliete una parola segreta da usare se un familiare chiede soldi per un'emergenza: le voci ormai si possono clonare.` },
    ],
  },
  chapters: [
    {
      id: `messaggi`,
      title: `Email, PEC e SMS`,
      intro: `Il canale più usato: nel 2025 i temi preferiti sono stati spedizioni, banche, multe e rimborsi fiscali.`,
      scams: [
        {
          id: `phishing`,
          title: `Phishing: l'email che imita un ente o un'azienda`,
          how: `Un'email con logo e tono ufficiali (Agenzia delle Entrate, ACI, banca, Aruba) ti invita a cliccare su un link. Il sito è una copia perfetta dell'originale, spesso creata con l'intelligenza artificiale, e serve a rubarti credenziali, SPID o dati della carta. Sempre più spesso arriva anche via PEC, con un allegato che installa un virus.`,
          example: { kind: `email`, from: `Agenzia delle Entrate <rimborsi@agenzia-rimborsi.info>`, text: `Gentile contribuente, risulta un rimborso di € 312,40 a suo favore. Per riceverlo confermi i dati entro 48 ore: [link]` },
          flags: [`Fretta e scadenze ravvicinate`, `L'indirizzo del mittente o del sito non è quello ufficiale`, `Chiede dati della carta, password o accesso SPID`, `Allegati .zip, .html o .js`],
          todo: [`Non cliccare: apri tu il sito ufficiale o l'app`, `Inoltra l'email al CERT-AgID (malware@cert-agid.gov.it)`, `Se hai inserito dati: cambia password e chiama la banca`],
          ai: `I testi non hanno più errori e i siti clone sono identici: non fidarti dell'aspetto, controlla l'indirizzo.`,
          vignette: `email`,
        },
        {
          id: `clickfix`,
          title: `Il falso "Non sono un robot"`,
          how: `Un sito ti mostra una finta verifica anti-robot e ti chiede di premere alcuni tasti (per esempio Windows+R, poi Ctrl+V e Invio). In realtà stai incollando ed eseguendo un comando che installa un virus. Nel 2025 questa tecnica, chiamata ClickFix, è cresciuta moltissimo.`,
          flags: [`Una verifica che chiede di premere combinazioni di tasti`, `Istruzioni per aprire "Esegui" o il terminale`],
          todo: [`Chiudi la pagina: nessuna verifica vera chiede di premere tasti`, `Se l'hai già fatto, spegni la connessione e fai controllare il computer`],
        },
        {
          id: `smishing-inps`,
          title: `SMS "INPS": la caccia ai tuoi documenti`,
          how: `Un SMS a nome dell'INPS ti avvisa che devi aggiornare i dati per non perdere un beneficio. Il sito falso chiede IBAN, foto di carta d'identità, tessera sanitaria, patente, buste paga e perfino un selfie con il documento. Con questo materiale rubano la tua identità, attivano uno SPID a tuo nome e rivendono i documenti.`,
          example: { kind: `sms`, from: `INPS`, text: `INPS: gentile utente, per non perdere i benefici in corso aggiorni i suoi dati entro oggi: [link]` },
          flags: [`L'INPS non chiede mai di aggiornare dati tramite link in un SMS`, `Richiesta di foto dei documenti e selfie`],
          todo: [`Verifica solo su inps.it o nell'app INPS Mobile`, `Non inviare mai foto di documenti o selfie tramite un link`, `Se l'hai già fatto: denuncia e controlla SPID, IBAN e conti`],
          vignette: `sms`,
        },
        {
          id: `smishing-multe`,
          title: `SMS di multe, pedaggi e bollo non pagati`,
          how: `Arriva un SMS con un piccolo importo "da saldare subito": una multa a nome di PagoPA o SEND, un pedaggio di Autostrade, il bollo auto dell'ACI. Il sito falso chiede i dati della carta. Nel 2025 il CERT-AgID ha contato 328 campagne con false multe; solo ad aprile 2026 sono partiti circa 79.000 SMS di finti pedaggi.`,
          example: { kind: `sms`, from: `Autostrade`, text: `Autostrade per l'Italia: risulta un pedaggio non saldato di € 6,50. Eviti la sanzione pagando qui: [link]` },
          flags: [`Importo piccolo e urgenza per "evitare la maggiorazione"`, `Link nel messaggio`, `Pagina fatta solo per smartphone`],
          todo: [`Le multe vere si controllano nell'app IO o sul sito del Comune`, `Autostrade non chiede pagamenti via SMS`, `Mai inserire i dati della carta da un link ricevuto`],
          vignette: `sms`,
        },
        {
          id: `pacchi`,
          title: `Pacchi in giacenza e false spese doganali`,
          how: `Un messaggio a nome di Poste, DHL, GLS o BRT dice che il tuo pacco è bloccato e che servono pochi euro di "spese" o "dazi". È uno dei temi più usati in assoluto, perché quasi tutti aspettano un pacco.`,
          example: { kind: `sms`, from: `Poste`, text: `Il suo pacco è fermo in dogana. Paghi 1,99 € di tasse per la consegna: [link]` },
          flags: [`Non sai di quale pacco si tratta`, `Chiede pochi euro con la carta`],
          todo: [`Traccia la spedizione dal sito del venditore o del corriere`, `I dazi veri si pagano al corriere o tramite canali ufficiali`],
        },
        {
          id: `account-sospeso`,
          title: `"Il tuo account è sospeso" (Netflix, Amazon, PayPal)`,
          how: `Email o SMS dicono che il pagamento dell'abbonamento non è andato a buon fine o che l'account verrà chiuso. Esiste anche la versione telefonica: una voce registrata annuncia un ordine costoso e ti chiede di premere 1 per annullarlo.`,
          example: { kind: `email`, from: `Netflix <avvisi@netflix-supporto.com>`, text: `Il pagamento del tuo abbonamento non è andato a buon fine. Aggiorna i dati entro 24 ore per non perdere l'accesso: [link]` },
          flags: [`Minaccia di blocco o chiusura`, `Mittente con un dominio "quasi" giusto`],
          todo: [`Apri direttamente l'app o il sito e controlla il tuo account`, `Non premere tasti durante chiamate registrate: riattacca`],
        },
        {
          id: `app-malevole`,
          title: `False app della banca e "aggiornamenti" via SMS`,
          how: `Un SMS ti invita a scaricare un "aggiornamento di sicurezza" della banca o un'app sanitaria da un link. È un'app pirata (per Android spesso un file .apk) che chiede i permessi di "Accessibilità": così legge i codici della banca, può svuotare il conto e cancellare il telefono.`,
          example: { kind: `sms`, from: `Banca`, text: `Gentile cliente, la sua app è obsoleta. Scarichi l'aggiornamento di sicurezza obbligatorio: [link]` },
          flags: [`Link per scaricare un'app fuori dagli store`, `Un'app che chiede i permessi di Accessibilità`],
          todo: [`Installa app solo da Google Play o App Store`, `Se hai installato qualcosa: modalità aereo, chiama la banca da un altro telefono, ripristina il dispositivo`],
        },
      ],
    },
    {
      id: `telefono`,
      title: `Telefonate e voci`,
      intro: `La truffa più costosa per le famiglie italiane: una voce gentile, un numero che sembra vero e la paura di perdere i risparmi.`,
      scams: [
        {
          id: `finto-operatore`,
          title: `Il finto operatore della banca e il finto carabiniere`,
          how: `Prima arriva un SMS "di sicurezza" su un bonifico sospetto, poi la telefonata. Sul display compare il numero vero della banca o dei Carabinieri (è falsificato: si chiama spoofing). L'operatore, molto professionale, ti convince a spostare i soldi su un "conto sicuro", a dettargli i codici o ad approvare una notifica nell'app. Nel 2026 i casi sono continui: da poche migliaia di euro fino a 241.000 € sottratti a un anziano di Milano.`,
          example: { kind: `call`, from: `Ufficio antifrode (numero della tua banca)`, text: `Buongiorno, abbiamo bloccato un bonifico sospetto di 2.450 €. Per proteggere i suoi risparmi dobbiamo spostarli subito su un conto sicuro. Non chiuda la chiamata.` },
          flags: [`"Mettere al sicuro i soldi" su un altro conto`, `Fretta e invito a non parlarne con nessuno`, `Richiesta di OTP, PIN o di approvare una notifica`],
          todo: [`Riattacca e richiama tu la banca dal numero sul retro della carta, dopo qualche minuto o da un altro telefono`, `Nessuna banca e nessuna forza dell'ordine chiede bonifici su conti sicuri`, `Se hai pagato: chiama subito la banca per bloccare il bonifico, poi 112 e denuncia`],
          ai: `Dal 2025 l'AGCOM blocca molte chiamate falsificate dall'estero, ma i truffatori si spostano su altri numeri: il numero giusto sul display non garantisce nulla.`,
          vignette: `call`,
        },
        {
          id: `voce-clonata`,
          title: `La voce clonata di un familiare`,
          how: `Bastano pochi secondi di un video sui social per clonare la voce di un figlio o di un nipote. Arriva una chiamata o un vocale disperato: un incidente, un arresto, serve subito un avvocato. Spesso poi si presenta un "avvocato" o un corriere a ritirare contanti e gioielli.`,
          example: { kind: `call`, from: `Numero sconosciuto`, text: `Nonno, sono io... ho fatto un incidente, ho bisogno subito di soldi per l'avvocato, non dirlo a mamma!` },
          flags: [`Emergenza, pianto, urgenza estrema`, `Chiede di non avvisare nessuno`, `Numero diverso dal solito`],
          todo: [`Riattacca e chiama il numero che conosci del familiare`, `Usa la parola d'ordine di famiglia`, `Non consegnare mai soldi o gioielli a chi si presenta alla porta`],
          ai: `Dal 10 ottobre 2025 diffondere deepfake che causano un danno è reato (art. 612-quater del Codice penale).`,
        },
        {
          id: `supporto-tecnico`,
          title: `Il falso supporto tecnico`,
          how: `Mentre navighi compare una finestra a tutto schermo con una sirena: "Il tuo computer è infetto, chiama subito Microsoft". Il finto tecnico ti fa installare un programma di controllo a distanza e poi si fa pagare o entra nel tuo home banking.`,
          example: { kind: `popup`, from: `Avviso di sicurezza`, text: `ATTENZIONE! Il tuo PC è infetto. Non spegnere il computer. Chiama subito l'assistenza: +39 02 ...` },
          flags: [`Allarmi sonori e numeri da chiamare`, `Richiesta di installare AnyDesk, TeamViewer o simili`],
          todo: [`Microsoft e Apple non mostrano mai numeri da chiamare`, `Chiudi il browser, anche forzatamente`, `Non installare nulla su richiesta di sconosciuti`],
        },
        {
          id: `luce-gas`,
          title: `I falsi operatori di luce e gas`,
          how: `Un operatore "dell'ufficio regionale" o "dell'autorità dell'energia" annuncia una tariffa agevolata o un rimborso e chiede il codice POD o PDR della bolletta e l'IBAN. Con questi dati attivano contratti che non hai chiesto o rubano i tuoi dati.`,
          example: { kind: `call`, from: `Ufficio energia`, text: `Buongiorno, da lunedì passa alla tariffa agevolata. Mi conferma il codice POD che trova in bolletta?` },
          flags: [`Richiesta di POD, PDR, IBAN o foto della bolletta`, `Enti "regionali" o "autorità" che chiamano per offerte`],
          todo: [`Non dare mai codici della bolletta o IBAN al telefono`, `Per contratti non richiesti rivolgiti al tuo fornitore`],
        },
        {
          id: `sim-swap`,
          title: `Il furto della SIM (SIM swap)`,
          how: `Con documenti falsi o un complice, il truffatore si fa fare un duplicato della tua SIM. Il tuo telefono resta senza linea e lui riceve gli SMS con i codici della banca.`,
          flags: [`Il telefono va all'improvviso su "Nessun servizio" o "Solo emergenza"`],
          todo: [`Chiama subito il tuo operatore e la banca da un altro telefono`, `Attiva il PIN della SIM`, `Preferisci le notifiche nell'app della banca agli SMS`],
        },
      ],
    },
    {
      id: `domicilio`,
      title: `Alla porta di casa`,
      intro: `Non tutte le truffe arrivano dal telefono o da internet. Nel 2024 in Italia le truffe a danno di persone con più di 65 anni sono state 42.890, il 15,6% in più dell’anno prima (dati della Direzione Centrale della Polizia Criminale, riportati nel Rapporto Eurispes 2025). Molte cominciano con un campanello.`,
      pattern: {
        title: `Lo schema è sempre lo stesso`,
        text: `Acqua, gas, luce, telefono, Comune, Carabinieri: cambia la divisa, non il trucco. Una persona che non aspettavi, un tesserino mostrato di fretta, un motivo urgente (una perdita, un guasto, un controllo, un rimborso) e una richiesta: entrare in casa oppure farsi dare soldi e gioielli. Spesso c’è un complice che entra o fruga mentre tu sei distratto.`,
      },
      scams: [
        {
          id: `finto-letturista`,
          title: `Il finto addetto alla lettura dei contatori`,
          how: `Suona alla porta dicendo di dover leggere il contatore dell’acqua, del gas o della luce, o di controllare i rubinetti per un problema nella zona. Una volta dentro ti fa aprire l’acqua in bagno o in cucina e, mentre sei occupato, lui o un complice cerca soldi e gioielli. Altre volte chiede subito contanti per un “conguaglio” o un “rimborso”.`,
          example: {
            kind: `notice`,
            from: `Avviso del Comune, su segnalazione dei Carabinieri`,
            text: `Si invita la cittadinanza a prestare la massima attenzione a persone che si presentino presso le abitazioni fingendosi incaricati della lettura dei contatori dell’acqua. Non consentite l’accesso a persone non identificate e, in caso di dubbi, contattate le Forze dell’Ordine.`,
          },
          flags: [`La visita non è stata annunciata da un avviso nel palazzo o in bolletta`, `Insiste per entrare o per farti aprire i rubinetti`, `Chiede contanti per conguagli, rimborsi o cauzioni`, `Mostra il tesserino di fretta o non ha nulla che lo identifichi`],
          todo: [`Non aprire a chi non aspetti: parla dalla porta chiusa o dal citofono`, `Chiama il numero scritto sulla tua bolletta, non quello che ti dà la persona, e chiedi se c’è davvero un intervento`, `Ricorda che le letture vere sono annunciate prima e spesso il contatore è fuori casa`, `Nel dubbio chiama subito il 112 e avvisa vicini e familiari anziani`, `Leggi e condividi gli avvisi del Comune e dei Carabinieri: segnalano le truffe in corso nella tua zona`],
          vignette: `door`,
        },
        {
          id: `finta-fuga-gas`,
          title: `La finta fuga di gas e il finto controllo della caldaia`,
          how: `Si presentano come tecnici del gas, dell’acquedotto o del Comune: “C’è una fuga nella zona, dobbiamo controllare subito”. Ti spaventano e ti chiedono di raccogliere soldi e gioielli “per proteggerli”, per esempio in una borsa o nel frigorifero, oppure ti fanno uscire di casa. Altre volte pretendono il pagamento di un “controllo obbligatorio” che non esiste.`,
          example: {
            kind: `door`,
            from: `Alla porta`,
            text: `Buongiorno, siamo del servizio gas. C’è una fuga nel palazzo: è pericoloso, dobbiamo entrare subito. Metta soldi e gioielli in una borsa, così non si rovinano.`,
          },
          flags: [`Allarme improvviso e paura: “è pericoloso, presto”`, `Ti chiedono di spostare o raccogliere soldi e gioielli`, `Parlano di controlli obbligatori da pagare subito, in contanti`],
          todo: [`Nessun tecnico vero ti chiede di toccare soldi o gioielli`, `Se senti davvero odore di gas esci, non usare interruttori e chiama il pronto intervento indicato in bolletta`, `Chiudi la porta e chiama il 112`],
        },
        {
          id: `finto-carabiniere-ritiro`,
          title: `Il finto carabiniere o avvocato che passa a ritirare soldi e gioielli`,
          how: `Prima arriva una telefonata: un figlio o un nipote ha avuto un incidente o è nei guai e serve subito una cauzione. Poco dopo un “incaricato”, che si presenta come carabiniere, avvocato o corriere, suona alla porta per ritirare contanti o gioielli. Ti tengono al telefono così non puoi chiamare nessuno.`,
          example: {
            kind: `call`,
            from: `Numero sconosciuto`,
            text: `Signora, sono il maresciallo dei Carabinieri. Suo nipote ha causato un incidente: per evitare il carcere serve subito una cauzione. Tra poco passa un nostro incaricato a ritirarla.`,
          },
          flags: [`Forze dell’ordine e avvocati non ritirano mai soldi o gioielli a casa`, `Ti chiedono di restare al telefono e di non parlarne con nessuno`, `Fretta e paura per un familiare`],
          todo: [`Riattacca, chiama tu il familiare e poi il 112`, `Non consegnare niente a nessuno, nemmeno a chi mostra un tesserino`, `Usa la parola d’ordine di famiglia`],
          vignette: `call`,
        },
        {
          id: `finto-funzionario`,
          title: `Il finto impiegato del Comune, dell’INPS, delle Poste o della banca`,
          how: `Si presenta come impiegato del Comune, dell’INPS, delle Poste o della banca: deve controllare la pensione, sostituire banconote “false”, verificare i documenti o consegnare un rimborso. Lo scopo è entrare, vedere dove tieni i soldi o farsi dare contanti, carte e PIN.`,
          flags: [`Enti e banche non mandano impiegati a casa senza appuntamento`, `Chiede di vedere contanti, carte, PIN o libretti`, `Parla di banconote false o di rimborsi da riscuotere subito`],
          todo: [`Chiedi nome e ufficio e chiama tu il numero ufficiale dell’ente`, `Non mostrare mai dove tieni soldi e gioielli`, `Se serve, fissa tu un appuntamento in ufficio, insieme a un familiare`],
        },
      ],
      poster: {
        title: `Da stampare e attaccare vicino alla porta`,
        lines: [`Non apro a chi non aspetto.`, `Chiedo il tesserino e chiamo io il numero della bolletta o dell’ente.`, `Nessuno ritira soldi o gioielli a casa: né Carabinieri, né avvocati, né tecnici.`, `Nel dubbio chiamo il 112.`],
        note: `Stampala e attaccala dentro la porta di casa dei tuoi genitori e dei tuoi nonni. E parlatene insieme: chi è avvisato si difende meglio.`,
      },
    },
    {
      id: `chat`,
      title: `WhatsApp, social e chat`,
      intro: `Qui la truffa passa dalla fiducia: un familiare, un amico, una persona che sembra interessata a te.`,
      scams: [
        {
          id: `finto-figlio`,
          title: `"Ciao mamma, ho cambiato numero"`,
          how: `Un numero sconosciuto scrive fingendosi tuo figlio o tua figlia: il telefono si è rotto, questo è il numero nuovo. Dopo pochi messaggi arriva la richiesta: un bonifico urgente per una fattura, "te li ridò domani".`,
          example: { kind: `chat`, from: `+39 3xx xxx xxxx`, text: `Ciao mamma, mi è caduto il telefono in acqua, questo è il mio numero nuovo, salvalo. Devo pagare una fattura urgente, mi fai un bonifico? Domani ti ridò tutto ❤️` },
          flags: [`Numero sconosciuto che si presenta come familiare`, `Non usa il tuo nome né soprannomi`, `Evita di fare una chiamata vocale`],
          todo: [`Chiama il vecchio numero del familiare`, `Fai una domanda che solo lui conosce`, `Usa la parola d'ordine di famiglia`],
          vignette: `whatsapp`,
        },
        {
          id: `codice-6-cifre`,
          title: `"Ti ho mandato un codice per sbaglio": il furto dell'account`,
          how: `Un amico (in realtà il suo account è già stato rubato) ti chiede di girargli un codice a 6 cifre "arrivato per errore", oppure di votare sua nipote a un concorso. È il codice di verifica del tuo WhatsApp: dandolo, perdi l'account e il truffatore chiede soldi a tutti i tuoi contatti.`,
          example: { kind: `chat`, from: `Marco`, text: `Ciao! Ti è arrivato un codice di 6 cifre? L'ho mandato al tuo numero per sbaglio, me lo inoltri per favore?` },
          flags: [`Richiesta di un codice arrivato via SMS`, `Link per "votare" o "verificare"`],
          todo: [`Non girare mai codici di verifica, a nessuno`, `Attiva la verifica in due passaggi di WhatsApp (PIN + email)`, `Se l'hai perso: reinstalla WhatsApp, verifica il numero e avvisa i contatti`],
        },
        {
          id: `romance`,
          title: `La truffa sentimentale`,
          how: `Un profilo affascinante (militare in missione, medico all'estero, imprenditore) ti corteggia per settimane con attenzioni e promesse. Poi arrivano le richieste: soldi per la dogana, un'emergenza, un biglietto aereo. Spesso diventa anche una truffa di investimenti in criptovalute.`,
          flags: [`Non si fa mai vedere dal vivo`, `Storie strappalacrime e richieste di denaro`, `Invito a investire insieme`],
          todo: [`Cerca le sue foto con la ricerca inversa per immagini`, `Non mandare soldi a chi non hai mai incontrato`, `Parlane con una persona di fiducia`],
          ai: `Foto, messaggi e persino videochiamate possono essere generati con l'intelligenza artificiale.`,
          vignette: `romance`,
        },
        {
          id: `sextortion`,
          title: `Il ricatto a sfondo sessuale e il finto hacker`,
          how: `C'è la versione di massa: un'email dice di averti filmato con la webcam e chiede soldi in Bitcoin, a volte citando una tua vecchia password rubata per sembrare credibile. Di solito non esiste nessun video. E c'è quella reale: dopo uno scambio di immagini intime con un profilo falso arriva il ricatto. Nel 2025 i casi trattati dalla Polizia Postale sono stati 1.225.`,
          example: { kind: `email`, from: `Sconosciuto`, text: `Ho preso il controllo del tuo dispositivo e ti ho registrato con la webcam. Paga 530 € in Bitcoin entro 48 ore o invio il video a tutti i tuoi contatti.` },
          flags: [`Minacce, scadenze e pagamento in criptovalute`, `Una tua vecchia password nel testo`],
          todo: [`Non pagare e non rispondere`, `Conserva le prove e denuncia alla Polizia Postale`, `Cambia la password citata`],
          ai: `Oggi possono creare immagini intime false partendo da foto normali: non è colpa tua, denuncia.`,
          vignette: `blackmail`,
        },
        {
          id: `lavoro`,
          title: `Lavori facili da casa e "like" pagati`,
          how: `Un messaggio su WhatsApp o Telegram offre 50-300 € al giorno per mettere "mi piace" o scrivere recensioni. I primi pagamenti arrivano davvero, per guadagnare la tua fiducia. Poi entri in un gruppo dove devi versare soldi per "sbloccare compiti premium". Un'indagine di Venezia nel 2026 ha scoperto circa 500.000 € sottratti così.`,
          example: { kind: `chat`, from: `Recruiter HR`, text: `Ciao! Cerchiamo collaboratori part-time: 50-300 € al giorno da casa mettendo like su YouTube. Ti interessa?` },
          flags: [`Offerte di lavoro mai richieste`, `Per guadagnare devi prima pagare`, `Ti chiedono di ricevere e girare soldi di altri`],
          todo: [`Un vero lavoro non ti chiede mai soldi`, `Non prestare il tuo conto: rischi l'accusa di riciclaggio`],
          vignette: `job`,
        },
      ],
    },
    {
      id: `acquisti`,
      title: `Acquisti, annunci e vacanze`,
      intro: `Prezzi irresistibili, venditori gentilissimi e fretta di concludere: il copione è sempre lo stesso.`,
      scams: [
        {
          id: `negozi-falsi`,
          title: `Negozi online falsi pubblicizzati sui social`,
          how: `Una pubblicità sponsorizzata annuncia "svuotiamo il magazzino, -80%" su scarpe, borse o elettronica di marca. Il sito, spesso creato con l'intelligenza artificiale, sembra vero, ma la merce non arriva o è contraffatta. Nel 2026 girano anche molti falsi biglietti per concerti.`,
          example: { kind: `ad`, from: `Sponsorizzato`, text: `CHIUSURA NEGOZIO! Tutto al -80% solo per oggi. Ultimi pezzi disponibili 🔥` },
          flags: [`Sconti irrealistici e conto alla rovescia`, `Nessuna partita IVA, indirizzo o recapito`, `Si paga solo con bonifico o criptovalute`],
          todo: [`Usa pagamenti con tutela (carta di credito, PayPal "beni e servizi")`, `Cerca recensioni su siti esterni`, `Diffida dei siti registrati da pochi giorni`],
          vignette: `shop`,
        },
        {
          id: `marketplace`,
          title: `Il finto acquirente su Subito, Vinted e Marketplace`,
          how: `Vendi un oggetto e un "acquirente" ti scrive di aver già pagato con il servizio di spedizione: ti basta cliccare un link per "ricevere i soldi". La pagina chiede i dati della tua carta. Oppure è il venditore a chiedere un anticipo con bonifico o ricarica e poi sparire.`,
          example: { kind: `chat`, from: `Acquirente`, text: `Ho già pagato con il servizio corriere, clicca qui per confermare e ricevere il pagamento sulla tua carta: [link]` },
          flags: [`Invito a uscire dalla chat della piattaforma`, `Per "ricevere" soldi ti chiedono i dati della carta`, `Richieste di pagamento da sconosciuti su app come BANCOMAT Pay`],
          todo: [`Resta sempre nella chat e nel pagamento della piattaforma`, `Per ricevere soldi non servono mai i dati della tua carta`, `Segnala l'utente dall'app`],
        },
        {
          id: `case-vacanza`,
          title: `Case vacanza e affitti che non esistono`,
          how: `Annunci con foto bellissime (rubate o generate) e prezzi bassi. Il "proprietario" vive all'estero e chiede una caparra del 50% o più con bonifico o ricarica. All'arrivo la casa non esiste o è di qualcun altro. Stesso schema per gli affitti agli studenti.`,
          flags: [`Caparra alta prima di vedere la casa`, `Pagamento fuori dalla piattaforma`, `Proprietario irraggiungibile di persona`],
          todo: [`Paga solo dentro la piattaforma di prenotazione`, `Controlla l'indirizzo su una mappa e le foto con la ricerca inversa`, `Una caparra ragionevole è intorno al 20%`],
        },
        {
          id: `qr`,
          title: `I QR code truccati (quishing)`,
          how: `Sui parcometri vengono incollati adesivi con un QR "paga la sosta" che porta a un sito falso. Lo stesso trucco compare su finte multe sotto il tergicristallo, avvisi di pacchi ed email che chiedono di "scansionare per verificare il conto".`,
          flags: [`Adesivi incollati sopra il QR originale`, `Dopo la scansione, un indirizzo strano`],
          todo: [`Paga la sosta dall'app ufficiale del Comune o del gestore`, `Controlla sempre l'indirizzo che si apre dopo la scansione`],
          vignette: `qr`,
        },
        {
          id: `premi`,
          title: `Premi, lotterie ed eredità`,
          how: `"Congratulazioni, hai vinto un iPhone!": basta pagare 2 € di spedizione. In realtà attivi un abbonamento nascosto sulla carta. Varianti: eredità milionarie da notai esteri, premi a nome di supermercati.`,
          example: { kind: `sms`, from: `Premio`, text: `Congratulazioni! Sei stato selezionato per vincere un iPhone 17. Paga solo 2 € di spedizione: [link]` },
          flags: [`Vincite di concorsi a cui non hai partecipato`, `Piccole spese da pagare per ricevere il premio`],
          todo: [`Se non hai partecipato, non hai vinto`, `Non pagare mai spese per ricevere un premio`],
        },
      ],
    },
    {
      id: `soldi`,
      title: `Investimenti e soldi`,
      intro: `Le perdite più alte: spesso i risparmi di una vita, persi in pochi mesi.`,
      scams: [
        {
          id: `investimenti`,
          title: `Investimenti con VIP falsi (deepfake) e falsi broker`,
          how: `Una pubblicità o un finto articolo di giornale mostra un politico, un personaggio TV o il Governatore della Banca d'Italia che rivela "il segreto per guadagnare". Lasci il numero, chiama un "consulente" che ti fa installare un'app di controllo a distanza e ti mostra guadagni finti. Quando provi a prelevare, servono "tasse" e "sblocchi". Variante: una relazione in chat costruita per settimane, poi l'invito a investire in criptovalute.`,
          example: { kind: `ad`, from: `Notizie di oggi`, text: `Il segreto che le banche non vogliono farti sapere: con soli 250 € guadagni 1.500 € a settimana. Guarda l'intervista.` },
          flags: [`Rendimenti garantiti o altissimi`, `VIP che "consigliano" investimenti`, `Richiesta di installare AnyDesk o app simili`, `Per prelevare devi pagare`],
          todo: [`Verifica l'intermediario sui siti di Consob e Banca d'Italia`, `Controlla l'elenco dei siti oscurati dalla Consob`, `Non installare mai app di accesso remoto`],
          ai: `Nel 2025 la Consob ha oscurato siti che usavano deepfake di Meloni, Salvini, Schlein e Calenda.`,
          vignette: `invest`,
        },
        {
          id: `recupero-fondi`,
          title: `Chi promette di recuperare i soldi persi`,
          how: `Dopo una truffa, ti contatta un finto avvocato, una società di recupero o addirittura una falsa "Polizia" o "Europol": hanno ritrovato i tuoi soldi, ma per sbloccarli servono spese legali. È una seconda truffa sulla stessa vittima.`,
          flags: [`Ti contattano loro, sapendo della truffa subita`, `Chiedono un pagamento anticipato`],
          todo: [`Nessun ente pubblico chiede soldi per restituirti somme rubate`, `Parla solo con la Polizia Postale e con avvocati che scegli tu`],
        },
        {
          id: `beneficenza`,
          title: `False raccolte fondi`,
          how: `Dopo alluvioni, terremoti o guerre compaiono pagine che imitano associazioni vere, IBAN privati e raccolte fondi con foto commoventi, a volte generate con l'intelligenza artificiale.`,
          flags: [`IBAN intestati a privati`, `Pagine appena create e molto emotive`],
          todo: [`Dona solo dal sito ufficiale dell'associazione`, `Mai a IBAN ricevuti in chat`],
        },
      ],
    },
    {
      id: `identita`,
      title: `Identità digitale e dati personali`,
      intro: `I tuoi dati valgono soldi: servono ad aprire conti, chiedere prestiti e rendere più credibili altre truffe.`,
      scams: [
        {
          id: `spid`,
          title: `Il furto dello SPID e il "doppio SPID"`,
          how: `Con documenti e selfie rubati (per esempio dal falso SMS INPS), i truffatori attivano un secondo SPID a tuo nome presso un altro gestore, oppure rubano le tue credenziali. Poi cambiano l'IBAN di pensioni e rimborsi e aprono conti o finanziamenti.`,
          flags: [`Email di un gestore SPID che non hai mai usato`, `Rimborsi o pensione che non arrivano`],
          todo: [`Non inviare mai foto di documenti o selfie`, `Usa l'app del gestore per confermare gli accessi`, `In caso di furto: denuncia, sospensione dello SPID e controllo dell'IBAN su MyINPS e Agenzia delle Entrate`],
          vignette: `identity`,
        },
        {
          id: `data-breach`,
          title: `Quando il truffatore conosce già i tuoi dati`,
          how: `Dopo un furto di dati a un'azienda, i truffatori conoscono nome, indirizzo, numero cliente e ultimi acquisti. Li usano per rendere credibili messaggi e telefonate, a volte fingendosi proprio l'azienda colpita o la "Polizia Postale".`,
          flags: [`Sanno molte cose di te e chiedono comunque dati o soldi`],
          todo: [`Conoscere i tuoi dati non rende qualcuno affidabile`, `Cambia le password e usa un gestore di password`, `Puoi controllare la tua email con "Verifica email" su commissariatodips.it`],
        },
      ],
    },
    {
      id: `aziende`,
      title: `Per chi ha un'attività o una partita IVA`,
      intro: `Artigiani, commercianti e professionisti sono bersagli perfetti: pagano fatture ogni giorno.`,
      scams: [
        {
          id: `iban-fattura`,
          title: `L'IBAN cambiato in fattura e il finto capo`,
          how: `La casella email di un fornitore viene violata, oppure i truffatori usano un indirizzo quasi identico. Arriva una comunicazione con il "nuovo IBAN" per i pagamenti. Variante: il finto titolare chiede un bonifico urgente e riservato. Un caso recente è costato 387.000 €.`,
          example: { kind: `email`, from: `Amministrazione <amministrazione@fornitore-srl.co>`, text: `Vi informiamo che per motivi di audit il nostro conto è cambiato. Da oggi vi preghiamo di effettuare i pagamenti sul nuovo IBAN indicato.` },
          flags: [`Cambio di IBAN comunicato via email`, `Urgenza e riservatezza su un bonifico`],
          todo: [`Verifica ogni cambio di IBAN al telefono, con il numero già in rubrica`, `Attiva l'autenticazione a due fattori sulla posta`, `Due persone controllano i bonifici importanti`],
          vignette: `invoice`,
        },
      ],
    },
  ],
  victim: {
    title: `Sei stato truffato? Cosa fare subito`,
    intro: `Non vergognarti: sei la vittima, non il colpevole. Agire nelle prime ore può fare la differenza.`,
    steps: [
      { title: `Blocca tutto`, text: `Blocca carte e accessi dall'app della banca o al numero sul retro della carta. Per molte carte di debito esiste anche il numero verde interbancario 800 822 056 (dall'estero +39 02 6084 3768).` },
      { title: `Chiedi il richiamo del bonifico`, text: `Chiama subito la banca e chiedi di bloccare o richiamare il bonifico: con i bonifici istantanei ogni minuto conta.` },
      { title: `Metti al sicuro gli account`, text: `Cambia le password (prima email e banca), attiva l'autenticazione a due fattori e disconnetti i dispositivi che non riconosci.` },
      { title: `Raccogli le prove`, text: `Screenshot di messaggi e chat, email, numeri di telefono, IBAN del destinatario, estratti conto, link. Non cancellare nulla.` },
      { title: `Denuncia`, text: `Presenta denuncia in un ufficio di Polizia o dei Carabinieri e segnala il caso sul sito della Polizia Postale. La denuncia serve anche per chiedere il rimborso alla banca.` },
      { title: `Avvisa gli altri`, text: `Se è stato rubato un tuo account, avvisa i contatti: potrebbero ricevere richieste di soldi a tuo nome.` },
    ],
  },
  contacts: {
    title: `A chi rivolgersi in Italia`,
    intro: `I numeri e i siti ufficiali. Salvali adesso, prima di averne bisogno.`,
    items: [
      { name: `Emergenza`, detail: `Se sei in pericolo o qualcuno è alla tua porta per ritirare soldi.`, phone: `112` },
      { name: `Polizia Postale – Commissariato di P.S. Online`, detail: `Segnalazioni, informazioni e "Verifica email".`, url: `https://www.commissariatodips.it` },
      { name: `Blocco carte di debito (interbancario)`, detail: `Vale per molte banche, non per tutte e non per le carte di credito: in quel caso usa il numero della tua banca.`, phone: `800 822 056` },
      { name: `CERT-AgID`, detail: `Inoltra le email sospette per aiutare a bloccare le campagne.`, url: `mailto:malware@cert-agid.gov.it` },
      { name: `Consob – siti oscurati`, detail: `Controlla se un sito di investimenti è stato bloccato.`, url: `https://www.consob.it/web/area-pubblica/oscuramenti` },
      { name: `Garante per la protezione dei dati personali`, detail: `Per violazioni dei tuoi dati personali.`, url: `https://www.garanteprivacy.it` },
    ],
    note: `Social e app: usa sempre la funzione "Segnala" della piattaforma (WhatsApp, Facebook, Instagram, Subito, Vinted, Airbnb).`,
  },
  whyReport: {
    title: `Perché denunciare è importante`,
    items: [
      `Permette di avviare le indagini e fermare i truffatori prima che colpiscano altri.`,
      `Aiuta a riconoscere e bloccare le nuove campagne.`,
      `Serve per chiedere il rimborso alla banca e limitare i danni.`,
      `Rende più sicuro il mondo digitale per tutti.`,
      `Non avere vergogna: chi deve vergognarsi è il truffatore, non tu.`,
    ],
  },
  ui: {
    toc: `Indice`,
    print: `Scarica o stampa il manuale`,
    howItWorks: `Come funziona`,
    example: `Esempio reale`,
    flags: `Segnali d'allarme`,
    todo: `Cosa fare`,
    ai: `Con l'intelligenza artificiale`,
    checkmailTitle: `Hai ricevuto un'email sospetta?`,
    checkmailText: `Con KUMANI CheckMail la controlli in pochi secondi: mittente, link, allegati e testo sotto la lente.`,
    checkmailCta: `Apri CheckMail`,
    updated: `Aggiornato a settembre 2026 con i dati di Polizia Postale, CERT-AgID, Consob e AGCOM.`,
    disclaimer: `Questo manuale ha scopo informativo e non sostituisce il parere delle forze dell'ordine, della tua banca o di un legale. Le truffe cambiano continuamente: nel dubbio, fermati e chiedi.`,
    copyright: `© KUMANI. Puoi condividerlo liberamente per aiutare altre persone a difendersi.`,
  },
}

export default it
