import type { GuideContent } from '@/lib/antitruffa/types'

// Manual antiburla KUMANI, português europeu (Portugal).
// Adaptado da versão italiana: burlas locais substituídas por equivalentes
// portugueses, sem estatísticas nem números inventados. Setembro de 2026.
const pt: GuideContent = {
  eyebrow: `Manual KUMANI · Segurança e Verificação`,
  title: `Como se defender das burlas online`,
  motto: `Nem tudo o que é grátis vale pouco. Este pode valer as suas poupanças.`,
  lead: `As burlas de hoje já não têm erros de ortografia: usam inteligência artificial, números de telefone falsificados e sites iguais aos verdadeiros. Este manual mostra-lhe, com exemplos reais, como as reconhecer em poucos segundos e o que fazer se alguma coisa já correu mal.`,
  giftNote: `Uma oferta reservada aos Kumani. Leia, guarde e partilhe com quem ama: pais e avós são os alvos preferidos.`,
  stats: [
    { value: `20,9 mil M$`, label: `de perdas comunicadas ao FBI (IC3) em 2025, nos EUA` },
    { value: `~16 mil M$`, label: `em fraudes comunicadas à FTC dos EUA em 2025` },
    { value: `269 M€`, label: `roubados online em Itália em 2025 (Polizia Postale)` },
    { value: `1.829`, label: `sites de falsos investimentos bloqueados pela Consob, em Itália` },
  ],
  statsSource: `Fontes: FBI IC3 2025; FTC Consumer Sentinel 2025; Polizia Postale, relatório 2025; Consob, 24/09/2026.`,
  tenSeconds: {
    title: `O teste dos 10 segundos`,
    intro: `Antes de clicar, responder ou pagar, pare e faça a si mesmo estas perguntas. Se uma só resposta for "sim", é quase de certeza uma burla.`,
    items: [
      `Está a apressar-me ou a ameaçar-me (conta bloqueada, multa, queixa)?`,
      `Pede-me palavras-passe, códigos, PIN, dados do cartão ou fotografias de documentos?`,
      `Pede-me para pagar por transferência imediata, MB WAY, cartão-presente ou criptomoedas?`,
      `Promete-me ganhos fáceis, prémios ou preços bons demais para serem verdade?`,
      `Pede-me para não contar a ninguém ou para ficar ao telefone?`,
      `Vem de um número ou endereço que não conheço, mesmo que diga ser alguém que conheço?`,
    ],
  },
  rules: {
    title: `As 6 regras de ouro`,
    items: [
      { title: `Desligue e ligue você`, text: `Banco, PSP, GNR, Segurança Social: se o contactarem, desligue e ligue para o número oficial que você mesmo procurou. O número que aparece no ecrã pode ser falsificado.` },
      { title: `Nunca dê códigos a ninguém`, text: `Nenhum funcionário verdadeiro lhe vai pedir códigos de confirmação, PIN, palavras-passe ou o código de 6 dígitos do WhatsApp. Quem os pede é um burlão, sempre.` },
      { title: `Abra você o site`, text: `Não use os links que recebe: abra a app oficial ou escreva você o endereço do site no navegador.` },
      { title: `Dupla proteção em tudo`, text: `Ative a autenticação de dois fatores no email, no banco, nas redes sociais e no WhatsApp (verificação em dois passos). Use uma palavra-passe diferente para cada serviço.` },
      { title: `Atualize tudo`, text: `Telemóvel, computador e apps atualizados fecham as portas que os burlões usam para entrar. Instale apps só a partir do Google Play ou da App Store.` },
      { title: `Uma palavra-chave na família`, text: `Escolham uma palavra secreta para usar se um familiar pedir dinheiro por causa de uma emergência: hoje em dia as vozes podem ser clonadas.` },
    ],
  },
  chapters: [
    {
      id: `messaggi`,
      title: `Email e SMS`,
      intro: `O canal mais usado: os temas preferidos são encomendas, bancos, multas, portagens e reembolsos de impostos.`,
      scams: [
        {
          id: `phishing`,
          title: `Phishing: o email que imita uma entidade ou uma empresa`,
          how: `Um email com logótipo e tom oficiais (Autoridade Tributária, banco, operadora, empresa de energia) convida-o a clicar num link. O site é uma cópia perfeita do original, muitas vezes criada com inteligência artificial, e serve para lhe roubar credenciais, a Chave Móvel Digital ou os dados do cartão. Às vezes traz um anexo que instala um vírus.`,
          example: { kind: `email`, from: `Autoridade Tributária <reembolsos@at-reembolsos.info>`, text: `Caro contribuinte, tem um reembolso de 312,40 € a seu favor. Para o receber, confirme os seus dados nas próximas 48 horas: [link]` },
          flags: [`Pressa e prazos muito curtos`, `O endereço do remetente ou do site não é o oficial`, `Pede dados do cartão, palavras-passe ou a Chave Móvel Digital`, `Anexos .zip, .html ou .js`],
          todo: [`Não clique: abra você o site oficial ou a app`, `Os reembolsos verdadeiros consultam-se no Portal das Finanças, entrando pelo endereço oficial`, `Se já introduziu dados: mude as palavras-passe e ligue para o banco`],
          ai: `Os textos já não têm erros e os sites falsos são idênticos: não confie no aspeto, verifique o endereço.`,
          vignette: `email`,
        },
        {
          id: `clickfix`,
          title: `O falso "Não sou um robô"`,
          how: `Um site mostra-lhe uma falsa verificação anti-robô e pede-lhe para carregar em algumas teclas (por exemplo Windows+R, depois Ctrl+V e Enter). Na realidade está a colar e a executar um comando que instala um vírus. Esta técnica, chamada ClickFix, cresceu muito nos últimos tempos.`,
          flags: [`Uma verificação que pede para carregar em combinações de teclas`, `Instruções para abrir "Executar" ou a linha de comandos`],
          todo: [`Feche a página: nenhuma verificação verdadeira pede para carregar em teclas`, `Se já o fez, desligue a internet e peça a alguém de confiança para verificar o computador`],
        },
        {
          id: `smishing-inps`,
          title: `SMS da "Segurança Social" ou das "Finanças": a caça aos seus documentos`,
          how: `Um SMS em nome da Segurança Social ou do Portal das Finanças avisa que tem de atualizar os seus dados para não perder uma prestação ou um reembolso. O site falso pede o IBAN, fotografias do Cartão de Cidadão, da carta de condução, recibos de vencimento e até uma selfie com o documento. Com este material roubam a sua identidade, abrem contas em seu nome e revendem os documentos.`,
          example: { kind: `sms`, from: `SegSocial`, text: `Seguranca Social: para nao perder a sua prestacao, atualize os seus dados ainda hoje: [link]` },
          flags: [`A Segurança Social e as Finanças não pedem para atualizar dados através de um link num SMS`, `Pedido de fotografias de documentos e selfies`],
          todo: [`Verifique só na Segurança Social Direta ou no Portal das Finanças, entrando pelo endereço oficial`, `Nunca envie fotografias de documentos ou selfies através de um link`, `Se já o fez: apresente queixa e vigie a Chave Móvel Digital, o IBAN e as contas`],
          vignette: `sms`,
        },
        {
          id: `smishing-multe`,
          title: `SMS de multas, portagens e IUC por pagar`,
          how: `Chega um SMS com um valor pequeno "a pagar já": uma portagem ou a Via Verde, uma multa de trânsito, o IUC do carro. O site falso pede os dados do cartão. É uma das burlas por SMS mais frequentes, enviada a milhares de pessoas de uma só vez.`,
          example: { kind: `sms`, from: `Portagens`, text: `Tem uma portagem por pagar de 6,50 €. Evite a coima pagando aqui: [link]` },
          flags: [`Valor pequeno e urgência para "evitar a coima"`, `Link na mensagem`, `Página feita só para telemóvel`],
          todo: [`Consulte portagens, multas e IUC só nos sites e apps oficiais, entrando você pelo endereço certo`, `Não pague nada através de links recebidos por SMS`, `Nunca introduza os dados do cartão a partir de um link recebido`],
          vignette: `sms`,
        },
        {
          id: `pacchi`,
          title: `Encomendas retidas e falsas taxas alfandegárias`,
          how: `Uma mensagem em nome dos CTT, da DHL ou de outra transportadora diz que a sua encomenda está parada e que faltam uns poucos euros de "portes" ou "taxas". É um dos temas mais usados de todos, porque quase toda a gente está à espera de uma encomenda.`,
          example: { kind: `sms`, from: `CTT`, text: `A sua encomenda esta retida na alfandega. Pague 1,99 € de taxas para a entrega: [link]` },
          flags: [`Não sabe de que encomenda se trata`, `Pede poucos euros com o cartão`],
          todo: [`Siga a encomenda no site do vendedor ou da transportadora, escrevendo você o endereço`, `As taxas verdadeiras pagam-se à transportadora ou por canais oficiais`],
        },
        {
          id: `account-sospeso`,
          title: `"A sua conta foi suspensa" (Netflix, Amazon, PayPal)`,
          how: `Um email ou SMS diz que o pagamento da assinatura falhou ou que a conta vai ser fechada. Existe também a versão por telefone: uma voz gravada anuncia uma encomenda cara e pede-lhe para carregar no 1 para a cancelar.`,
          example: { kind: `email`, from: `Netflix <avisos@netflix-suporte.com>`, text: `O pagamento da sua assinatura falhou. Atualize os seus dados nas próximas 24 horas para não perder o acesso: [link]` },
          flags: [`Ameaça de bloqueio ou encerramento`, `Remetente com um domínio "quase" certo`],
          todo: [`Abra diretamente a app ou o site e verifique a sua conta`, `Não carregue em teclas durante chamadas gravadas: desligue`],
        },
        {
          id: `app-malevole`,
          title: `Falsas apps do banco e "atualizações" por SMS`,
          how: `Um SMS convida-o a descarregar uma "atualização de segurança" do banco ou outra app a partir de um link. É uma app pirata (no Android muitas vezes um ficheiro .apk) que pede permissões de "Acessibilidade": assim lê os códigos do banco, pode esvaziar a conta e apagar o telemóvel.`,
          example: { kind: `sms`, from: `Banco`, text: `Caro cliente, a sua app esta desatualizada. Descarregue a atualizacao de seguranca obrigatoria: [link]` },
          flags: [`Link para descarregar uma app fora das lojas oficiais`, `Uma app que pede permissões de Acessibilidade`],
          todo: [`Instale apps só a partir do Google Play ou da App Store`, `Se instalou alguma coisa: modo de voo, ligue para o banco de outro telefone, reponha o telemóvel`],
        },
      ],
    },
    {
      id: `telefono`,
      title: `Chamadas e vozes`,
      intro: `A burla mais cara para as famílias: uma voz simpática, um número que parece verdadeiro e o medo de perder as poupanças.`,
      scams: [
        {
          id: `finto-operatore`,
          title: `O falso funcionário do banco e o falso polícia`,
          how: `Primeiro chega um SMS "de segurança" sobre uma transferência suspeita, depois a chamada. No ecrã aparece o número verdadeiro do banco ou da polícia (está falsificado: chama-se spoofing). O "funcionário", muito profissional, convence-o a passar o dinheiro para uma "conta segura", a ditar-lhe os códigos ou a aprovar uma notificação na app. Há casos em que pessoas mais velhas perdem as poupanças de uma vida.`,
          example: { kind: `call`, from: `Departamento antifraude (número do seu banco)`, text: `Bom dia, bloqueámos uma transferência suspeita de 2.450 €. Para proteger as suas poupanças temos de as passar já para uma conta segura. Não desligue a chamada.` },
          flags: [`"Pôr o dinheiro em segurança" noutra conta`, `Pressa e pedido para não falar com ninguém`, `Pedido de códigos, PIN ou para aprovar uma notificação`],
          todo: [`Desligue e ligue você para o banco, para o número que está no verso do cartão ou na app, alguns minutos depois ou de outro telefone`, `Nenhum banco e nenhuma polícia pede transferências para contas seguras`, `Se já pagou: ligue já para o banco para travar a transferência, depois 112 e queixa`],
          ai: `O número certo no ecrã não garante nada: os burlões conseguem mostrar o número de qualquer entidade.`,
          vignette: `call`,
        },
        {
          id: `voce-clonata`,
          title: `A voz clonada de um familiar`,
          how: `Bastam poucos segundos de um vídeo nas redes sociais para clonar a voz de um filho ou de um neto. Chega uma chamada ou uma mensagem de voz desesperada: um acidente, uma detenção, é preciso já um advogado. Muitas vezes aparece depois um "advogado" ou um estafeta à porta para levar dinheiro e joias.`,
          example: { kind: `call`, from: `Número desconhecido`, text: `Avô, sou eu... tive um acidente, preciso já de dinheiro para o advogado, não digas nada à mãe!` },
          flags: [`Emergência, choro, urgência extrema`, `Pede para não avisar ninguém`, `Número diferente do habitual`],
          todo: [`Desligue e ligue para o número do familiar que já conhece`, `Use a palavra-chave da família`, `Nunca entregue dinheiro ou joias a quem aparece à porta`],
          ai: `Hoje uma voz pode ser imitada com inteligência artificial a partir de poucos segundos de áudio: não confie só no que ouve.`,
        },
        {
          id: `supporto-tecnico`,
          title: `O falso apoio técnico`,
          how: `Enquanto navega, aparece uma janela em ecrã inteiro com uma sirene: "O seu computador está infetado, ligue já para a Microsoft". O falso técnico faz-lhe instalar um programa de controlo remoto e depois cobra-lhe dinheiro ou entra no seu homebanking.`,
          example: { kind: `popup`, from: `Aviso de segurança`, text: `ATENÇÃO! O seu PC está infetado. Não desligue o computador. Ligue já para o apoio técnico: +351 ...` },
          flags: [`Alarmes sonoros e números para ligar`, `Pedido para instalar AnyDesk, TeamViewer ou semelhantes`],
          todo: [`A Microsoft e a Apple nunca mostram números para ligar`, `Feche o navegador, mesmo que tenha de o forçar`, `Não instale nada a pedido de desconhecidos`],
        },
        {
          id: `luce-gas`,
          title: `Os falsos comerciais de eletricidade e gás`,
          how: `Alguém que diz falar "da entidade reguladora" ou de "um serviço de energia" anuncia uma tarifa mais barata ou um reembolso e pede o código CPE da fatura e o IBAN. Com estes dados fazem contratos que não pediu ou roubam os seus dados.`,
          example: { kind: `call`, from: `Serviço de energia`, text: `Bom dia, a partir de segunda-feira passa para a tarifa reduzida. Pode confirmar-me o código CPE que está na sua fatura?` },
          flags: [`Pedido do código CPE, do IBAN ou de uma fotografia da fatura`, `"Entidades" ou "reguladores" que ligam para fazer ofertas`],
          todo: [`Nunca dê códigos da fatura nem o IBAN por telefone`, `Em caso de contratos que não pediu, fale com o seu fornecedor pelos contactos oficiais`],
        },
        {
          id: `sim-swap`,
          title: `O roubo do cartão SIM (SIM swap)`,
          how: `Com documentos falsos ou um cúmplice, o burlão consegue uma segunda via do seu cartão SIM. O seu telemóvel fica sem rede e ele passa a receber os SMS com os códigos do banco.`,
          flags: [`O telemóvel passa de repente para "Sem serviço" ou "Só emergência"`],
          todo: [`Ligue já para a sua operadora e para o banco a partir de outro telefone`, `Ative o PIN do cartão SIM`, `Prefira as notificações na app do banco aos SMS`],
        },
      ],
    },
    {
      id: `chat`,
      title: `WhatsApp, redes sociais e chats`,
      intro: `Aqui a burla passa pela confiança: um familiar, um amigo, alguém que parece interessado em si.`,
      scams: [
        {
          id: `finto-figlio`,
          title: `"Olá mãe, mudei de número"`,
          how: `Um número desconhecido escreve a fingir que é o seu filho ou a sua filha: o telemóvel avariou, este é o número novo. Depois de poucas mensagens vem o pedido: uma transferência ou um MB WAY urgente para pagar uma fatura, "amanhã devolvo-te".`,
          example: { kind: `chat`, from: `+351 9xx xxx xxx`, text: `Olá mãe, o meu telemóvel caiu à água, este é o meu número novo, guarda-o. Tenho de pagar uma fatura urgente, podes fazer-me uma transferência? Amanhã devolvo-te tudo ❤️` },
          flags: [`Número desconhecido que se apresenta como familiar`, `Não usa o seu nome nem alcunhas`, `Evita fazer uma chamada de voz`],
          todo: [`Ligue para o número antigo do familiar`, `Faça uma pergunta que só ele sabe responder`, `Use a palavra-chave da família`],
          vignette: `whatsapp`,
        },
        {
          id: `codice-6-cifre`,
          title: `"Enviei-te um código por engano": o roubo da conta`,
          how: `Um amigo (na verdade a conta dele já foi roubada) pede-lhe para reencaminhar um código de 6 dígitos "que chegou por engano", ou para votar na sobrinha num concurso. É o código de verificação do seu WhatsApp: se o der, perde a conta e o burlão pede dinheiro a todos os seus contactos.`,
          example: { kind: `chat`, from: `Marco`, text: `Olá! Recebeste um código de 6 dígitos? Enviei-o para o teu número por engano, podes reencaminhar-mo, por favor?` },
          flags: [`Pedido de um código recebido por SMS`, `Link para "votar" ou "verificar"`],
          todo: [`Nunca reencaminhe códigos de verificação, a ninguém`, `Ative a verificação em dois passos do WhatsApp (PIN + email)`, `Se perdeu a conta: reinstale o WhatsApp, verifique o número e avise os contactos`],
        },
        {
          id: `romance`,
          title: `A burla sentimental`,
          how: `Um perfil encantador (militar em missão, médico no estrangeiro, empresário) corteja-o durante semanas com atenções e promessas. Depois chegam os pedidos: dinheiro para a alfândega, uma emergência, um bilhete de avião. Muitas vezes transforma-se também numa burla de investimentos em criptomoedas.`,
          flags: [`Nunca aparece em pessoa`, `Histórias de partir o coração e pedidos de dinheiro`, `Convite para investirem juntos`],
          todo: [`Procure as fotografias dele com a pesquisa inversa de imagens`, `Não envie dinheiro a quem nunca conheceu pessoalmente`, `Fale sobre isso com alguém de confiança`],
          ai: `Fotografias, mensagens e até videochamadas podem ser criadas com inteligência artificial.`,
          vignette: `romance`,
        },
        {
          id: `sextortion`,
          title: `A chantagem sexual e o falso hacker`,
          how: `Há a versão em massa: um email diz que o filmou pela webcam e pede dinheiro em Bitcoin, às vezes citando uma palavra-passe antiga sua, roubada, para parecer credível. Normalmente não existe vídeo nenhum. E há a versão real: depois de uma troca de imagens íntimas com um perfil falso, chega a chantagem.`,
          example: { kind: `email`, from: `Desconhecido`, text: `Tomei o controlo do seu dispositivo e gravei-o com a webcam. Pague 530 € em Bitcoin nas próximas 48 horas ou envio o vídeo a todos os seus contactos.` },
          flags: [`Ameaças, prazos e pagamento em criptomoedas`, `Uma palavra-passe antiga sua no texto`],
          todo: [`Não pague e não responda`, `Guarde as provas e apresente queixa à polícia`, `Mude a palavra-passe citada`],
          ai: `Hoje conseguem criar imagens íntimas falsas a partir de fotografias normais: a culpa não é sua, apresente queixa.`,
          vignette: `blackmail`,
        },
        {
          id: `lavoro`,
          title: `Trabalhos fáceis a partir de casa e "gostos" pagos`,
          how: `Uma mensagem no WhatsApp ou no Telegram oferece 50 a 300 € por dia para pôr "gosto" em vídeos ou escrever avaliações. Os primeiros pagamentos chegam mesmo, para ganhar a sua confiança. Depois entra num grupo onde tem de pagar para "desbloquear tarefas premium" e o dinheiro nunca mais volta.`,
          example: { kind: `chat`, from: `Recrutamento RH`, text: `Olá! Procuramos colaboradores em part-time: 50 a 300 € por dia a partir de casa, a pôr gostos no YouTube. Tem interesse?` },
          flags: [`Ofertas de trabalho que nunca pediu`, `Para ganhar tem de pagar primeiro`, `Pedem-lhe para receber e reenviar dinheiro de outras pessoas`],
          todo: [`Um trabalho verdadeiro nunca lhe pede dinheiro`, `Não empreste a sua conta: arrisca ser acusado de branqueamento de capitais`],
          vignette: `job`,
        },
      ],
    },
    {
      id: `acquisti`,
      title: `Compras, anúncios e férias`,
      intro: `Preços irresistíveis, vendedores muito simpáticos e pressa em fechar o negócio: o guião é sempre o mesmo.`,
      scams: [
        {
          id: `negozi-falsi`,
          title: `Lojas online falsas anunciadas nas redes sociais`,
          how: `Um anúncio patrocinado promete "liquidação total, -80%" em sapatilhas, malas ou eletrónica de marca. O site, muitas vezes criado com inteligência artificial, parece verdadeiro, mas a mercadoria não chega ou é contrafeita. Circulam também muitos bilhetes falsos para concertos.`,
          example: { kind: `ad`, from: `Patrocinado`, text: `A LOJA VAI FECHAR! Tudo a -80% só hoje. Últimas unidades disponíveis 🔥` },
          flags: [`Descontos irrealistas e contagem decrescente`, `Sem NIF, morada ou contactos da empresa`, `Só aceita transferência, MB WAY para um particular ou criptomoedas`],
          todo: [`Use pagamentos com proteção (cartão de crédito, PayPal "bens e serviços")`, `Procure avaliações em sites independentes`, `Desconfie de sites registados há poucos dias`],
          vignette: `shop`,
        },
        {
          id: `marketplace`,
          title: `O falso comprador no OLX, na Vinted e no Marketplace`,
          how: `Vende um objeto e um "comprador" diz que já pagou através do serviço de envio: basta clicar num link para "receber o dinheiro", e a página pede os dados do seu cartão. Muito comum em Portugal é a versão MB WAY: o "comprador" pede-lhe para ir ao multibanco ou à app MB WAY e seguir uns passos para "receber" o pagamento. Na verdade está a enviar-lhe dinheiro ou a ligar o telemóvel dele à sua conta. Outras vezes é o vendedor que pede um sinal e desaparece.`,
          example: { kind: `chat`, from: `Comprador`, text: `Já paguei, mas para receber tem de ir ao multibanco, escolher MB WAY e pôr o meu número. Eu vou-lhe dizendo os passos.` },
          flags: [`Convite para sair do chat da plataforma`, `Para "receber" dinheiro pedem-lhe dados do cartão ou uma operação MB WAY`, `Instruções ao telefone enquanto está no multibanco`],
          todo: [`Fique sempre no chat e no pagamento da plataforma`, `Para receber dinheiro nunca tem de fazer nenhuma operação no multibanco nem dar os dados do cartão`, `Nunca associe ao seu MB WAY um número que não é seu`, `Denuncie o utilizador na app`],
        },
        {
          id: `case-vacanza`,
          title: `Casas de férias e arrendamentos que não existem`,
          how: `Anúncios com fotografias lindíssimas (roubadas ou geradas) e preços baixos. O "senhorio" vive no estrangeiro e pede um sinal de metade ou mais por transferência ou MB WAY. À chegada, a casa não existe ou é de outra pessoa. O mesmo esquema aparece nos quartos para estudantes.`,
          flags: [`Sinal alto antes de ver a casa`, `Pagamento fora da plataforma`, `Senhorio impossível de conhecer pessoalmente`],
          todo: [`Pague só dentro da plataforma de reservas`, `Verifique a morada num mapa e as fotografias com a pesquisa inversa`, `Visite a casa, ou peça a alguém de confiança, antes de pagar um arrendamento`],
        },
        {
          id: `qr`,
          title: `Os códigos QR adulterados (quishing)`,
          how: `Nos parquímetros são colados autocolantes com um QR "pague o estacionamento" que leva a um site falso. O mesmo truque aparece em falsas multas no para-brisas, avisos de encomendas e emails que pedem para "digitalizar para verificar a conta".`,
          flags: [`Autocolantes colados por cima do QR original`, `Depois de ler o código, abre um endereço estranho`],
          todo: [`Pague o estacionamento pela app oficial da câmara municipal ou da empresa gestora`, `Verifique sempre o endereço que se abre depois de ler o código`],
          vignette: `qr`,
        },
        {
          id: `premi`,
          title: `Prémios, sorteios e heranças`,
          how: `"Parabéns, ganhou um iPhone!": basta pagar 2 € de portes. Na verdade está a ativar uma assinatura escondida no cartão. Variantes: heranças milionárias de notários estrangeiros, prémios em nome de supermercados.`,
          example: { kind: `sms`, from: `Premio`, text: `Parabens! Foi selecionado para ganhar um iPhone 17. Pague apenas 2 € de portes: [link]` },
          flags: [`Prémios de concursos em que não participou`, `Pequenos custos a pagar para receber o prémio`],
          todo: [`Se não participou, não ganhou`, `Nunca pague custos para receber um prémio`],
        },
      ],
    },
    {
      id: `soldi`,
      title: `Investimentos e dinheiro`,
      intro: `As perdas mais altas: muitas vezes as poupanças de uma vida, perdidas em poucos meses.`,
      scams: [
        {
          id: `investimenti`,
          title: `Investimentos com famosos falsos (deepfake) e falsos corretores`,
          how: `Um anúncio ou uma falsa notícia de jornal mostra um político, uma figura da televisão ou um banqueiro conhecido a revelar "o segredo para ganhar dinheiro". Deixa o seu número, liga-lhe um "consultor" que o faz instalar uma app de controlo remoto e lhe mostra ganhos falsos. Quando tenta levantar o dinheiro, aparecem "impostos" e "taxas de desbloqueio". Variante: uma relação construída no chat durante semanas, depois o convite para investir em criptomoedas.`,
          example: { kind: `ad`, from: `Notícias de hoje`, text: `O segredo que os bancos não querem que saiba: com apenas 250 € ganha 1.500 € por semana. Veja a entrevista.` },
          flags: [`Rendimentos garantidos ou altíssimos`, `Famosos que "recomendam" investimentos`, `Pedido para instalar AnyDesk ou apps semelhantes`, `Para levantar o dinheiro tem de pagar`],
          todo: [`Confirme se a entidade está autorizada nos sites oficiais dos supervisores (CMVM e Banco de Portugal)`, `Desconfie de quem o contacta sem ter pedido`, `Nunca instale apps de acesso remoto`],
          ai: `Circulam vídeos falsos, criados com inteligência artificial, de políticos e figuras públicas a "recomendar" investimentos: nenhum é verdadeiro.`,
          vignette: `invest`,
        },
        {
          id: `recupero-fondi`,
          title: `Quem promete recuperar o dinheiro perdido`,
          how: `Depois de uma burla, contacta-o um falso advogado, uma empresa de recuperação ou até uma falsa "Polícia" ou "Europol": encontraram o seu dinheiro, mas para o desbloquear são precisas despesas legais. É uma segunda burla à mesma vítima.`,
          flags: [`São eles que o contactam, sabendo da burla que sofreu`, `Pedem um pagamento adiantado`],
          todo: [`Nenhuma entidade pública pede dinheiro para lhe devolver valores roubados`, `Fale só com a polícia e com advogados escolhidos por si`],
        },
        {
          id: `beneficenza`,
          title: `Falsas angariações de fundos`,
          how: `Depois de cheias, incêndios, sismos ou guerras aparecem páginas que imitam associações verdadeiras, IBAN de particulares e angariações com fotografias comoventes, às vezes geradas com inteligência artificial.`,
          flags: [`IBAN em nome de particulares`, `Páginas acabadas de criar e muito emotivas`],
          todo: [`Doe só a partir do site oficial da associação`, `Nunca para um IBAN recebido num chat`],
        },
      ],
    },
    {
      id: `identita`,
      title: `Identidade digital e dados pessoais`,
      intro: `Os seus dados valem dinheiro: servem para abrir contas, pedir créditos e tornar outras burlas mais credíveis.`,
      scams: [
        {
          id: `spid`,
          title: `O roubo da Chave Móvel Digital`,
          how: `Com documentos e selfies roubados (por exemplo com o falso SMS da Segurança Social) ou com os seus códigos, os burlões entram nos serviços públicos em seu nome com a Chave Móvel Digital. Depois mudam o IBAN de pensões e reembolsos, acedem aos seus dados e abrem contas ou créditos.`,
          flags: [`Um SMS com um código da Chave Móvel Digital que não pediu`, `Reembolsos ou pensão que não chegam`],
          todo: [`Nunca envie fotografias de documentos ou selfies`, `Nunca diga a ninguém o PIN ou os códigos da Chave Móvel Digital`, `Em caso de roubo: apresente queixa, cancele a Chave Móvel Digital e confirme o IBAN na Segurança Social Direta e no Portal das Finanças`],
          vignette: `identity`,
        },
        {
          id: `data-breach`,
          title: `Quando o burlão já conhece os seus dados`,
          how: `Depois de um roubo de dados a uma empresa, os burlões sabem o seu nome, morada, número de cliente e últimas compras. Usam isso para tornar credíveis mensagens e chamadas, às vezes fingindo ser a própria empresa atacada ou a "polícia".`,
          flags: [`Sabem muitas coisas sobre si e mesmo assim pedem dados ou dinheiro`],
          todo: [`Conhecer os seus dados não torna ninguém de confiança`, `Mude as palavras-passe e use um gestor de palavras-passe`, `Pode verificar se o seu email apareceu em fugas de dados em haveibeenpwned.com`],
        },
      ],
    },
    {
      id: `aziende`,
      title: `Para quem tem um negócio ou trabalha por conta própria`,
      intro: `Artesãos, comerciantes e profissionais são alvos perfeitos: pagam faturas todos os dias.`,
      scams: [
        {
          id: `iban-fattura`,
          title: `O IBAN trocado na fatura e o falso patrão`,
          how: `A caixa de email de um fornecedor é pirateada, ou os burlões usam um endereço quase idêntico. Chega uma comunicação com o "novo IBAN" para os pagamentos. Variante: o falso administrador pede uma transferência urgente e confidencial. Estas burlas podem custar dezenas ou centenas de milhares de euros a uma empresa.`,
          example: { kind: `email`, from: `Contabilidade <contabilidade@fornecedor-lda.co>`, text: `Informamos que, por motivos de auditoria, a nossa conta bancária mudou. A partir de hoje pedimos que efetuem os pagamentos para o novo IBAN indicado.` },
          flags: [`Mudança de IBAN comunicada por email`, `Urgência e confidencialidade numa transferência`],
          todo: [`Confirme cada mudança de IBAN por telefone, com o número que já tem guardado`, `Ative a autenticação de dois fatores no email`, `Duas pessoas verificam as transferências importantes`],
          vignette: `invoice`,
        },
      ],
    },
  ],
  victim: {
    title: `Foi vítima de uma burla? O que fazer já`,
    intro: `Não tenha vergonha: é a vítima, não o culpado. Agir nas primeiras horas pode fazer toda a diferença.`,
    steps: [
      { title: `Bloqueie tudo`, text: `Bloqueie cartões e acessos pela app do banco ou pelo número que está no verso do cartão.` },
      { title: `Peça para travar a transferência`, text: `Ligue já para o banco e peça para bloquear ou anular a transferência ou o MB WAY: com as transferências imediatas, cada minuto conta.` },
      { title: `Proteja as contas`, text: `Mude as palavras-passe (primeiro do email e do banco), ative a autenticação de dois fatores e desligue os dispositivos que não reconhece.` },
      { title: `Junte as provas`, text: `Capturas de ecrã de mensagens e chats, emails, números de telefone, IBAN do destinatário, extratos bancários, links. Não apague nada.` },
      { title: `Apresente queixa`, text: `Apresente queixa na PSP, na GNR ou na Polícia Judiciária. A queixa serve também para pedir ao banco a devolução do dinheiro.` },
      { title: `Avise os outros`, text: `Se lhe roubaram uma conta, avise os seus contactos: podem receber pedidos de dinheiro em seu nome.` },
    ],
  },
  contacts: {
    title: `A quem recorrer em Portugal`,
    intro: `Os números e sites oficiais. Guarde-os agora, antes de precisar deles.`,
    items: [
      { name: `Emergência`, detail: `Se está em perigo ou se alguém está à sua porta para levar dinheiro.`, phone: `112` },
      { name: `Linha Internet Segura (APAV / Centro Internet Segura)`, detail: `Apoio gratuito e confidencial a vítimas de burlas e crimes online.`, phone: `800 21 90 90`, url: `https://www.internetsegura.pt` },
      { name: `Polícia Judiciária`, detail: `Alertas sobre burlas e informação para apresentar queixa.`, url: `https://www.policiajudiciaria.pt` },
      { name: `CNCS (Centro Nacional de Cibersegurança)`, detail: `Para reportar incidentes de cibersegurança, a título particular ou como empresa.`, url: `https://www.cncs.gov.pt/pt/como-reportar-um-incidente/` },
    ],
    note: `Redes sociais e apps: use sempre a função "Denunciar" da plataforma (WhatsApp, Facebook, Instagram, OLX, Vinted, Airbnb). Se vive no Brasil: registe a ocorrência na delegacia de polícia e contacte logo o seu banco.`,
  },
  whyReport: {
    title: `Porque é importante apresentar queixa`,
    items: [
      `Permite abrir uma investigação e travar os burlões antes que façam outras vítimas.`,
      `Ajuda a reconhecer e bloquear as novas campanhas.`,
      `Serve para pedir a devolução ao banco e limitar os prejuízos.`,
      `Torna o mundo digital mais seguro para todos.`,
      `Não tenha vergonha: quem se deve envergonhar é o burlão, não você.`,
    ],
  },
  ui: {
    toc: `Índice`,
    print: `Descarregar ou imprimir o manual`,
    howItWorks: `Como funciona`,
    example: `Exemplo real`,
    flags: `Sinais de alarme`,
    todo: `O que fazer`,
    ai: `Com inteligência artificial`,
    checkmailTitle: `Recebeu um email suspeito?`,
    checkmailText: `Com o KUMANI CheckMail verifica-o em poucos segundos: remetente, links, anexos e texto à lupa.`,
    checkmailCta: `Abrir CheckMail`,
    updated: `Atualizado em setembro de 2026 com dados do FBI, da FTC, da Polizia Postale, do CERT-AgID e da Consob.`,
    disclaimer: `Este manual tem fins informativos e não substitui o conselho das autoridades, do seu banco ou de um advogado. As burlas mudam constantemente: na dúvida, pare e pergunte.`,
    copyright: `© KUMANI. Pode partilhá-lo livremente para ajudar outras pessoas a defenderem-se.`,
  },
}

export default pt
